# Generated by Django 5.2.8 on 2025-12-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='chart_of_ac_account_af5267_idx',
            old_name='chart_of_ac_account_6f8d8e_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='chart_of_ac_isActiv_fd7ada_idx',
            old_name='chart_of_ac_isActiv_3k9e5c_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='chart_of_ac_account_8be151_idx',
            old_name='chart_of_ac_account_8m2l9n_idx',
        ),
    ]
