# Generated by Django 5.2.7 on 2025-12-18 15:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_drop_duplicate_chart_of_accounts_table'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherNumber', models.CharField(db_index=True, max_length=50, unique=True)),
                ('entryDate', models.DateField(db_index=True)),
                ('referenceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(help_text='Description of the transaction')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=20)),
                ('totalDebit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('totalCredit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('postedAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to='user.member')),
                ('postedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to='user.member')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_journal_entries', to='user.member')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entryDate', '-voucherNumber'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineNumber', models.IntegerField(help_text='Sequence number of this line in the entry')),
                ('description', models.CharField(blank=True, help_text='Line-specific description', max_length=500, null=True)),
                ('debitAmount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('creditAmount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounts.account')),
                ('journalEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounts.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'ordering': ['journalEntry', 'lineNumber'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['voucherNumber'], name='chart_of_ac_voucher_4c80e5_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['entryDate'], name='chart_of_ac_entryDa_143a94_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status'], name='chart_of_ac_status_45ce5e_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['-entryDate', '-voucherNumber'], name='chart_of_ac_entryDa_319bda_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journalEntry', 'lineNumber'], name='chart_of_ac_journal_1646e6_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account'], name='chart_of_ac_account_a9242e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentryline',
            unique_together={('journalEntry', 'lineNumber')},
        ),
    ]
