# Generated by Django 5.2.8 on 2025-12-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_journalentry_journalentryline_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_account_0fe4f1_idx',
            old_name='chart_of_ac_account_af5267_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_isActiv_0e21dc_idx',
            old_name='chart_of_ac_isActiv_fd7ada_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_account_fb8cb9_idx',
            old_name='chart_of_ac_account_8be151_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounts_jo_voucher_b471d5_idx',
            old_name='chart_of_ac_voucher_4c80e5_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounts_jo_entryDa_e97847_idx',
            old_name='chart_of_ac_entryDa_143a94_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounts_jo_status_3ef0e4_idx',
            old_name='chart_of_ac_status_45ce5e_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='accounts_jo_entryDa_cd4ea0_idx',
            old_name='chart_of_ac_entryDa_319bda_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentryline',
            new_name='accounts_jo_journal_cd168d_idx',
            old_name='chart_of_ac_journal_1646e6_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentryline',
            new_name='accounts_jo_account_c1b9e5_idx',
            old_name='chart_of_ac_account_a9242e_idx',
        ),
    ]
