# Generated by Django 5.2.8 on 2025-12-21 14:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_drop_old_chart_of_accounts_tables'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        # Create VoucherType model
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('journal', 'Journal Voucher'), ('contra', 'Contra Voucher')], max_length=20, unique=True)),
                ('displayName', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('prefix', models.CharField(help_text='Prefix for voucher numbers (e.g., RV, PV, JV, CV)', max_length=10)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_types', to='user.member')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voucher_types', to='user.member')),
            ],
            options={
                'verbose_name': 'Voucher Type',
                'verbose_name_plural': 'Voucher Types',
                'ordering': ['name'],
            },
        ),
        
        # Create VoucherEntry model (similar to JournalEntry but with voucherType relationship)
        migrations.CreateModel(
            name='VoucherEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucherNumber', models.CharField(db_index=True, max_length=50, unique=True)),
                ('entryDate', models.DateField(db_index=True)),
                ('referenceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('narration', models.TextField(help_text='Description of the transaction')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', max_length=20)),
                ('totalDebit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('totalCredit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('postedAt', models.DateTimeField(blank=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_entries', to='user.member')),
                ('postedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_voucher_entries', to='user.member')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voucher_entries', to='user.member')),
                ('voucherType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounts.vouchertype')),
            ],
            options={
                'verbose_name': 'Voucher Entry',
                'verbose_name_plural': 'Voucher Entries',
                'ordering': ['-entryDate', '-voucherNumber'],
            },
        ),
        
        # Create VoucherEntryDetails model (similar to JournalEntryLine)
        migrations.CreateModel(
            name='VoucherEntryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineNumber', models.IntegerField(help_text='Sequence number of this line in the entry')),
                ('description', models.CharField(blank=True, help_text='Line-specific description', max_length=500, null=True)),
                ('debitAmount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('creditAmount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_details', to='accounts.account')),
                ('voucherEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts.voucherentry')),
            ],
            options={
                'verbose_name': 'Voucher Entry Detail',
                'verbose_name_plural': 'Voucher Entry Details',
                'ordering': ['voucherEntry', 'lineNumber'],
            },
        ),
        
        # Add indexes for VoucherEntry
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['voucherNumber'], name='accounts_vo_voucher_4c80e5_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['entryDate'], name='accounts_vo_entryDa_143a94_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['status'], name='accounts_vo_status_45ce5e_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['voucherType'], name='accounts_vo_voucher_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['-entryDate', '-voucherNumber'], name='accounts_vo_entryDa_319bda_idx'),
        ),
        
        # Add indexes for VoucherEntryDetails
        migrations.AddIndex(
            model_name='voucherentrydetails',
            index=models.Index(fields=['voucherEntry', 'lineNumber'], name='accounts_vo_voucher_1646e6_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentrydetails',
            index=models.Index(fields=['account'], name='accounts_vo_account_a9242e_idx'),
        ),
        
        # Add unique constraint for VoucherEntryDetails
        migrations.AlterUniqueTogether(
            name='voucherentrydetails',
            unique_together={('voucherEntry', 'lineNumber')},
        ),
    ]