# Generated by Django 5.2.8 on 2025-12-21 14:10

from django.db import migrations
from django.utils import timezone

def populate_voucher_types(apps, schema_editor):
    VoucherType = apps.get_model('accounts', 'VoucherType')
    Member = apps.get_model('user', 'Member')
    
    # Try to get a member for createdBy/updatedBy fields
    # If no members exist, we'll set these to None
    try:
        member = Member.objects.first()
    except:
        member = None
    
    voucher_types = [
        {
            'name': 'receipt',
            'displayName': 'Receipt Voucher',
            'description': 'Voucher for recording cash receipts',
            'prefix': 'RV',
            'isActive': True,
            'createdBy': member,
            'updatedBy': member,
        },
        {
            'name': 'payment',
            'displayName': 'Payment Voucher',
            'description': 'Voucher for recording cash payments',
            'prefix': 'PV',
            'isActive': True,
            'createdBy': member,
            'updatedBy': member,
        },
        {
            'name': 'journal',
            'displayName': 'Journal Voucher',
            'description': 'Voucher for recording non-cash transactions',
            'prefix': 'JV',
            'isActive': True,
            'createdBy': member,
            'updatedBy': member,
        },
        {
            'name': 'contra',
            'displayName': 'Contra Voucher',
            'description': 'Voucher for recording transfers between cash accounts',
            'prefix': 'CV',
            'isActive': True,
            'createdBy': member,
            'updatedBy': member,
        },
    ]
    
    for vt_data in voucher_types:
        voucher_type, created = VoucherType.objects.get_or_create(
            name=vt_data['name'],
            defaults=vt_data
        )
        if not created:
            # Update existing record if it already exists
            for key, value in vt_data.items():
                setattr(voucher_type, key, value)
            voucher_type.save()

def reverse_populate_voucher_types(apps, schema_editor):
    VoucherType = apps.get_model('accounts', 'VoucherType')
    VoucherType.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vouchertype_voucherentry_voucherentrydetails'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.RunPython(populate_voucher_types, reverse_populate_voucher_types),
    ]