# Generated by Django 5.2.8 on 2025-12-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_populate_voucher_types'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voucherentry',
            new_name='accounts_vo_voucher_297ee1_idx',
            old_name='accounts_vo_voucher_4c80e5_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherentry',
            new_name='accounts_vo_entryDa_81967e_idx',
            old_name='accounts_vo_entryDa_143a94_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherentry',
            new_name='accounts_vo_status_e5b118_idx',
            old_name='accounts_vo_status_45ce5e_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherentry',
            new_name='accounts_vo_voucher_548aa9_idx',
            old_name='accounts_vo_voucher_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherentry',
            new_name='accounts_vo_entryDa_f359d6_idx',
            old_name='accounts_vo_entryDa_319bda_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherentrydetails',
            new_name='accounts_vo_voucher_1c2e70_idx',
            old_name='accounts_vo_voucher_1646e6_idx',
        ),
        migrations.RenameIndex(
            model_name='voucherentrydetails',
            new_name='accounts_vo_account_ad656f_idx',
            old_name='accounts_vo_account_a9242e_idx',
        ),
    ]
