# Generated by Django 5.2.7 on 2025-12-21 15:06

from django.db import migrations


def drop_foreign_keys_and_fields(apps, schema_editor):
    """
    Drop foreign key constraints and fields before deleting tables.
    This is necessary for MySQL which doesn't allow dropping tables with active foreign keys.
    """
    if schema_editor.connection.vendor != 'mysql':
        return
    
    try:
        with schema_editor.connection.cursor() as cursor:
            # Get the database name
            cursor.execute("SELECT DATABASE()")
            db_name = cursor.fetchone()[0]
            
            # Check if the table exists first
            cursor.execute("""
                SELECT COUNT(*)
                FROM information_schema.TABLES
                WHERE TABLE_SCHEMA = %s
                AND TABLE_NAME = 'accounts_journalentryline'
            """, [db_name])
            
            if cursor.fetchone()[0] == 0:
                print("Table accounts_journalentryline does not exist. Skipping.")
                return
            
            # Find and drop foreign key constraints on accounts_journalentryline
            cursor.execute("""
                SELECT CONSTRAINT_NAME
                FROM information_schema.TABLE_CONSTRAINTS
                WHERE TABLE_SCHEMA = %s
                AND TABLE_NAME = 'accounts_journalentryline'
                AND CONSTRAINT_TYPE = 'FOREIGN KEY'
            """, [db_name])
            
            constraints = cursor.fetchall()
            for constraint in constraints:
                constraint_name = constraint[0]
                try:
                    cursor.execute(f"ALTER TABLE accounts_journalentryline DROP FOREIGN KEY `{constraint_name}`")
                    print(f"Dropped foreign key constraint: {constraint_name}")
                except Exception as e:
                    print(f"Error dropping constraint {constraint_name}: {e}")
            
            # Drop columns if they exist (account and journalEntry)
            # Check and drop account column
            cursor.execute("""
                SELECT COUNT(*)
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = %s
                AND TABLE_NAME = 'accounts_journalentryline'
                AND COLUMN_NAME = 'account_id'
            """, [db_name])
            if cursor.fetchone()[0] > 0:
                try:
                    cursor.execute("ALTER TABLE accounts_journalentryline DROP COLUMN account_id")
                    print("Dropped account_id column")
                except Exception as e:
                    print(f"Error dropping account_id column: {e}")
            
            # Check and drop journalEntry column
            cursor.execute("""
                SELECT COUNT(*)
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = %s
                AND TABLE_NAME = 'accounts_journalentryline'
                AND COLUMN_NAME = 'journalEntry_id'
            """, [db_name])
            if cursor.fetchone()[0] > 0:
                try:
                    cursor.execute("ALTER TABLE accounts_journalentryline DROP COLUMN journalEntry_id")
                    print("Dropped journalEntry_id column")
                except Exception as e:
                    print(f"Error dropping journalEntry_id column: {e}")
                    
    except Exception as e:
        print(f"Error in drop_foreign_keys_and_fields: {e}")
        # Don't fail the migration if we can't drop constraints


def reverse_drop_foreign_keys_and_fields(apps, schema_editor):
    """
    Reverse operation - foreign keys will be recreated when models are recreated.
    This is a no-op since we're deleting the models.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_journalentry_createdby_and_more'),
    ]

    operations = [
        # First, drop foreign key constraints and fields manually for MySQL
        migrations.RunPython(drop_foreign_keys_and_fields, reverse_drop_foreign_keys_and_fields),
        
        # Delete child table first (JournalEntryLine)
        # Fields are already dropped in the Python function above
        migrations.DeleteModel(
            name='JournalEntryLine',
        ),
        
        # Then delete parent table (JournalEntry)
        migrations.DeleteModel(
            name='JournalEntry',
        ),
    ]
