# Generated by Django 5.2.8 on 2025-12-22 13:55

import django.db.models.deletion
from django.db import migrations, models


def create_table_if_not_exists(apps, schema_editor):
    """Create table only if it doesn't already exist"""
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_schema = DATABASE()
            AND table_name = 'accounts_defaultaccounthead'
            """
        )
        table_exists = cursor.fetchone()[0] > 0

        if not table_exists:
            # Table doesn't exist, create it using raw SQL
            cursor.execute(
                """
                CREATE TABLE `accounts_defaultaccounthead` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `transactionType` varchar(20) NOT NULL,
                    `description` longtext,
                    `isActive` tinyint(1) NOT NULL,
                    `createdAt` datetime(6) NOT NULL,
                    `updatedAt` datetime(6) NOT NULL,
                    `createdBy_id` bigint DEFAULT NULL,
                    `defaultAccount_id` bigint NOT NULL,
                    `updatedBy_id` bigint DEFAULT NULL,
                    PRIMARY KEY (`id`),
                    UNIQUE KEY `transactionType` (`transactionType`),
                    KEY `accounts_de_transac_567dd9_idx` (`transactionType`),
                    KEY `accounts_de_isActiv_79ae49_idx` (`isActive`),
                    KEY `accounts_defaultac_createdBy_id_76b5bdaa_fk_user_memb` (`createdBy_id`),
                    KEY `accounts_defaultac_defaultAccount_id_8e5d4a9f_fk_accounts_` (`defaultAccount_id`),
                    KEY `accounts_defaultac_updatedBy_id_e0c7e8e9_fk_user_memb` (`updatedBy_id`),
                    CONSTRAINT `accounts_defaultac_createdBy_id_76b5bdaa_fk_user_memb` FOREIGN KEY (`createdBy_id`) REFERENCES `user_member` (`id`),
                    CONSTRAINT `accounts_defaultac_defaultAccount_id_8e5d4a9f_fk_accounts_` FOREIGN KEY (`defaultAccount_id`) REFERENCES `accounts_account` (`id`),
                    CONSTRAINT `accounts_defaultac_updatedBy_id_e0c7e8e9_fk_user_memb` FOREIGN KEY (`updatedBy_id`) REFERENCES `user_member` (`id`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
                """
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_journalentryline_journalentry_and_more'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='DefaultAccountHead',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('transactionType', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('cash', 'Cash'), ('bank', 'Bank'), ('mfs', 'Mobile Financial Service (MFS)')], help_text='Type of financial transaction', max_length=20, unique=True)),
                        ('description', models.TextField(blank=True, help_text='Description for this default account mapping', null=True)),
                        ('isActive', models.BooleanField(default=True)),
                        ('createdAt', models.DateTimeField(auto_now_add=True)),
                        ('updatedAt', models.DateTimeField(auto_now=True)),
                        ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_default_account_heads', to='user.member')),
                        ('defaultAccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_account_heads', to='accounts.account')),
                        ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_default_account_heads', to='user.member')),
                    ],
                    options={
                        'verbose_name': 'Default Account Head',
                        'verbose_name_plural': 'Default Account Heads',
                        'ordering': ['transactionType'],
                        'indexes': [models.Index(fields=['transactionType'], name='accounts_de_transac_567dd9_idx'), models.Index(fields=['isActive'], name='accounts_de_isActiv_79ae49_idx')],
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    code=create_table_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
    ]
