# Generated by Django 5.2.8 on 2025-12-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_make_default_account_heads_dynamic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherentry',
            name='narration',
            field=models.TextField(blank=True, help_text='Description of the transaction', null=True),
        ),
    ]
