# Generated by Django 5.2.7 on 2026-01-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_voucherentry_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='openingBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='openingBalanceDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
