# Generated by Django 5.2.7 on 2026-01-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_account_openingbalance_account_openingbalancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultaccounthead',
            name='defaultEntryType',
            field=models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', help_text='Default entry type (Debit or Credit) for this transaction type', max_length=10),
        ),
    ]
