# Generated by Django 5.2.7 on 2026-01-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_defaultaccounthead_defaultentrytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultaccounthead',
            name='defaultEntryType',
            field=models.CharField(blank=True, choices=[('debit', 'Debit'), ('credit', 'Credit')], help_text='Default entry type (Debit or Credit) for this transaction type', max_length=10, null=True),
        ),
    ]
