# Generated by Django 5.2.7 on 2026-01-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_fix_opening_balance_columns'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='account',
                    name='openingCredit',
                    field=models.DecimalField(decimal_places=2, default=0, help_text='Opening credit amount', max_digits=15),
                ),
                migrations.AddField(
                    model_name='account',
                    name='openingDebit',
                    field=models.DecimalField(decimal_places=2, default=0, help_text='Opening debit amount', max_digits=15),
                ),
            ],
            database_operations=[],
        ),
    ]
