# Generated by Django 5.2.7 on 2026-01-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account_openingcredit_account_openingdebit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchertype',
            name='name',
            field=models.CharField(choices=[('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('journal', 'Journal Voucher'), ('contra', 'Contra Voucher')], max_length=50, unique=True),
        ),
    ]
