# Generated by Django 5.2.7 on 2026-01-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_vouchertype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchertype',
            name='name',
            field=models.CharField(choices=[('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('journal', 'Journal Voucher'), ('contra', 'Contra Voucher'), ('ServiceFeeBill', 'Service Fee Bill'), ('ServiceFeePayment', 'Service Fee Payment'), ('AdvancePayment', 'Advance Payment')], max_length=50, unique=True),
        ),
    ]
