# Generated by Django 5.2.7 on 2026-01-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_fix_account_field_defaults'),
        ('accounts', '0020_alter_vouchertype_name'),
    ]

    operations = [
    ]
