# Generated by Django 5.2.8 on 2026-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_merge_20260127_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchertype',
            name='name',
            field=models.CharField(choices=[('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('journal', 'Journal Voucher'), ('contra', 'Contra Voucher'), ('ServiceFeeBill', 'Service Fee Bill'), ('ServiceFeePayment', 'Service Fee Payment'), ('AdvancePayment', 'Advance Payment'), ('ServiceFeeAdjustment', 'Service Fee Adjustment')], max_length=50, unique=True),
        ),
    ]
