# Generated by Django 5.2.8 on 2026-02-08 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_vouchertype_name'),
        ('towers', '0025_floor_towers_floo_tower_i_35871b_idx_and_more'),
        ('user', '0004_create_django_cache_table'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='voucherentry',
                    name='account_holder_id',
                    field=models.PositiveBigIntegerField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='voucherentry',
                    name='account_holder_type',
                    field=models.CharField(blank=True, choices=[('resident', 'Resident'), ('owner', 'Owner')], max_length=20, null=True),
                ),
                migrations.AddField(
                    model_name='voucherentry',
                    name='unit',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_entries', to='towers.unit'),
                ),
                migrations.AddIndex(
                    model_name='voucherentry',
                    index=models.Index(fields=['unit'], name='accounts_vo_unit_id_d83f42_idx'),
                ),
                migrations.AddIndex(
                    model_name='voucherentry',
                    index=models.Index(fields=['account_holder_type', 'account_holder_id'], name='accounts_vo_account_534eab_idx'),
                ),
            ],
            database_operations=[],
        ),
        migrations.AddField(
            model_name='voucherentrydetails',
            name='account_holder_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherentrydetails',
            name='account_holder_type',
            field=models.CharField(blank=True, choices=[('resident', 'Resident'), ('owner', 'Owner')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voucherentrydetails',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_detail_lines', to='towers.unit'),
        ),
        migrations.AddIndex(
            model_name='voucherentrydetails',
            index=models.Index(fields=['unit'], name='accounts_vo_unit_id_e0b38c_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentrydetails',
            index=models.Index(fields=['account_holder_type', 'account_holder_id'], name='accounts_vo_account_3c9ff1_idx'),
        ),
    ]
