# Generated by Django 5.2.8 on 2026-03-04 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_account_is_group'),
        ('user', '0004_create_django_cache_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(choices=[('trial_balance', 'Trial Balance'), ('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('cash_flow', 'Cash Flow Statement')], help_text='The report module this section belongs to', max_length=50)),
                ('sectionName', models.CharField(help_text='Name of the section (e.g., ASSETS, LIABILITIES)', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Sort order for the section within the report')),
                ('description', models.TextField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, help_text='Ledger accounts included in this section', related_name='report_sections', to='accounts.account')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_sections', to='user.member')),
                ('updatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_report_sections', to='user.member')),
            ],
            options={
                'verbose_name': 'Report Section',
                'verbose_name_plural': 'Report Sections',
                'ordering': ['moduleName', 'order'],
                'unique_together': {('moduleName', 'sectionName')},
            },
        ),
    ]
