# Generated by Django 5.2.8 on 2026-03-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_reportsection'),
        ('towers', '0025_floor_towers_floo_tower_i_35871b_idx_and_more'),
        ('user', '0004_create_django_cache_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsection',
            name='moduleName',
            field=models.CharField(choices=[('trial_balance', 'Trial Balance'), ('income_statement', 'Income Statement'), ('balance_sheet', 'Balance Sheet'), ('received_payment', 'Received & Payment'), ('cash_flow', 'Cash Flow Statement')], help_text='The report module this section belongs to', max_length=50),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parentAccount'], name='accounts_ac_parentA_17d67f_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['status', 'entryDate'], name='accounts_vo_status_0c0275_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentrydetails',
            index=models.Index(fields=['account', 'voucherEntry'], name='accounts_vo_account_dde956_idx'),
        ),
    ]
