# Generated by Django 5.2.8 on 2026-03-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_reportsection_modulename_and_more'),
        ('towers', '0025_floor_towers_floo_tower_i_35871b_idx_and_more'),
        ('user', '0004_create_django_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherentry',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Primary account associated with this voucher (e.g., Bank for payments)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='header_vouchers', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='voucherentrydetails',
            name='entryDate',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['account'], name='accounts_vo_account_6f46cd_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentry',
            index=models.Index(fields=['account', 'entryDate'], name='accounts_vo_account_8aba15_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentrydetails',
            index=models.Index(fields=['entryDate'], name='accounts_vo_entryDa_3b4f0a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherentrydetails',
            index=models.Index(fields=['account', 'entryDate'], name='accounts_vo_account_08e87a_idx'),
        ),
    ]
