# Generated by Django 5.2.8 on 2026-03-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_voucherentry_account_voucherentrydetails_entrydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vouchertype',
            name='name',
            field=models.CharField(choices=[('receipt', 'Receipt Voucher'), ('payment', 'Payment Voucher'), ('journal', 'Journal Voucher'), ('contra', 'Contra Voucher'), ('ServiceFeeBill', 'Service Fee Bill'), ('ServiceFeePayment', 'Service Fee Payment'), ('AdvancePayment', 'Advance Payment'), ('ServiceFeeAdjustment', 'Service Fee Adjustment'), ('ClosingBalance', 'Closing Balance')], max_length=50, unique=True),
        ),
    ]
