# Generated by Django 5.2.7 on 2025-12-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billcategory',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of this bill category'),
        ),
    ]
