# Generated by Django 5.2.7 on 2026-01-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account_openingcredit_account_openingdebit'),
        ('bill_categories', '0002_alter_billcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='billcategory',
            name='default_account_head',
            field=models.ForeignKey(blank=True, help_text="Default accounting head for this category's revenue", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_categories', to='accounts.defaultaccounthead'),
        ),
    ]
