# Generated by Django 5.2.8 on 2025-12-22 10:15

import django.db.models.deletion
from django.db import migrations, models


def safe_rename_indexes(apps, schema_editor):
    """
    Safely rename indexes, handling cases where they might not exist.
    This is needed because the old notification_type index was removed
    when the field was changed in migration 0002.
    Also checks if tables exist before attempting any index operations.
    """
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # First check if tables exist
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        notification_table_exists = cursor.fetchone()[0] > 0
        
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notificationtype'
        """)
        notificationtype_table_exists = cursor.fetchone()[0] > 0
        
        # Only proceed with notification table indexes if table exists
        if notification_table_exists:
            # Check and rename indexes for notification table
            # Check if old notification_type index exists and rename it
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_notific_f2898f_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_notific_f2898f_idx TO notificatio_notific_d6e074_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notification' 
                    AND index_name = 'notificatio_notific_d6e074_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_notific_d6e074_idx ON notifications_notification(notification_type_id)")
            
            # Check and rename entity indexes
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__idx TO notificatio_entity__950da6_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__idx2'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__idx2 TO notificatio_entity__08aa77_idx")
        
        # Only proceed with notificationtype table indexes if table exists
        if notificationtype_table_exists:
            # Check and rename indexes for notificationtype table
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_code_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_code_idx TO notificatio_code_64d00e_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_entity__idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_entity__idx TO notificatio_entity__e6db54_idx")


def reverse_rename_indexes(apps, schema_editor):
    """
    Reverse the index renames (for rollback purposes)
    Also checks if tables exist before attempting any index operations.
    """
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # First check if tables exist
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        notification_table_exists = cursor.fetchone()[0] > 0
        
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notificationtype'
        """)
        notificationtype_table_exists = cursor.fetchone()[0] > 0
        
        # Only proceed with notification table indexes if table exists
        if notification_table_exists:
            # Reverse notification indexes
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_notific_d6e074_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_notific_d6e074_idx TO notificatio_notific_f2898f_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__950da6_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__950da6_idx TO notificatio_entity__idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__08aa77_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__08aa77_idx TO notificatio_entity__idx2")
        
        # Only proceed with notificationtype table indexes if table exists
        if notificationtype_table_exists:
            # Reverse notificationtype indexes
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_code_64d00e_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_code_64d00e_idx TO notificatio_code_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_entity__e6db54_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_entity__e6db54_idx TO notificatio_entity__idx")


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_dynamic_notification_system'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RunPython(safe_rename_indexes, reverse_rename_indexes),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the notification has been read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(help_text='Notification message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='The member who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user.member'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Notification title', max_length=255),
        ),
    ]
