# Generated by Django 5.2.7 on 2025-12-22 12:14

from django.db import migrations, connection


def rename_indexes_if_needed(apps, schema_editor):
    """Rename indexes only if the old names exist"""
    with connection.cursor() as cursor:
        # Get existing indexes for notifications_notification
        cursor.execute("""
            SELECT DISTINCT index_name
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
            AND table_name = 'notifications_notification'
        """)
        notification_indexes = {row[0] for row in cursor.fetchall()}
        
        # Rename notification indexes if old names exist
        index_renames_notification = [
            ('notificatio_notific_f2898f_idx', 'notificatio_notific_d6e074_idx'),
            ('notificatio_entity__idx', 'notificatio_entity__950da6_idx'),
            ('notificatio_entity__idx2', 'notificatio_entity__08aa77_idx'),
        ]
        
        for old_name, new_name in index_renames_notification:
            if old_name in notification_indexes and new_name not in notification_indexes:
                cursor.execute(f"ALTER TABLE notifications_notification RENAME INDEX `{old_name}` TO `{new_name}`")
        
        # Get existing indexes for notifications_notificationtype
        cursor.execute("""
            SELECT DISTINCT index_name
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
            AND table_name = 'notifications_notificationtype'
        """)
        type_indexes = {row[0] for row in cursor.fetchall()}
        
        # Rename notificationtype indexes if old names exist
        index_renames_type = [
            ('notificatio_code_idx', 'notificatio_code_64d00e_idx'),
            ('notificatio_entity__idx', 'notificatio_entity__e6db54_idx'),
        ]
        
        for old_name, new_name in index_renames_type:
            if old_name in type_indexes and new_name not in type_indexes:
                cursor.execute(f"ALTER TABLE notifications_notificationtype RENAME INDEX `{old_name}` TO `{new_name}`")


def safe_rename_indexes_0004(apps, schema_editor):
    """
    Safely rename indexes, handling cases where they might not exist.
    This migration ensures indexes are renamed if they exist, or created if they don't.
    """
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check if notification table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        notification_table_exists = cursor.fetchone()[0] > 0
        
        # Check if notificationtype table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notificationtype'
        """)
        notificationtype_table_exists = cursor.fetchone()[0] > 0
        
        if notification_table_exists:
            # Rename notification_type index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_notific_f2898f_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_notific_f2898f_idx TO notificatio_notific_d6e074_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notification' 
                    AND index_name = 'notificatio_notific_d6e074_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_notific_d6e074_idx ON notifications_notification(notification_type_id)")
            
            # Rename entity_type, entity_id index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__idx TO notificatio_entity__950da6_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notification' 
                    AND index_name = 'notificatio_entity__950da6_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_entity__950da6_idx ON notifications_notification(entity_type, entity_id)")
            
            # Rename entity_type, entity_id, recipient index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__idx2'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__idx2 TO notificatio_entity__08aa77_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notification' 
                    AND index_name = 'notificatio_entity__08aa77_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_entity__08aa77_idx ON notifications_notification(entity_type, entity_id, recipient_id)")
        
        if notificationtype_table_exists:
            # Rename code index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_code_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_code_idx TO notificatio_code_64d00e_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notificationtype' 
                    AND index_name = 'notificatio_code_64d00e_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_code_64d00e_idx ON notifications_notificationtype(code)")
            
            # Rename entity_type, is_active index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_entity__idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_entity__idx TO notificatio_entity__e6db54_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notificationtype' 
                    AND index_name = 'notificatio_entity__e6db54_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_entity__e6db54_idx ON notifications_notificationtype(entity_type, is_active)")


def reverse_rename_indexes_0004(apps, schema_editor):
    """
    Reverse the index renames (for rollback purposes)
    """
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check if notification table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        notification_table_exists = cursor.fetchone()[0] > 0
        
        # Check if notificationtype table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notificationtype'
        """)
        notificationtype_table_exists = cursor.fetchone()[0] > 0
        
        if notification_table_exists:
            # Reverse notification indexes
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_notific_d6e074_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_notific_d6e074_idx TO notificatio_notific_f2898f_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__950da6_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__950da6_idx TO notificatio_entity__idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__08aa77_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__08aa77_idx TO notificatio_entity__idx2")
        
        if notificationtype_table_exists:
            # Reverse notificationtype indexes
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_code_64d00e_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_code_64d00e_idx TO notificatio_code_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_entity__e6db54_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_entity__e6db54_idx TO notificatio_entity__idx")


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.RunPython(safe_rename_indexes_0004, reverse_rename_indexes_0004),
    ]
