# Generated by Django 5.2.8 on 2025-12-22 12:46

from django.db import migrations, connection


def safe_rename_indexes_0005(apps, schema_editor):
    """
    Safely rename indexes, handling cases where they might not exist.
    This migration consolidates logic from original 0005 and 0006 to ensure
    all machines run the same operations regardless of auto-generation differences.
    """
    db_connection = schema_editor.connection
    
    with db_connection.cursor() as cursor:
        # Check if notification table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        notification_table_exists = cursor.fetchone()[0] > 0
        
        # Check if notificationtype table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notificationtype'
        """)
        notificationtype_table_exists = cursor.fetchone()[0] > 0
        
        if notification_table_exists:
            # Rename notification_type index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_notific_f2898f_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_notific_f2898f_idx TO notificatio_notific_d6e074_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notification' 
                    AND index_name = 'notificatio_notific_d6e074_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_notific_d6e074_idx ON notifications_notification(notification_type_id)")
            
            # Rename entity_type, entity_id index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__idx TO notificatio_entity__950da6_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notification' 
                    AND index_name = 'notificatio_entity__950da6_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_entity__950da6_idx ON notifications_notification(entity_type, entity_id)")
            
            # Rename entity_type, entity_id, recipient index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__idx2'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__idx2 TO notificatio_entity__08aa77_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notification' 
                    AND index_name = 'notificatio_entity__08aa77_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_entity__08aa77_idx ON notifications_notification(entity_type, entity_id, recipient_id)")
            
            # Handle recipient + created_at index (from consolidated 0006)
            cursor.execute("""
                SELECT DISTINCT index_name, GROUP_CONCAT(column_name ORDER BY seq_in_index)
                FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification'
                GROUP BY index_name
            """)
            existing_indexes = {row[0]: row[1] for row in cursor.fetchall()}
            
            recipient_created_idx_old = None
            for idx_name, columns in existing_indexes.items():
                if 'recipient_id,created_at' in columns and idx_name != 'notificatio_recipie_7c8f9a_idx':
                    recipient_created_idx_old = idx_name
                    break
            
            if recipient_created_idx_old:
                cursor.execute(f"ALTER TABLE notifications_notification RENAME INDEX `{recipient_created_idx_old}` TO notificatio_recipie_7c8f9a_idx")
            elif 'notificatio_recipie_7c8f9a_idx' not in existing_indexes:
                cursor.execute("CREATE INDEX notificatio_recipie_7c8f9a_idx ON notifications_notification(recipient_id, created_at DESC)")
            
            # Handle recipient + is_read index (from consolidated 0006)
            recipient_read_idx_old = None
            for idx_name, columns in existing_indexes.items():
                if 'recipient_id,is_read' in columns and idx_name != 'notificatio_recipie_a1b2c3_idx':
                    recipient_read_idx_old = idx_name
                    break
            
            if recipient_read_idx_old:
                cursor.execute(f"ALTER TABLE notifications_notification RENAME INDEX `{recipient_read_idx_old}` TO notificatio_recipie_a1b2c3_idx")
            elif 'notificatio_recipie_a1b2c3_idx' not in existing_indexes:
                cursor.execute("CREATE INDEX notificatio_recipie_a1b2c3_idx ON notifications_notification(recipient_id, is_read)")
        
        if notificationtype_table_exists:
            # Rename code index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_code_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_code_idx TO notificatio_code_64d00e_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notificationtype' 
                    AND index_name = 'notificatio_code_64d00e_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_code_64d00e_idx ON notifications_notificationtype(code)")
            
            # Rename entity_type, is_active index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_entity__idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_entity__idx TO notificatio_entity__e6db54_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notificationtype' 
                    AND index_name = 'notificatio_entity__e6db54_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_entity__e6db54_idx ON notifications_notificationtype(entity_type, is_active)")


def reverse_rename_indexes_0005(apps, schema_editor):
    """
    Reverse the index renames (for rollback purposes)
    """
    db_connection = schema_editor.connection
    
    with db_connection.cursor() as cursor:
        # Check if notification table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        notification_table_exists = cursor.fetchone()[0] > 0
        
        # Check if notificationtype table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notificationtype'
        """)
        notificationtype_table_exists = cursor.fetchone()[0] > 0
        
        if notification_table_exists:
            # Reverse notification indexes
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_notific_d6e074_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_notific_d6e074_idx TO notificatio_notific_f2898f_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__950da6_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__950da6_idx TO notificatio_entity__idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__08aa77_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__08aa77_idx TO notificatio_entity__idx2")
        
        if notificationtype_table_exists:
            # Reverse notificationtype indexes
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_code_64d00e_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_code_64d00e_idx TO notificatio_code_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_entity__e6db54_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_entity__e6db54_idx TO notificatio_entity__idx")


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_notificatio_notific_f2898f_idx_notificatio_notific_d6e074_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(safe_rename_indexes_0005, reverse_rename_indexes_0005),
    ]
