# Generated by Django 5.2.8 on 2025-12-22 14:00

from django.db import migrations


def safe_idempotent_migration(apps, schema_editor):
    """
    This is an idempotent migration that safely handles all index operations
    without errors, regardless of which machine or which previous migrations
    have been applied.
    
    This migration:
    1. Checks if indexes exist before trying to rename them
    2. Creates indexes if they don't exist
    3. Never fails even if operations are repeated
    """
    db_connection = schema_editor.connection
    
    with db_connection.cursor() as cursor:
        # Check if notification table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        notification_table_exists = cursor.fetchone()[0] > 0
        
        if notification_table_exists:
            # Get all existing indexes on notifications_notification
            cursor.execute("""
                SELECT DISTINCT index_name, GROUP_CONCAT(column_name ORDER BY seq_in_index)
                FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification'
                GROUP BY index_name
            """)
            existing_indexes = {row[0]: row[1] for row in cursor.fetchall()}
            
            # Define target indexes and their properties
            target_indexes = {
                'notificatio_notific_d6e074_idx': 'notification_type_id',
                'notificatio_entity__950da6_idx': 'entity_type,entity_id',
                'notificatio_entity__08aa77_idx': 'entity_type,entity_id,recipient_id',
                'notificatio_recipie_7c8f9a_idx': 'recipient_id,created_at',
                'notificatio_recipie_a1b2c3_idx': 'recipient_id,is_read',
            }
            
            # Ensure all target indexes exist
            for target_name, columns in target_indexes.items():
                if target_name in existing_indexes:
                    # Index already exists, skip
                    continue
                
                # Index doesn't exist, create it
                if target_name == 'notificatio_notific_d6e074_idx':
                    try:
                        cursor.execute("CREATE INDEX notificatio_notific_d6e074_idx ON notifications_notification(notification_type_id)")
                    except Exception:
                        pass  # Index might already exist, ignore error
                
                elif target_name == 'notificatio_entity__950da6_idx':
                    try:
                        cursor.execute("CREATE INDEX notificatio_entity__950da6_idx ON notifications_notification(entity_type, entity_id)")
                    except Exception:
                        pass
                
                elif target_name == 'notificatio_entity__08aa77_idx':
                    try:
                        cursor.execute("CREATE INDEX notificatio_entity__08aa77_idx ON notifications_notification(entity_type, entity_id, recipient_id)")
                    except Exception:
                        pass
                
                elif target_name == 'notificatio_recipie_7c8f9a_idx':
                    try:
                        cursor.execute("CREATE INDEX notificatio_recipie_7c8f9a_idx ON notifications_notification(recipient_id, created_at DESC)")
                    except Exception:
                        pass
                
                elif target_name == 'notificatio_recipie_a1b2c3_idx':
                    try:
                        cursor.execute("CREATE INDEX notificatio_recipie_a1b2c3_idx ON notifications_notification(recipient_id, is_read)")
                    except Exception:
                        pass


def reverse_safe_idempotent_migration(apps, schema_editor):
    """
    Reverse migration is a no-op since we can't safely determine which indexes
    were created by this migration vs. which were created by other means.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_rename_notificatio_notific_f2898f_idx_notificatio_notific_d6e074_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(safe_idempotent_migration, reverse_safe_idempotent_migration),
    ]
