# Generated by Django 5.2.7 on 2025-12-23 10:49
# Modified to safely handle cases where indexes may already have been renamed or created

from django.db import migrations, connection


def safe_rename_indexes_0007(apps, schema_editor):
    """
    Safely rename indexes, checking if they exist before attempting to rename.
    This handles cases where migration 0006 may have already created indexes
    with the new names, or where previous migrations may have already renamed them.
    """
    db_connection = schema_editor.connection
    
    with db_connection.cursor() as cursor:
        # Check if notification table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        notification_table_exists = cursor.fetchone()[0] > 0
        
        # Check if notificationtype table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notificationtype'
        """)
        notificationtype_table_exists = cursor.fetchone()[0] > 0
        
        if notification_table_exists:
            # Rename recipient + created_at index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_recipie_a972ce_idx'
            """)
            old_index_exists = cursor.fetchone()[0] > 0
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_recipie_7c8f9a_idx'
            """)
            new_index_exists = cursor.fetchone()[0] > 0
            
            if old_index_exists and new_index_exists:
                # Both exist - drop new one and rename old one
                cursor.execute("ALTER TABLE notifications_notification DROP INDEX notificatio_recipie_7c8f9a_idx")
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_recipie_a972ce_idx TO notificatio_recipie_7c8f9a_idx")
            elif old_index_exists:
                # Only old exists - rename it
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_recipie_a972ce_idx TO notificatio_recipie_7c8f9a_idx")
            elif not new_index_exists:
                # Neither exists - create the new one
                cursor.execute("CREATE INDEX notificatio_recipie_7c8f9a_idx ON notifications_notification(recipient_id, created_at DESC)")
            
            # Rename recipient + is_read index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_recipie_4e3567_idx'
            """)
            old_index_exists = cursor.fetchone()[0] > 0
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_recipie_a1b2c3_idx'
            """)
            new_index_exists = cursor.fetchone()[0] > 0
            
            if old_index_exists and new_index_exists:
                # Both exist - drop new one and rename old one
                cursor.execute("ALTER TABLE notifications_notification DROP INDEX notificatio_recipie_a1b2c3_idx")
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_recipie_4e3567_idx TO notificatio_recipie_a1b2c3_idx")
            elif old_index_exists:
                # Only old exists - rename it
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_recipie_4e3567_idx TO notificatio_recipie_a1b2c3_idx")
            elif not new_index_exists:
                # Neither exists - create the new one
                cursor.execute("CREATE INDEX notificatio_recipie_a1b2c3_idx ON notifications_notification(recipient_id, is_read)")
            
            # Rename notification_type index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_notific_f2898f_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_notific_f2898f_idx TO notificatio_notific_d6e074_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notification' 
                    AND index_name = 'notificatio_notific_d6e074_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_notific_d6e074_idx ON notifications_notification(notification_type_id)")
            
            # Rename entity_type, entity_id index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__idx TO notificatio_entity__950da6_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notification' 
                    AND index_name = 'notificatio_entity__950da6_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_entity__950da6_idx ON notifications_notification(entity_type, entity_id)")
            
            # Rename entity_type, entity_id, recipient index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__idx2'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__idx2 TO notificatio_entity__08aa77_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notification' 
                    AND index_name = 'notificatio_entity__08aa77_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_entity__08aa77_idx ON notifications_notification(entity_type, entity_id, recipient_id)")
        
        if notificationtype_table_exists:
            # Rename code index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_code_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_code_idx TO notificatio_code_64d00e_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notificationtype' 
                    AND index_name = 'notificatio_code_64d00e_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_code_64d00e_idx ON notifications_notificationtype(code)")
            
            # Rename entity_type, is_active index
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_entity__idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_entity__idx TO notificatio_entity__e6db54_idx")
            else:
                # Check if new index already exists
                cursor.execute("""
                    SELECT COUNT(*) FROM information_schema.statistics 
                    WHERE table_schema = DATABASE() 
                    AND table_name = 'notifications_notificationtype' 
                    AND index_name = 'notificatio_entity__e6db54_idx'
                """)
                if cursor.fetchone()[0] == 0:
                    # Create the index if it doesn't exist
                    cursor.execute("CREATE INDEX notificatio_entity__e6db54_idx ON notifications_notificationtype(entity_type, is_active)")


def reverse_rename_indexes_0007(apps, schema_editor):
    """
    Reverse the index renames (for rollback purposes)
    """
    db_connection = schema_editor.connection
    
    with db_connection.cursor() as cursor:
        # Check if notification table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        notification_table_exists = cursor.fetchone()[0] > 0
        
        # Check if notificationtype table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notificationtype'
        """)
        notificationtype_table_exists = cursor.fetchone()[0] > 0
        
        if notification_table_exists:
            # Reverse notification indexes
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_recipie_7c8f9a_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_recipie_7c8f9a_idx TO notificatio_recipie_a972ce_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_recipie_a1b2c3_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_recipie_a1b2c3_idx TO notificatio_recipie_4e3567_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_notific_d6e074_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_notific_d6e074_idx TO notificatio_notific_f2898f_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__950da6_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__950da6_idx TO notificatio_entity__idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notification' 
                AND index_name = 'notificatio_entity__08aa77_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notification RENAME INDEX notificatio_entity__08aa77_idx TO notificatio_entity__idx2")
        
        if notificationtype_table_exists:
            # Reverse notificationtype indexes
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_code_64d00e_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_code_64d00e_idx TO notificatio_code_idx")
            
            cursor.execute("""
                SELECT COUNT(*) FROM information_schema.statistics 
                WHERE table_schema = DATABASE() 
                AND table_name = 'notifications_notificationtype' 
                AND index_name = 'notificatio_entity__e6db54_idx'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("ALTER TABLE notifications_notificationtype RENAME INDEX notificatio_entity__e6db54_idx TO notificatio_entity__idx")


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_safe_idempotent_migration"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_rename_indexes_0007, reverse_rename_indexes_0007),
            ],
            state_operations=[
                # Update Django's migration state to reflect the index renames
                migrations.RenameIndex(
                    model_name="notification",
                    new_name="notificatio_recipie_7c8f9a_idx",
                    old_name="notificatio_recipie_a972ce_idx",
                ),
                migrations.RenameIndex(
                    model_name="notification",
                    new_name="notificatio_recipie_a1b2c3_idx",
                    old_name="notificatio_recipie_4e3567_idx",
                ),
                migrations.RenameIndex(
                    model_name="notification",
                    new_name="notificatio_notific_d6e074_idx",
                    old_name="notificatio_notific_f2898f_idx",
                ),
                migrations.RenameIndex(
                    model_name="notification",
                    new_name="notificatio_entity__950da6_idx",
                    old_name="notificatio_entity__idx",
                ),
                migrations.RenameIndex(
                    model_name="notification",
                    new_name="notificatio_entity__08aa77_idx",
                    old_name="notificatio_entity__idx2",
                ),
                migrations.RenameIndex(
                    model_name="notificationtype",
                    new_name="notificatio_code_64d00e_idx",
                    old_name="notificatio_code_idx",
                ),
                migrations.RenameIndex(
                    model_name="notificationtype",
                    new_name="notificatio_entity__e6db54_idx",
                    old_name="notificatio_entity__idx",
                ),
            ],
        ),
    ]
