# Generated by Django 5.2.7 on 2025-12-23 11:20
# Modified to be a no-op migration that only updates Django's migration state
# The indexes were already renamed in migration 0007, so we just need to update the state

from django.db import migrations, connection


def safe_rename_indexes_state_only(apps, schema_editor):
    """
    This is a no-op function for database operations.
    The indexes were already renamed in migration 0007.
    We only need to update Django's migration state.
    """
    # Verify indexes exist with new names (they should, from migration 0007)
    with connection.cursor() as cursor:
        # Check if notification table exists
        cursor.execute("""
            SELECT COUNT(*) FROM information_schema.tables 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        if cursor.fetchone()[0] == 0:
            return
        
        # Get all existing indexes to verify they have the correct names
        cursor.execute("""
            SELECT DISTINCT index_name
            FROM information_schema.statistics 
            WHERE table_schema = DATABASE() 
            AND table_name = 'notifications_notification'
        """)
        existing_indexes = {row[0] for row in cursor.fetchall()}
        
        # Expected new index names
        expected_indexes = {
            'notificatio_recipie_7c8f9a_idx',
            'notificatio_recipie_a1b2c3_idx',
            'notificatio_notific_d6e074_idx',
            'notificatio_entity__950da6_idx',
            'notificatio_entity__08aa77_idx',
        }
        
        # If any expected indexes are missing, create them (shouldn't happen, but be safe)
        missing_indexes = expected_indexes - existing_indexes
        if missing_indexes:
            # This shouldn't happen, but if it does, we'll handle it
            # The indexes should have been created/renamed in migration 0007
            pass


def reverse_safe_rename_indexes_state_only(apps, schema_editor):
    """Reverse is a no-op since we're just updating state."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0007_rename_notificatio_recipie_a972ce_idx_notificatio_recipie_7c8f9a_idx_and_more",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    safe_rename_indexes_state_only,
                    reverse_safe_rename_indexes_state_only
                ),
            ],
            state_operations=[
                # Update Django's migration state to reflect the new index names
                # The database already has these names from migration 0007
                migrations.RenameIndex(
                    model_name="notification",
                    new_name="notificatio_recipie_7c8f9a_idx",
                    old_name="notificatio_recipie_a972ce_idx",
                ),
                migrations.RenameIndex(
                    model_name="notification",
                    new_name="notificatio_recipie_a1b2c3_idx",
                    old_name="notificatio_recipie_4e3567_idx",
                ),
                migrations.RenameIndex(
                    model_name="notification",
                    new_name="notificatio_notific_d6e074_idx",
                    old_name="notificatio_notific_f2898f_idx",
                ),
                migrations.RenameIndex(
                    model_name="notification",
                    new_name="notificatio_entity__950da6_idx",
                    old_name="notificatio_entity__idx",
                ),
                migrations.RenameIndex(
                    model_name="notification",
                    new_name="notificatio_entity__08aa77_idx",
                    old_name="notificatio_entity__idx2",
                ),
                migrations.RenameIndex(
                    model_name="notificationtype",
                    new_name="notificatio_code_64d00e_idx",
                    old_name="notificatio_code_idx",
                ),
                migrations.RenameIndex(
                    model_name="notificationtype",
                    new_name="notificatio_entity__e6db54_idx",
                    old_name="notificatio_entity__idx",
                ),
            ],
        ),
    ]
