# Generated by Django 5.2.7 on 2026-01-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_rename_notificatio_recipie_a972ce_idx_notificatio_recipie_7c8f9a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='entity_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('bulletin', 'Bulletin'), ('member', 'Member'), ('notice', 'Notice'), ('payment', 'Payment'), ('service_fee', 'Service Fee'), ('document', 'Document'), ('role', 'Role'), ('group', 'Group'), ('other', 'Other')], help_text='Type of entity this notification relates to', max_length=50),
        ),
    ]
