# Generated by Django 5.2.7 on 2026-01-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notificationtype_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='entity_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('bulletin', 'Bulletin'), ('member', 'Member'), ('notice', 'Notice'), ('payment', 'Payment'), ('service_fee', 'Service Fee'), ('document', 'Document'), ('role', 'Role'), ('group', 'Group'), ('unit', 'Unit'), ('resident', 'Resident'), ('unit_staff', 'Unit Staff'), ('other', 'Other')], help_text='Type of entity this notification relates to', max_length=50),
        ),
    ]
