# Generated by Django 5.2.3 on 2026-01-22 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_alter_notificationtype_entity_type'),
        ('user', '0003_member_terms_accepted_member_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_token', models.CharField(help_text='Expo push notification token', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], help_text='Type of device', max_length=20)),
                ('device_id', models.CharField(blank=True, help_text='Device identifier/model name', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this device token is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(help_text='The member who owns this device', on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='user.member')),
            ],
            options={
                'verbose_name': 'Device Token',
                'verbose_name_plural': 'Device Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['member', 'is_active'], name='notificatio_member__a7f621_idx'), models.Index(fields=['push_token'], name='notificatio_push_to_bb7c88_idx')],
                'unique_together': {('member', 'push_token')},
            },
        ),
    ]

