# Generated by Django 5.2.3 on 2026-01-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_alter_notification_priority'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_priorit_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='push_token',
            field=models.CharField(help_text='Expo push notification token', max_length=255),
        ),
    ]
