# Generated by Django 5.2.7 on 2026-01-27 16:28

from django.db import migrations, models


def check_and_add_token_type(apps, schema_editor):
    """
    Add token_type field only if it doesn't exist
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'notifications_devicetoken' 
            AND COLUMN_NAME = 'token_type'
        """)
        column_exists = cursor.fetchone()[0] > 0
        
        if not column_exists:
            # Add the column
            cursor.execute("""
                ALTER TABLE notifications_devicetoken 
                ADD COLUMN token_type VARCHAR(10) DEFAULT 'expo' 
                NOT NULL
            """)
            print("✅ Added token_type column")
        else:
            print("ℹ️ token_type column already exists, skipping")


def check_and_add_index(apps, schema_editor):
    """
    Add index only if it doesn't exist
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if index exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'notifications_devicetoken' 
            AND INDEX_NAME = 'notificatio_token_t_085be6_idx'
        """)
        index_exists = cursor.fetchone()[0] > 0
        
        if not index_exists:
            cursor.execute("""
                CREATE INDEX notificatio_token_t_085be6_idx 
                ON notifications_devicetoken (token_type, is_active)
            """)
            print("✅ Added token_type index")
        else:
            print("ℹ️ token_type index already exists, skipping")


def reverse_add_token_type(apps, schema_editor):
    """
    Remove token_type field and index
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Remove index if exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.STATISTICS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'notifications_devicetoken' 
            AND INDEX_NAME = 'notificatio_token_t_085be6_idx'
        """)
        index_exists = cursor.fetchone()[0] > 0
        
        if index_exists:
            cursor.execute("""
                ALTER TABLE notifications_devicetoken 
                DROP INDEX notificatio_token_t_085be6_idx
            """)
            print("✅ Removed token_type index")
        
        # Remove column if exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'notifications_devicetoken' 
            AND COLUMN_NAME = 'token_type'
        """)
        column_exists = cursor.fetchone()[0] > 0
        
        if column_exists:
            cursor.execute("""
                ALTER TABLE notifications_devicetoken 
                DROP COLUMN token_type
            """)
            print("✅ Removed token_type column")


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_remove_devicetoken_unique_constraint'),
        ('user', '0003_member_terms_accepted_member_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(check_and_add_token_type, reverse_add_token_type),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='devicetoken',
                    name='token_type',
                    field=models.CharField(choices=[('expo', 'Expo Push Token'), ('fcm', 'FCM Token')], default='expo', help_text='Type of push token (Expo or FCM)', max_length=10),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='push_token',
            field=models.CharField(help_text='Push notification token (Expo or FCM)', max_length=500),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(check_and_add_index, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddIndex(
                    model_name='devicetoken',
                    index=models.Index(fields=['token_type', 'is_active'], name='notificatio_token_t_085be6_idx'),
                ),
            ]
        ),
    ]
