# Generated by Django 5.2.8 on 2026-02-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_devicetoken_token_type_alter_devicetoken_push_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('web', 'Web Only'), ('mobile', 'Mobile Only'), ('both', 'Both Web and Mobile')], default='web', help_text='Channel where this notification should be displayed', max_length=10),
        ),
    ]
