# Generated by Django 5.2.7 on 2026-02-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0020_alter_notificationtype_entity_type'),
        ('notifications', '0020_remove_push_token_unique_index'),
    ]

    operations = [
    ]
