# Generated by Django 5.2.3 on 2025-08-28 15:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('towers', '0006_alter_owner_unique_together'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(help_text='Auto-populated creator name', max_length=255)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('BDT', 'BDT'), ('USD', 'USD'), ('EUR', 'EUR')], default='BDT', max_length=3)),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Weekly', 'Weekly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('due_day', models.IntegerField(help_text='Due day of the month (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('accepts_cash', models.BooleanField(default=False)),
                ('accepts_mfs', models.BooleanField(default=False)),
                ('accepts_bank', models.BooleanField(default=False)),
                ('reminder_before_days', models.IntegerField(blank=True, help_text='Send reminder X days before due date', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('reminder_after_days', models.IntegerField(blank=True, help_text='Send reminder X days after due date', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_fee_creator', to='user.member')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_service_fees', to='user.member')),
                ('towers', models.ManyToManyField(blank=True, related_name='service_fees', to='towers.tower')),
                ('units', models.ManyToManyField(blank=True, related_name='service_fees', to='towers.unit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_fee_updater', to='user.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeeBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('Prime Bank', 'Prime Bank'), ('DBBL', 'DBBL'), ('BRAC Bank', 'BRAC Bank'), ('City Bank', 'City Bank'), ('Dutch Bangla Bank', 'Dutch Bangla Bank'), ('Islami Bank', 'Islami Bank')], max_length=100)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_address', models.TextField()),
                ('account_holder_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=17)),
                ('routing_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='service_fee.servicefee')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeeMFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('bKash', 'bKash'), ('Nagad', 'Nagad'), ('Rocket', 'Rocket'), ('IKcash', 'IKcash')], max_length=20)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfs_accounts', to='service_fee.servicefee')),
            ],
            options={
                'unique_together': {('service_fee', 'provider')},
            },
        ),
    ]
