# Generated by Django 5.2.5 on 2025-08-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0002_alter_servicefee_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeebank',
            name='account_number',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='servicefeemfs',
            unique_together={('account_number',), ('service_fee', 'provider')},
        ),
    ]
