# Generated by Django 5.2.3 on 2025-08-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0003_alter_servicefeebank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeebank',
            name='account_number',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='servicefeebank',
            name='routing_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='servicefeemfs',
            name='account_number',
            field=models.CharField(max_length=25),
        ),
    ]
