# Generated by Django 5.2.5 on 2025-08-31 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0004_alter_servicefeebank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefee',
            name='reminder_after_days',
            field=models.IntegerField(default=3, help_text='Send reminder X days after due date', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicefee',
            name='reminder_before_days',
            field=models.IntegerField(default=7, help_text='Send reminder X days before due date', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
            preserve_default=False,
        ),
    ]
