# Generated by Django 5.2.5 on 2025-08-31 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0005_alter_servicefee_reminder_after_days_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicefeemfs',
            unique_together={('provider', 'account_number'), ('service_fee', 'provider')},
        ),
    ]
