# Generated by Django 5.2.3 on 2025-08-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0006_alter_servicefeemfs_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicefeemfs',
            unique_together={('service_fee', 'provider')},
        ),
        migrations.AlterField(
            model_name='servicefeebank',
            name='account_number',
            field=models.CharField(max_length=25),
        ),
    ]
