# Generated by Django 5.2.5 on 2025-09-11 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0007_alter_servicefeemfs_unique_together_and_more'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('activated', 'Activated'), ('deactivated', 'Deactivated'), ('deleted', 'Deleted')], max_length=20)),
                ('changed_by_name', models.CharField(help_text='Auto-populated changed by name', max_length=255)),
                ('field_changes', models.JSONField(default=list, help_text='List of field changes with old and new values')),
                ('reason', models.TextField(blank=True, help_text='Reason for the change (especially for cancellations)', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_changes', to='user.member')),
                ('service_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='service_fee.servicefee')),
            ],
            options={
                'verbose_name': 'Service Fee History',
                'verbose_name_plural': 'Service Fee Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
