# Generated by Django 5.2.5 on 2025-09-15 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0008_servicefeehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefee',
            name='reminder_after_days',
            field=models.IntegerField(help_text='Send reminder X days after due date', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='servicefee',
            name='reminder_before_days',
            field=models.IntegerField(help_text='Send reminder X days before due date', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
