# Generated by Django 5.2.5 on 2025-09-20 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0009_update_reminder_days_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefee',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
