# Generated by Django 5.2.7 on 2025-10-07 11:33

from django.db import migrations, models


def add_service_fee_date_if_not_exists(apps, schema_editor):
    """Add service_fee_date field if it doesn't exist"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_servicefee' 
            AND COLUMN_NAME = 'service_fee_date'
        """)
        exists = cursor.fetchone()[0]
        
        if not exists:
            # Add the column
            cursor.execute("""
                ALTER TABLE service_fee_servicefee 
                ADD COLUMN service_fee_date DATE NULL 
                COMMENT 'Service fee effective date'
            """)


def reverse_add_service_fee_date(apps, schema_editor):
    """Remove service_fee_date field"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if column exists before dropping
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_servicefee' 
            AND COLUMN_NAME = 'service_fee_date'
        """)
        exists = cursor.fetchone()[0]
        
        if exists:
            cursor.execute("""
                ALTER TABLE service_fee_servicefee 
                DROP COLUMN service_fee_date
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0013_allow_multiple_accounts_per_provider'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_service_fee_date_if_not_exists,
                    reverse_add_service_fee_date
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='servicefee',
                    name='service_fee_date',
                    field=models.DateField(blank=True, help_text='Service fee effective date', null=True),
                ),
            ],
        ),
    ]
