# Generated by Django 5.2.5 on 2025-10-07 13:12

import django.utils.timezone
from django.db import migrations, models


def alter_service_fee_date_if_exists(apps, schema_editor):
    """Alter service_fee_date field to add default if it exists"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_servicefee' 
            AND COLUMN_NAME = 'service_fee_date'
        """)
        exists = cursor.fetchone()[0]
        
        if exists:
            # Alter the column to add default value
            cursor.execute("""
                ALTER TABLE service_fee_servicefee 
                MODIFY COLUMN service_fee_date DATE NOT NULL 
                DEFAULT (CURRENT_DATE)
                COMMENT 'Service fee effective date'
            """)


def reverse_alter_service_fee_date(apps, schema_editor):
    """Reverse the alter by removing default constraint"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_servicefee' 
            AND COLUMN_NAME = 'service_fee_date'
        """)
        exists = cursor.fetchone()[0]
        
        if exists:
            cursor.execute("""
                ALTER TABLE service_fee_servicefee 
                MODIFY COLUMN service_fee_date DATE NULL 
                COMMENT 'Service fee effective date'
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0014_servicefee_service_fee_date'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    alter_service_fee_date_if_exists,
                    reverse_alter_service_fee_date
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='servicefee',
                    name='service_fee_date',
                    field=models.DateField(default=django.utils.timezone.now, help_text='Service fee effective date'),
                ),
            ],
        ),
    ]
