# Generated by Django 5.2.7 on 2025-11-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0015_alter_servicefee_service_fee_date'),
        ('towers', '0001_initial'),
    ]

    operations = [
        # Register the through model with Django (state only, columns already added manually)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ServiceFeeUnit',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('service_fee', models.ForeignKey(db_column='servicefee_id', on_delete=django.db.models.deletion.CASCADE, to='service_fee.servicefee')),
                        ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='towers.unit')),
                    ],
                    options={
                        'verbose_name': 'Service Fee Unit Assignment',
                        'verbose_name_plural': 'Service Fee Unit Assignments',
                        'db_table': 'service_fee_servicefee_units',
                        'unique_together': [('service_fee', 'unit')],
                    },
                ),
                migrations.AlterField(
                    model_name='servicefee',
                    name='units',
                    field=models.ManyToManyField(blank=True, related_name='service_fees', through='service_fee.ServiceFeeUnit', to='towers.unit'),
                ),
            ],
            database_operations=[],
        ),
    ]
