# Generated by Django 5.2.7 on 2025-12-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0018_servicefeetower_alter_servicefee_towers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceFeeTower',
        ),
    ]
