# Generated by Django 5.2.7 on 2025-12-30 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0020_add_late_penalty_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latepenaltytier',
            name='days_overdue',
            field=models.IntegerField(help_text='Number of days overdue for this penalty tier (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='latepenaltytier',
            name='penalty_percentage',
            field=models.DecimalField(decimal_places=2, help_text='Penalty percentage (>1 and <=100)', max_digits=5, validators=[django.core.validators.MinValueValidator(1.01), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
