# Generated by Django 5.2.7 on 2026-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0021_alter_latepenaltytier_days_overdue_and_more'),
        ('towers', '0024_alter_unitresidenthistory_entry_type'),
        ('user', '0003_member_terms_accepted_member_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicefee',
            index=models.Index(fields=['is_active'], name='service_fee_is_acti_19558f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefee',
            index=models.Index(fields=['service_fee_date'], name='service_fee_service_76f246_idx'),
        ),
    ]
