#!/bin/bash
# Quick command reference for PayStation testing

echo "PayStation Integration Test - Quick Commands"
echo "=============================================="
echo ""
echo "1. Run all tests with auto venv setup:"
echo "   ./run_paystation_tests.sh"
echo ""
echo "2. Run tests manually:"
echo "   source venv/bin/activate"
echo "   python test_paystation_integration.py"
echo ""
echo "3. Clean test data:"
echo "   python manage.py shell"
echo "   >>> from service_fee_management.models import ServiceFeePayment"
echo "   >>> ServiceFeePayment.objects.filter(service_period_month=2, service_period_year=2026).delete()"
echo ""
echo "4. Check PayStation credentials:"
echo "   python manage.py shell"
echo "   >>> from django.conf import settings"
echo "   >>> print(settings.PAYSTATION_MERCHANT_ID)"
echo "   >>> print(settings.PAYSTATION_IS_SANDBOX)"
echo ""
echo "5. Test single payment initialization:"
echo "   curl -X POST http://localhost:8000/api/service-fee-management/paystation/init/ \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"unit_id\":26,\"service_fee_id\":3,\"amount\":\"5000.00\",\"service_period_month\":3,\"service_period_year\":2026}'"
echo ""
