# Generated by Django 5.2.8 on 2025-11-18 00:03

import django.core.validators
from django.db import migrations, models


def upload_to_contact_photo(instance, filename):
    """Generate upload path for contact photos - kept for migration compatibility"""
    return f'contacts/{instance.id}_{instance.name}/{filename}'


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importantcontact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=upload_to_contact_photo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
