# Generated by Django 5.2.7 on 2025-12-03 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_migrate_to_org_member'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importantcontact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Important Contact', 'verbose_name_plural': 'Important Contacts'},
        ),
        migrations.AlterField(
            model_name='importantcontact',
            name='created_by',
            field=models.ForeignKey(help_text='Member who created this important contact entry', on_delete=django.db.models.deletion.DO_NOTHING, related_name='important_contacts_created', to='user.member'),
        ),
        migrations.AlterField(
            model_name='importantcontact',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Member who last updated this entry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='important_contacts_updated', to='user.member'),
        ),
    ]
