"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import pymysql

# Configure PyMySQL to work as MySQLdb
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (optional)
# Install python-dotenv: pip install python-dotenv
try:
    from dotenv import load_dotenv
    # Load .env file from backend directory
    env_path = BASE_DIR / '.env'
    if env_path.exists():
        load_dotenv(env_path)
        print(f"[OK] Loaded environment variables from {env_path}")
except ImportError:
    # python-dotenv not installed, using system environment variables only
    pass
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # DISABLED - Use SMTP instead (configured below)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1uv1c1!(922iv@glb0tj6^0n=%*$gbgqqhpab7jujpbc&%_hxb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['api.estatelink.cloud','dev-api.estatelink.cloud', '192.168.0.105','192.168.0.228','test-api.estatelink.cloud','demo-api.estatelink.cloud','localhost', '127.0.0.1', '192.168.0.109', '192.168.100.8', '192.168.0.221', '192.168.0.255', '192.168.0.104','192.168.0.110', '192.168.0.219', '192.168.0.185', '192.168.0.101', '10.0.2.2']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'user',
    'rest_framework_simplejwt.token_blacklist',
    'group_role',
    'audit_trail',
    'towers',
    'announcements',
    'bulletins',
    'noticeboard',
    'service_fee',
    'service_fee_management',
    'contacts',
    'company_settings',
    'bill_categories',
    'accounts',
    'notifications',
]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

from datetime import timedelta
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    # Token Lifetimes - Increased for better mobile app UX
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),  # Increased from 1 day to 7 days
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),  # Increased from 10 days to 30 days
    
    # Token Rotation - Keep enabled for security
    "ROTATE_REFRESH_TOKENS": True,
    
    # Blacklisting - DISABLED for mobile apps to prevent UX issues
    # Mobile apps store tokens securely in AsyncStorage, so blacklisting is not necessary
    # and can cause "Token is blacklisted" errors when users reopen the app after extended periods
    "BLACKLIST_AFTER_ROTATION": False,  # Changed from True to False
    
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(days=1),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "user.serializers.CustomTokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
     'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'estatelink',
        'USER': 'root',
        'PASSWORD': '12345678',
        'HOST': 'localhost',
        'PORT':'3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_ALL_TABLES', character_set_connection=utf8mb4, collation_connection=utf8mb4_unicode_ci",
            'charset': 'utf8mb4',
        },
    }
}

# Shared cache backend (OTP, rate limiting, etc.)
# Uses database cache so multiple workers / processes share the same data.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        # Database table name for cache data
        "LOCATION": "django_cache",
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

import os
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
# Increase upload limits to support 5MB total attachments per bulletin
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB to allow some headroom beyond our 5MB limit
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB for individual files
DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000  # Increased to handle large form submissions with many units/towers

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'estatelink.dtg@gmail.com'
EMAIL_HOST_PASSWORD = 'lfyv nars ktkv aczq'

# Login Link Configuration - Used in email notifications
LOGIN_LINK = 'https://control.estatelink.cloud/login'

# App Download Link Configuration - Used in email notifications for community members
APP_DOWNLOAD_LINK = 'https://play.google.com/apps/internaltest/4701408139020918392'
IOS_APP_DOWNLOAD_LINK = 'https://apps.apple.com/us/app/estatelink/id6476132800' # Placeholder for iOS

# ==================== PAYMENT GATEWAY CONFIGURATION ====================

# SSLCommerz Payment Gateway Configuration - COMMENTED OUT (replaced with PayStation)
# SSLCOMMERZ_STORE_ID = 'test68f4e592b3961'
# SSLCOMMERZ_STORE_PASSWORD = 'test68f4e592b3961@ssl'
# SSLCOMMERZ_IS_SANDBOX = True  # Set to False for production
# SSLCOMMERZ_SESSION_API = 'https://sandbox.sslcommerz.com/gwprocess/v4/api.php'
# SSLCOMMERZ_VALIDATION_API = 'https://sandbox.sslcommerz.com/validator/api/validationserverAPI.php'
# For production, use:
# SSLCOMMERZ_SESSION_API = 'https://securepay.sslcommerz.com/gwprocess/v4/api.php'
# SSLCOMMERZ_VALIDATION_API = 'https://securepay.sslcommerz.com/validator/api/validationserverAPI.php'

# PayStation Payment Gateway Configuration
# Set PAYSTATION_ENV in .env: "development" = sandbox, "production" = live
_PAYSTATION_ENV = os.environ.get('PAYSTATION_ENV', 'development').lower()
if _PAYSTATION_ENV in ('production', 'prod'):
    PAYSTATION_MERCHANT_ID = '2080-1768292806'
    PAYSTATION_PASSWORD = 'k&jW$56@#'
    PAYSTATION_IS_SANDBOX = False
    print('[PayStation] Using PRODUCTION (live) credentials')
else:
    PAYSTATION_MERCHANT_ID = '104-1653730183'
    PAYSTATION_PASSWORD = 'gamecoderstorepass'
    PAYSTATION_IS_SANDBOX = True
    print('[PayStation] Using DEVELOPMENT (sandbox) credentials')

# ==================== EXPO PUSH NOTIFICATIONS ====================
# Expo Access Token (optional but recommended for better reliability and higher rate limits)
# To get an access token:
# 1. Go to https://expo.dev/accounts/[your-account]/settings/access-tokens
# 2. Create a new access token with "Push notifications" scope
# 3. Add it here or set it as an environment variable: EXPO_ACCESS_TOKEN
# If not set, push notifications will still work but with lower rate limits
EXPO_ACCESS_TOKEN = os.environ.get('EXPO_ACCESS_TOKEN', None)

# ==================== FIREBASE CLOUD MESSAGING (FCM) ====================
# FCM service account for estatelink-9ac38 (Android + iOS)
# Set FCM_CREDENTIALS_PATH env var to override
FCM_CREDENTIALS_PATH = os.environ.get(
    'FCM_CREDENTIALS_PATH',
    os.path.join(BASE_DIR, 'estatelink-9ac38-firebase-adminsdk-fbsvc-c273bf8116.json')
)

# FCM Enabled - Set to True to enable FCM push notifications
# If False, only Expo Push API will be used
FCM_ENABLED = os.environ.get('FCM_ENABLED', 'True').lower() == 'true'

# ==================== SERVICE FEE GENERATION SCHEDULER ====================
# Background scheduler is configured in service_fee_management/apps.py
# Schedules are configured via Django Admin: Service Fee Generation Schedules
# The scheduler runs automatically when the server starts and checks every 60 seconds

