# Generated by Django 5.2.5 on 2025-08-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
