# Generated by Django 5.2.7 on 2025-12-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='terms_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
