# Generated by Django 5.2.8 on 2026-03-12 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_create_django_cache_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(help_text='The member who is blocked', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='user.member')),
                ('blocker', models.ForeignKey(help_text='The member who initiated the block', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to='user.member')),
            ],
            options={
                'verbose_name': 'Blocked User',
                'verbose_name_plural': 'Blocked Users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['blocker', 'blocked'], name='user_blocke_blocker_4a661e_idx'), models.Index(fields=['blocker'], name='user_blocke_blocker_852e04_idx')],
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
