# Generated by Django 5.0.4 on 2025-05-29 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='ownership_transfer_from',
        ),
    ]
