# Generated by Django 5.0.4 on 2025-05-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0003_remove_owner_ownership_transfer_from'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='ownership_transfer_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_ownerships', to='user.member'),
        ),
    ]
