# Generated by Django 5.0.4 on 2025-07-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0005_unit_status_color_alter_unit_unit_status'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together={('member', 'unit')},
        ),
    ]
