# Generated by Django 5.2.1 on 2025-08-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0008_vehicle_status_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=100),
        ),
    ]
