# Generated by Django 5.2.1 on 2025-08-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0009_alter_vehicle_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
