# Generated by Django 5.2.3 on 2025-09-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0010_alter_vehicle_brand_alter_vehicle_color_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
