# Generated by Django 5.2.7 on 2025-12-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0013_populate_ownership_history'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='unitownershiphistory',
            new_name='towers_unit_unit_id_c5deae_idx',
            old_name='towers_unit_unit_id_f0a7e3_idx',
        ),
        migrations.RenameIndex(
            model_name='unitownershiphistory',
            new_name='towers_unit_entry_t_042270_idx',
            old_name='towers_unit_entry_t_8f9a2c_idx',
        ),
    ]
