# Generated by Django - Add ownership_state_before and ownership_state_after fields
# 
# NOTE: This migration is for databases that already ran the old 0012-0014 migrations.
# If you're doing a fresh install with the updated 0012 migration (which includes these fields),
# you can skip this migration or Django will handle it automatically.

from django.db import migrations


def check_column_exists(schema_editor, table_name, column_name):
    """Check if a column exists in the given table"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = %s 
            AND COLUMN_NAME = %s
        """, [table_name, column_name])
        return cursor.fetchone()[0] > 0


def add_fields_if_not_exists(apps, schema_editor):
    """Add fields only if they don't already exist"""
    table_name = 'towers_unitownershiphistory'
    
    # Check and add ownership_state_before if it doesn't exist
    if not check_column_exists(schema_editor, table_name, 'ownership_state_before'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE `{}` 
                ADD COLUMN `ownership_state_before` JSON NOT NULL DEFAULT ('[]')
            """.format(table_name))
    
    # Check and add ownership_state_after if it doesn't exist
    if not check_column_exists(schema_editor, table_name, 'ownership_state_after'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                ALTER TABLE `{}` 
                ADD COLUMN `ownership_state_after` JSON NOT NULL DEFAULT ('[]')
            """.format(table_name))


def remove_fields_if_exists(apps, schema_editor):
    """Remove fields if they exist (for reverse migration)"""
    table_name = 'towers_unitownershiphistory'
    
    if check_column_exists(schema_editor, table_name, 'ownership_state_before'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("ALTER TABLE `{}` DROP COLUMN `ownership_state_before`".format(table_name))
    
    if check_column_exists(schema_editor, table_name, 'ownership_state_after'):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("ALTER TABLE `{}` DROP COLUMN `ownership_state_after`".format(table_name))


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0014_rename_towers_unit_unit_id_f0a7e3_idx_towers_unit_unit_id_c5deae_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            add_fields_if_not_exists,
            reverse_code=remove_fields_if_exists,
        ),
    ]

