# Generated by Django 5.2.7 on 2025-12-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("towers", "0016_unitstaffhistory"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="unitstaffhistory",
            new_name="towers_unit_unit_id_304000_idx",
            old_name="towers_unit_unit_id_staff_idx",
        ),
        migrations.RenameIndex(
            model_name="unitstaffhistory",
            new_name="towers_unit_entry_t_5b714d_idx",
            old_name="towers_unit_entry_type_staff_idx",
        ),
        migrations.RenameIndex(
            model_name="unitstaffhistory",
            new_name="towers_unit_staff_m_6e3368_idx",
            old_name="towers_unit_staff_member_idx",
        ),
    ]
