# Generated by Django 5.2.7 on 2025-12-18 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0017_rename_towers_unit_unit_id_staff_idx_towers_unit_unit_id_304000_idx_and_more'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitResidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('resident_assigned', 'Resident Assigned'), ('resident_removed', 'Resident Removed'), ('resident_info_updated', 'Resident Info Updated'), ('resident_status_changed', 'Resident Status Changed')], max_length=50)),
                ('entry_date', models.DateTimeField(help_text='The date/time this resident event occurred')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the event', null=True)),
                ('is_resident_or_tenant', models.BooleanField(blank=True, help_text='Resident status at the time of event (True=Resident, False=Tenant)', null=True)),
                ('resident_state_before', models.JSONField(default=list, help_text='Complete resident state before this event with all resident details')),
                ('resident_state_after', models.JSONField(default=list, help_text='Complete resident state after this event with all resident details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_resident_history', to='user.member')),
                ('resident_member', models.ForeignKey(blank=True, help_text='The resident member involved in this event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_history_entries', to='user.member')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_history', to='towers.unit')),
            ],
            options={
                'verbose_name': 'Unit Resident History',
                'verbose_name_plural': 'Unit Resident Histories',
                'ordering': ['-entry_date', '-created_at'],
                'indexes': [models.Index(fields=['unit', '-entry_date'], name='towers_unit_unit_id_14202b_idx'), models.Index(fields=['entry_type'], name='towers_unit_entry_t_e67347_idx'), models.Index(fields=['resident_member'], name='towers_unit_residen_191a8b_idx')],
            },
        ),
    ]
