# Generated by Django 5.2.7 on 2025-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0018_unitresidenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitresidenthistory',
            name='resident_contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unitresidenthistory',
            name='resident_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='unitresidenthistory',
            name='resident_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
