# Generated by Django 5.2.7 on 2025-12-18 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0019_unitresidenthistory_resident_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitownershiphistory',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date/time this ownership event occurred'),
        ),
        migrations.AlterField(
            model_name='unitresidenthistory',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date/time this resident event occurred'),
        ),
        migrations.AlterField(
            model_name='unitstaffhistory',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date/time this staff event occurred'),
        ),
    ]
