# Generated by Django 5.2.7 on 2025-12-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("towers", "0020_alter_unitownershiphistory_entry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitstaffhistory",
            name="staff_member_contact",
            field=models.CharField(
                blank=True,
                help_text="Staff member contact at the time of the event (preserved even if member is deleted)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unitstaffhistory",
            name="staff_member_email",
            field=models.EmailField(
                blank=True,
                help_text="Staff member email at the time of the event (preserved even if member is deleted)",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="unitstaffhistory",
            name="staff_member_name",
            field=models.CharField(
                blank=True,
                help_text="Staff member name at the time of the event (preserved even if member is deleted)",
                max_length=255,
                null=True,
            ),
        ),
    ]
