# Generated by Django 5.2.7 on 2025-12-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0022_owner_last_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitownershiphistory',
            name='entry_type',
            field=models.CharField(choices=[('initial_ownership', 'Initial Ownership'), ('initial_ownership_list', 'Initial Ownership List'), ('ownership_transfer', 'Ownership Transfer'), ('ownership_updated', 'Ownership Updated'), ('ownership_list_updated', 'Ownership List Updated'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed')], max_length=50),
        ),
    ]
