# Generated by Django 5.2.7 on 2025-12-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0023_alter_unitownershiphistory_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitresidenthistory',
            name='entry_type',
            field=models.CharField(choices=[('resident_assigned', 'Resident Assigned'), ('resident_removed', 'Resident Removed'), ('resident_info_updated', 'Resident Info Updated'), ('resident_status_changed', 'Resident Status Changed'), ('attachment_added', 'Attachment Added'), ('attachment_removed', 'Attachment Removed')], max_length=50),
        ),
    ]
