# Generated by Django 5.2.7 on 2026-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towers', '0024_alter_unitresidenthistory_entry_type'),
        ('user', '0003_member_terms_accepted_member_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='floor',
            index=models.Index(fields=['tower', 'floor_no'], name='towers_floo_tower_i_35871b_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['unit', 'member'], name='towers_owne_unit_id_1f766f_idx'),
        ),
        migrations.AddIndex(
            model_name='owner',
            index=models.Index(fields=['member'], name='towers_owne_member__6eb74b_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['unit', 'is_active'], name='towers_resi_unit_id_626844_idx'),
        ),
        migrations.AddIndex(
            model_name='resident',
            index=models.Index(fields=['member', 'is_active'], name='towers_resi_member__b243c6_idx'),
        ),
        migrations.AddIndex(
            model_name='tower',
            index=models.Index(fields=['tower_name'], name='towers_towe_tower_n_2d5fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['floor', 'unit_name'], name='towers_unit_floor_i_4470c3_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_status'], name='towers_unit_unit_st_dca39c_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['primary_email'], name='towers_unit_primary_f40d73_idx'),
        ),
    ]
