# Generated by Django 5.2.3 on 2025-12-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0003_alter_bulletinhistory_action'),
        ('group_role', '0005_add_additional_permissions'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['-is_pinned', '-created_at'], name='bulletins_b_is_pinn_0ac8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['status', '-created_at'], name='bulletins_b_status_11e63d_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['priority'], name='bulletins_b_priorit_f63ee8_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['creator'], name='bulletins_b_creator_0bc35c_idx'),
        ),
    ]
