# Generated by Django 5.2.7 on 2025-12-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0004_bulletin_bulletins_b_is_pinn_0ac8e2_idx_and_more'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or Advertising'), ('harassment', 'Harassment or Hate Speech'), ('pornographic', 'Pornographic or Explicit Content'), ('violence', 'Violence or Harmful Content'), ('illegal', 'Illegal Activity'), ('privacy', 'Privacy Violation'), ('false_info', 'False Information / Misinformation'), ('inappropriate', 'Inappropriate / Off-Topic'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Optional additional details about the report', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='bulletins.bulletin')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_reports', to='user.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bulletin', '-created_at'], name='bulletins_b_bulleti_81cc5e_idx'), models.Index(fields=['status', '-created_at'], name='bulletins_b_status_0626e0_idx'), models.Index(fields=['reported_by'], name='bulletins_b_reporte_c81f3c_idx')],
                'unique_together': {('bulletin', 'reported_by')},
            },
        ),
    ]
