# Generated by Django 5.2.7 on 2025-12-22 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0005_bulletinreport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bulletinreport',
            unique_together=set(),
        ),
    ]
