# Generated by Django 5.2.8 on 2026-02-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0006_remove_unique_constraint_from_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='label',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
