"""
Centralized permission ID constants for role-based access control.

These values must match the IDs inserted into the `group_role_permission`
table. Keep this list in sync with any data migrations or seed scripts that
populate permissions.
"""

PERMISSION_CREATE_MEMBER = 1
PERMISSION_EDIT_MEMBER = 2
PERMISSION_VIEW_MEMBER_LIST = 3
PERMISSION_CREATE_ROLE = 4
PERMISSION_EDIT_ROLE = 5
PERMISSION_VIEW_ROLE_LIST = 6
PERMISSION_CREATE_GROUP = 7
PERMISSION_EDIT_GROUP = 8
PERMISSION_VIEW_GROUP_LIST = 9
PERMISSION_CREATE_TOWER = 10
PERMISSION_EDIT_TOWER = 11
PERMISSION_VIEW_TOWER = 12
PERMISSION_VIEW_UNIT_DETAILS = 13
PERMISSION_EDIT_UNIT_DETAILS = 14
PERMISSION_VIEW_UNIT_OWNERSHIP = 15
PERMISSION_ADD_OWNERSHIP = 16
PERMISSION_CHANGE_OWNERSHIP = 17
PERMISSION_VIEW_UNIT_RESIDENT = 18
PERMISSION_ADD_RESIDENT = 19
PERMISSION_EDIT_RESIDENT_INFO = 20
PERMISSION_VIEW_UNIT_STAFF = 21
PERMISSION_ADD_UNIT_STAFF = 22
PERMISSION_EDIT_UNIT_STAFF = 23
PERMISSION_VIEW_COMMUNITY_MEMBER_LIST = 24

PERMISSION_ADD_ANNOUNCEMENTS = 25
PERMISSION_VIEW_ANNOUNCEMENTS = 26
PERMISSION_EDIT_ANNOUNCEMENTS = 27

PERMISSION_ADD_BULLETIN_BOARD = 28
PERMISSION_VIEW_BULLETIN_BOARD = 29
PERMISSION_EDIT_BULLETIN_BOARD = 30

PERMISSION_ADD_NOTICE_BOARD = 31
PERMISSION_VIEW_NOTICE_BOARD = 32
PERMISSION_EDIT_NOTICE_BOARD = 33

PERMISSION_VIEW_IMPORTANT_CONTACTS = 34
PERMISSION_VIEW_SERVICE_FEE_SETTINGS = 35
PERMISSION_ADD_IMPORTANT_CONTACTS = 36
PERMISSION_EDIT_IMPORTANT_CONTACTS = 37
PERMISSION_ADD_SERVICE_FEE_SETTINGS = 38
PERMISSION_EDIT_SERVICE_FEE_SETTINGS = 39

# Granular Service Fee page permissions (per-page)
# Note: Ensure these IDs are created in the database (see AutoPopulatePermissions)
PERMISSION_VIEW_SERVICE_FEE_OVERVIEW = 40
PERMISSION_VIEW_UNIT_PAYMENT_HISTORY = 41
PERMISSION_MANAGE_SCHEDULE_CONFIGURATION = 42
PERMISSION_MANAGE_REMINDERS = 43
PERMISSION_RECORD_PAYMENT = 44

# Additional Service Fee Management permissions
PERMISSION_GENERATE_SERVICE_FEES = 45
PERMISSION_DELETE_GENERATED_SERVICE_FEES = 46
PERMISSION_DELETE_RECORDED_PAYMENT = 47
PERMISSION_VIEW_REMINDERS = 48
PERMISSION_ADD_REMINDER = 49
PERMISSION_EDIT_REMINDER = 50
PERMISSION_DELETE_REMINDER = 51

# Additional Announcement permissions
PERMISSION_EXPIRE_ANNOUNCEMENTS = 54
PERMISSION_PIN_ANNOUNCEMENTS = 55

# Additional Bulletin Board permissions
PERMISSION_ARCHIVE_BULLETIN_BOARD = 56
PERMISSION_APPROVE_REJECT_BULLETIN_BOARD = 57

# Additional Notice Board permissions
PERMISSION_EXPIRE_NOTICE_BOARD = 58

# Company Settings permissions
PERMISSION_VIEW_COMPANY_SETTINGS = 59

# Bill Categories permissions
PERMISSION_VIEW_BILL_CATEGORIES = 60
PERMISSION_ADD_BILL_CATEGORIES = 61
PERMISSION_EDIT_BILL_CATEGORIES = 62

# Chart of Accounts permissions
PERMISSION_VIEW_CHART_OF_ACCOUNTS = 63
PERMISSION_ADD_CHART_OF_ACCOUNTS = 64
PERMISSION_EDIT_CHART_OF_ACCOUNTS = 65

# Billing Management permissions
PERMISSION_VIEW_BILLING_MANAGEMENT = 66

# Bill Uploads permissions
PERMISSION_BILL_UPLOADS = 69
PERMISSION_VIEW_UNIT_RECEIVABLES = 70
PERMISSION_VIEW_SERVICE_FEE_PAYMENTS = 71
PERMISSION_VIEW_PAYMENT_METHODS = 72
PERMISSION_ADD_PAYMENT_METHODS = 73
PERMISSION_EDIT_PAYMENT_METHODS = 74


PERMISSION_NAME_BY_ID = {
    PERMISSION_CREATE_MEMBER: "Create Member",
    PERMISSION_EDIT_MEMBER: "Edit Member",
    PERMISSION_VIEW_MEMBER_LIST: "View Member List",
    PERMISSION_CREATE_ROLE: "Create Role",
    PERMISSION_EDIT_ROLE: "Edit Role",
    PERMISSION_VIEW_ROLE_LIST: "View Role List",
    PERMISSION_CREATE_GROUP: "Create Group",
    PERMISSION_EDIT_GROUP: "Edit Group",
    PERMISSION_VIEW_GROUP_LIST: "View Group List",
    PERMISSION_CREATE_TOWER: "Create Tower",
    PERMISSION_EDIT_TOWER: "Edit Tower",
    PERMISSION_VIEW_TOWER: "View Tower",
    PERMISSION_VIEW_UNIT_DETAILS: "View Unit Details",
    PERMISSION_EDIT_UNIT_DETAILS: "Edit Unit Details",
    PERMISSION_VIEW_UNIT_OWNERSHIP: "View Unit Ownership",
    PERMISSION_ADD_OWNERSHIP: "Add Ownership",
    PERMISSION_CHANGE_OWNERSHIP: "Change Ownership",
    PERMISSION_VIEW_UNIT_RESIDENT: "View Unit Resident",
    PERMISSION_ADD_RESIDENT: "Add Resident",
    PERMISSION_EDIT_RESIDENT_INFO: "Edit Resident Info",
    PERMISSION_VIEW_UNIT_STAFF: "View Unit Staff",
    PERMISSION_ADD_UNIT_STAFF: "Add Unit Staff",
    PERMISSION_EDIT_UNIT_STAFF: "Edit Unit Staff",
    PERMISSION_VIEW_COMMUNITY_MEMBER_LIST: "View Community Member List",
    PERMISSION_ADD_ANNOUNCEMENTS: "Add Announcements",
    PERMISSION_VIEW_ANNOUNCEMENTS: "View Announcements",
    PERMISSION_EDIT_ANNOUNCEMENTS: "Edit Announcements",
    PERMISSION_ADD_BULLETIN_BOARD: "Add Bulletin Board",
    PERMISSION_VIEW_BULLETIN_BOARD: "View Bulletin Board",
    PERMISSION_EDIT_BULLETIN_BOARD: "Edit Bulletin Board",
    PERMISSION_ADD_NOTICE_BOARD: "Add Notice Board",
    PERMISSION_VIEW_NOTICE_BOARD: "View Notice Board",
    PERMISSION_EDIT_NOTICE_BOARD: "Edit Notice Board",
    PERMISSION_VIEW_IMPORTANT_CONTACTS: "View Important Contacts",
    PERMISSION_VIEW_SERVICE_FEE_SETTINGS: "View Service Fee Settings",
    PERMISSION_ADD_IMPORTANT_CONTACTS: "Add Important Contacts",
    PERMISSION_EDIT_IMPORTANT_CONTACTS: "Edit Important Contacts",
    PERMISSION_ADD_SERVICE_FEE_SETTINGS: "Add Service Fee Settings",
    PERMISSION_EDIT_SERVICE_FEE_SETTINGS: "Edit Service Fee Settings",
    PERMISSION_VIEW_SERVICE_FEE_OVERVIEW: "View Service Fee Overview",
    PERMISSION_VIEW_UNIT_PAYMENT_HISTORY: "View Unit Payment History",
    PERMISSION_MANAGE_SCHEDULE_CONFIGURATION: "Manage Schedule Configuration",
    PERMISSION_MANAGE_REMINDERS: "Manage Service Fee Reminders",
    PERMISSION_RECORD_PAYMENT: "Record Service Fee Payment",
    PERMISSION_GENERATE_SERVICE_FEES: "Generate Service Fees",
    PERMISSION_DELETE_GENERATED_SERVICE_FEES: "Delete Generated Service Fees",
    PERMISSION_DELETE_RECORDED_PAYMENT: "Delete Recorded Payment",
    PERMISSION_VIEW_REMINDERS: "View Reminders",
    PERMISSION_ADD_REMINDER: "Add Reminder",
    PERMISSION_EDIT_REMINDER: "Edit Reminder",
    PERMISSION_DELETE_REMINDER: "Delete Reminder",

    PERMISSION_EXPIRE_ANNOUNCEMENTS: "Expire Announcements",
    PERMISSION_PIN_ANNOUNCEMENTS: "Pin Announcements",
    PERMISSION_ARCHIVE_BULLETIN_BOARD: "Archive Bulletin Posts",
    PERMISSION_APPROVE_REJECT_BULLETIN_BOARD: "Approve/Reject Bulletin Posts",
    PERMISSION_EXPIRE_NOTICE_BOARD: "Expire Notices",
    PERMISSION_VIEW_COMPANY_SETTINGS: "Edit Company Settings",
    PERMISSION_VIEW_BILL_CATEGORIES: "View Bill Categories",
    PERMISSION_ADD_BILL_CATEGORIES: "Add Bill Categories",
    PERMISSION_EDIT_BILL_CATEGORIES: "Edit Bill Categories",
    PERMISSION_VIEW_CHART_OF_ACCOUNTS: "View Accounts",
    PERMISSION_ADD_CHART_OF_ACCOUNTS: "Add Accounts",
    PERMISSION_EDIT_CHART_OF_ACCOUNTS: "Edit Accounts",
    PERMISSION_VIEW_BILLING_MANAGEMENT: "View Billing Management",
    PERMISSION_BILL_UPLOADS: "Bill Uploads",
    PERMISSION_VIEW_UNIT_RECEIVABLES: "View Unit Receivables",
    PERMISSION_VIEW_SERVICE_FEE_PAYMENTS: "View Service Fee Payments Page",
    PERMISSION_VIEW_PAYMENT_METHODS: "View Payment Methods",
    PERMISSION_ADD_PAYMENT_METHODS: "Add Payment Methods",
    PERMISSION_EDIT_PAYMENT_METHODS: "Edit Payment Methods",
}

ALL_PERMISSION_NAMES = list(PERMISSION_NAME_BY_ID.values())

COMMUNICATION_PERMISSIONS = {
    "announcements": {
        "add": PERMISSION_ADD_ANNOUNCEMENTS,
        "view": PERMISSION_VIEW_ANNOUNCEMENTS,
        "edit": PERMISSION_EDIT_ANNOUNCEMENTS,
        "expire": PERMISSION_EXPIRE_ANNOUNCEMENTS,
        "pin": PERMISSION_PIN_ANNOUNCEMENTS,
    },
    "bulletin_board": {
        "add": PERMISSION_ADD_BULLETIN_BOARD,
        "view": PERMISSION_VIEW_BULLETIN_BOARD,
        "edit": PERMISSION_EDIT_BULLETIN_BOARD,
        "archive": PERMISSION_ARCHIVE_BULLETIN_BOARD,
        "approve_reject": PERMISSION_APPROVE_REJECT_BULLETIN_BOARD,
    },
    "notice_board": {
        "add": PERMISSION_ADD_NOTICE_BOARD,
        "view": PERMISSION_VIEW_NOTICE_BOARD,
        "edit": PERMISSION_EDIT_NOTICE_BOARD,
        "expire": PERMISSION_EXPIRE_NOTICE_BOARD,
    },
}

