# Generated by Django 5.2.1 on 2025-06-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='manually_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='label',
            field=models.CharField(choices=[('sports', 'Sports'), ('events', 'Events'), ('maintenance', 'Maintenance'), ('general', 'General'), ('important', 'Important'), ('notice', 'Notice')], max_length=20),
        ),
    ]
