# Generated by Django 5.2.1 on 2025-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_manually_expired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
