# Generated by Django 5.2.1 on 2025-06-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_announcement_posted_group_announcement_posted_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='member_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
