# Generated by Django 5.2.1 on 2025-06-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_announcement_group_name_announcement_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
