# Generated by Django 5.2.3 on 2025-07-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_alter_announcement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='label',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
