# Generated by Django 5.2.7 on 2025-12-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_is_pinn_6f4cb5_idx',
            old_name='announcemen_is_pinn_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_status_c8b2ec_idx',
            old_name='announcemen_status_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_priorit_8accd1_idx',
            old_name='announcemen_priorit_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_start_d_c54642_idx',
            old_name='announcemen_start_d_idx',
        ),
        migrations.RenameIndex(
            model_name='announcement',
            new_name='announcemen_creator_577aa7_idx',
            old_name='announcemen_creator_idx',
        ),
    ]
