# Generated by Django 5.2.3 on 2025-09-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audittrail',
            name='event_type',
            field=models.CharField(choices=[('MEMBER_CREATED', 'MEMBER CREATED'), ('MEMBER_UPDATED', 'MEMBER UPDATED'), ('MEMBER_STATUS_CHANGED', 'MEMBER STATUS CHANGED'), ('GROUP_CREATE', 'Group Created'), ('GROUP_UPDATE', 'Group Updated'), ('GROUP_STATUS_CHANGE', 'GROUP STATUS CHANGE'), ('ROLE_CREATED', 'ROLE CREATED'), ('ROLE_UPDATED', 'ROLE UPDATED'), ('ROLE_STATUS_CHANGED', 'ROLE STATUS CHANGED'), ('PAYMENT_CREATED', 'PAYMENT CREATED'), ('PAYMENT_UPDATED', 'PAYMENT UPDATED'), ('PAYMENT_DELETED', 'PAYMENT DELETED'), ('PAYMENT_STATUS_CHANGED', 'PAYMENT STATUS CHANGED'), ('SERVICE_FEE_CREATED', 'SERVICE FEE CREATED'), ('SERVICE_FEE_UPDATED', 'SERVICE FEE UPDATED'), ('SERVICE_FEE_DELETED', 'SERVICE FEE DELETED'), ('SERVICE_FEE_STATUS_CHANGED', 'SERVICE FEE STATUS CHANGED')], max_length=30),
        ),
    ]
