# Generated by Django 5.0.2 on 2025-09-18 14:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_fee', '0007_alter_servicefeemfs_unique_together_and_more'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Unique transaction identifier', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer'), ('sslcommerz', 'SSLCommerz')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('service_status', models.CharField(choices=[('due', 'Due'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='due', help_text='Auto-calculated based on payment vs service fee amount', max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True, help_text='When payment was initiated')),
                ('due_date', models.DateField(auto_now_add=True, help_text='Service fee due date', null=True)),
                ('completion_date', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('reference_number', models.CharField(blank=True, help_text='External reference (e.g., MFS transaction ID)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional payment notes', null=True)),
                ('service_period_month', models.IntegerField(help_text='Month for which service fee is paid (1-12)')),
                ('service_period_year', models.IntegerField(help_text='Year for which service fee is paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_management_recorded_payments', to='user.member')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_management_payments', to='user.member')),
                ('service_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='management_payments', to='service_fee.servicefee')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_management_payments', to='towers.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_fee_management_updated_payments', to='user.member')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('resident', 'unit', 'service_period_month', 'service_period_year', 'service_fee')},
            },
        ),
    ]
