# Generated by Django 5.0.2 on 2025-09-18 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0001_initial'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeepayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_fee_management_recorded_payments', to='user.member'),
        ),
    ]
