# Generated by Django 5.0.2 on 2025-09-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0002_alter_servicefeepayment_created_by'),
    ]

    operations = [
    ]
