# Generated by Django 5.0.2 on 2025-09-24 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0003_fix_null_created_by'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_name', models.CharField(help_text='Name/title of the reminder', max_length=255)),
                ('reminder_type', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Manual Send', 'Manual Send')], default='Scheduled', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused')], default='Active', max_length=20)),
                ('send_when', models.JSONField(default=list, help_text="List of timing options (e.g., ['1 day before due', '3 days after due'])")),
                ('app_notification', models.BooleanField(default=False)),
                ('sms', models.BooleanField(default=False)),
                ('email', models.BooleanField(default=False)),
                ('audience', models.CharField(choices=[('All Towers', 'All Towers'), ('All Residents', 'All Residents'), ('Specific Tower', 'Specific Tower'), ('Specific Units', 'Specific Units'), ('Specific Resident', 'Specific Resident'), ('Due Only', 'Due Only'), ('Overdue Only', 'Overdue Only')], default='All Towers', max_length=50)),
                ('specific_target', models.CharField(blank=True, help_text="Specific target when audience is 'Specific...'", max_length=255, null=True)),
                ('message_preview', models.TextField(help_text='Template message for the reminder')),
                ('total_sent', models.IntegerField(default=0, help_text='Total number of reminders sent')),
                ('last_sent', models.DateTimeField(blank=True, help_text='When this reminder was last sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to='user.member')),
            ],
            options={
                'db_table': 'service_fee_reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='Channel used: App, SMS, Email', max_length=20)),
                ('message_content', models.TextField(help_text='Actual message sent')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reminders', to='user.member')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='service_fee_management.reminder')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_reminders', to='towers.unit')),
            ],
            options={
                'db_table': 'service_fee_reminder_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
