# Generated by Django 5.0.2 on 2025-09-24 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0004_reminder_reminderlog'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_reminders', to='user.member'),
        ),
    ]
