# Generated by Django 5.2.7 on 2025-10-06 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0011_alter_servicefee_fee_amount'),
        ('service_fee_management', '0005_alter_reminder_created_by'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicefeepayment',
            unique_together={('unit', 'service_period_month', 'service_period_year', 'service_fee')},
        ),
        migrations.AlterField(
            model_name='servicefeepayment',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_management_payments', to='user.member'),
        ),
    ]
