# Generated by Django - simplified payment method migration

from django.db import migrations, models


def create_payment_method_table(apps, schema_editor):
    """Create PaymentMethod table with MyISAM engine explicitly"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS `service_fee_payment_methods` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `method_name` varchar(100) NOT NULL,
                    `is_active` tinyint(1) NOT NULL DEFAULT 1,
                    `display_order` int NOT NULL DEFAULT 0,
                    `icon` varchar(100) DEFAULT NULL,
                    `description` longtext,
                    `created_at` datetime(6) NOT NULL,
                    `updated_at` datetime(6) NOT NULL,
                    PRIMARY KEY (`id`),
                    UNIQUE KEY `method_name_unique` (`method_name`)
                ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
            """)


def drop_payment_method_table(apps, schema_editor):
    """Drop PaymentMethod table"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("DROP TABLE IF EXISTS `service_fee_payment_methods`")


def populate_payment_methods(apps, schema_editor):
    """Populate initial payment methods"""
    PaymentMethod = apps.get_model('service_fee_management', 'PaymentMethod')
    
    payment_methods = [
        {'method_name': 'Cash', 'display_order': 1, 'description': 'Cash payment'},
        {'method_name': 'bKash', 'display_order': 2, 'description': 'bKash mobile financial service'},
        {'method_name': 'Nagad', 'display_order': 3, 'description': 'Nagad mobile financial service'},
        {'method_name': 'Rocket', 'display_order': 4, 'description': 'Rocket mobile financial service'},
    ]
    
    for method in payment_methods:
        PaymentMethod.objects.get_or_create(
            method_name=method['method_name'],
            defaults={
                'display_order': method['display_order'],
                'description': method.get('description', ''),
                'is_active': True
            }
        )


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0006_alter_servicefeepayment_unique_together_and_more'),
    ]

    operations = [
        # Create table with MyISAM engine using raw SQL, then register model in Django state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Create the actual table with MyISAM engine
                migrations.RunPython(create_payment_method_table, reverse_code=drop_payment_method_table),
            ],
            state_operations=[
                # Register the model in Django's migration state (doesn't touch database)
                migrations.CreateModel(
                    name='PaymentMethod',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('method_name', models.CharField(help_text="Display name (e.g., 'Cash', 'bKash')", max_length=100, unique=True)),
                        ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is currently available')),
                        ('display_order', models.IntegerField(default=0, help_text='Order in which to display this method')),
                        ('icon', models.CharField(blank=True, help_text='Icon class or image path', max_length=100, null=True)),
                        ('description', models.TextField(blank=True, help_text='Additional details about this payment method', null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'db_table': 'service_fee_payment_methods',
                        'ordering': ['display_order', 'method_name'],
                    },
                ),
            ],
        ),
        
        # Populate PaymentMethod table with initial data
        migrations.RunPython(populate_payment_methods, reverse_code=migrations.RunPython.noop),
    ]
