# Generated by Django 5.2.7 on 2025-10-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0007_paymentmethod_and_migrate_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeepayment',
            name='payment_date',
            field=models.DateTimeField(auto_now=True, help_text='When payment was last updated'),
        ),
    ]
