# Generated by Django - Add payment_method_rel ForeignKey mapped to payment_method_id column

from django.db import migrations, models
import django.db.models.deletion


def add_payment_method_fk_if_not_exists(apps, schema_editor):
    """
    Add payment_method_rel FK if it doesn't exist.
    Check if payment_method_id column exists first to handle parallel migrations.
    """
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check if payment_method_id column exists
            cursor.execute("""
                SELECT COLUMN_NAME, COLUMN_TYPE 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment' 
                AND COLUMN_NAME = 'payment_method_id'
            """)
            result = cursor.fetchone()
            
            if result:
                print("payment_method_id column already exists, skipping database creation")
                return
            
            # Column doesn't exist, add it manually
            print("Adding payment_method_id column as foreign key")
            cursor.execute("""
                ALTER TABLE service_fee_management_servicefeepayment
                ADD COLUMN payment_method_id BIGINT NULL,
                ADD CONSTRAINT fk_payment_method
                FOREIGN KEY (payment_method_id) 
                REFERENCES service_fee_payment_methods(id)
                ON DELETE RESTRICT
            """)
            print("Successfully added payment_method_id column")


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0008_update_payment_date_auto_now'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle state and database changes separately
        migrations.SeparateDatabaseAndState(
            # State operations - always executed to update Django's internal state
            state_operations=[
                migrations.AddField(
                    model_name='servicefeepayment',
                    name='payment_method_rel',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='payments',
                        to='service_fee_management.paymentmethod',
                        help_text='Payment method used',
                        db_column='payment_method_id'
                    ),
                ),
            ],
            # Database operations - check if column exists before adding
            database_operations=[
                migrations.RunPython(
                    code=add_payment_method_fk_if_not_exists,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
    ]
