# Generated by Django - Fix payment_method column default value

from django.db import migrations


def fix_payment_method_column(apps, schema_editor):
    """Make the old payment_method VARCHAR column nullable with default"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check if payment_method column exists as VARCHAR
            cursor.execute("""
                SELECT DATA_TYPE 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE()
                AND TABLE_NAME = 'service_fee_management_servicefeepayment' 
                AND COLUMN_NAME = 'payment_method'
            """)
            result = cursor.fetchone()
            
            if result and 'varchar' in result[0].lower():
                # Make it nullable with default value
                cursor.execute("""
                    ALTER TABLE service_fee_management_servicefeepayment 
                    MODIFY COLUMN payment_method VARCHAR(20) DEFAULT 'cash' NULL
                """)
                print("✓ Updated payment_method column to nullable with default 'cash'")


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0009_convert_payment_method_to_fk'),
    ]

    operations = [
        migrations.RunPython(fix_payment_method_column, reverse_code=migrations.RunPython.noop),
    ]
