# Generated by Django - Remove old payment_method CharField

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0010_fix_payment_method_default'),
    ]

    operations = [
        # Remove the old payment_method CharField from Django's migration state ONLY
        # The column doesn't exist in the database anymore (was renamed in migration 0009)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database changes needed - column already gone
            ],
            state_operations=[
                # Remove from Django's state
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='payment_method',
                ),
            ],
        ),
    ]
