# Generated by Django 5.2.5 on 2025-10-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0009_remove_old_payment_method_column'),
        ('service_fee_management', '0011_remove_servicefeepayment_payment_method'),
    ]

    operations = [
    ]
