# Generated by Django 5.2.3 on 2025-10-23 16:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0017_remove_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeepayment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original service fee amount for this month', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='servicefeepayment',
            name='remaining_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Remaining amount to be paid for this month', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
