# Generated by Django 5.2.3 on 2025-10-29 13:46

from django.db import migrations, models
import uuid
from datetime import datetime


def populate_receipt_transaction_ids(apps, schema_editor):
    """
    Populate receipt_id and transaction_id for existing ServiceFeePayment records using raw SQL - robust version
    """
    if schema_editor.connection.vendor != 'mysql':
        return
    
    try:
        with schema_editor.connection.cursor() as cursor:
            # Check if table exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.TABLES 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
            """)
            if cursor.fetchone()[0] == 0:
                print("Table service_fee_management_servicefeepayment does not exist, skipping")
                return
            
            # Check if columns exist
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME IN ('receipt_id', 'transaction_id')
            """)
            if cursor.fetchone()[0] < 2:
                print("Columns receipt_id or transaction_id do not exist yet, skipping")
                return
            
            # Get all payments that need IDs
            cursor.execute("""
                SELECT id, billing_id 
                FROM service_fee_management_servicefeepayment 
                WHERE receipt_id IS NULL OR transaction_id IS NULL
            """)
            
            payments = cursor.fetchall()
            
            # Determine billing table name
            billing_table_names = ['service_fee_payment_details', 'service_fee_billings']
            billing_table = None
            for table_name in billing_table_names:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.TABLES 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                """, [table_name])
                if cursor.fetchone()[0] > 0:
                    billing_table = table_name
                    break
            
            for payment_id, billing_id in payments:
                try:
                    # Generate receipt ID
                    if billing_id and billing_table:
                        # Get billing info
                        cursor.execute(f"""
                            SELECT service_period_year, service_period_month 
                            FROM {billing_table} 
                            WHERE id = %s
                        """, [billing_id])
                        billing_info = cursor.fetchone()
                        
                        if billing_info:
                            year, month = billing_info
                        else:
                            year = datetime.now().year
                            month = datetime.now().month
                    else:
                        year = datetime.now().year
                        month = datetime.now().month
                    
                    # Generate IDs
                    short_id = str(uuid.uuid4()).replace('-', '').upper()[:5]
                    receipt_id = f"RCP-{year}-{month:02d}-{short_id}"
                    transaction_id = f"TXN{str(uuid.uuid4()).replace('-', '').upper()[:12]}"
                    
                    # Update the record
                    cursor.execute("""
                        UPDATE service_fee_management_servicefeepayment 
                        SET receipt_id = %s, transaction_id = %s 
                        WHERE id = %s
                    """, [receipt_id, transaction_id, payment_id])
                except Exception as e:
                    print(f"Error updating payment {payment_id}: {e}")
                    continue
            
            print(f"Populated receipt_id and transaction_id for {len(payments)} payments")
    except Exception as e:
        print(f"Error in populate_receipt_transaction_ids: {e}")
        # Continue migration even if this fails


def reverse_populate_receipt_transaction_ids(apps, schema_editor):
    """
    Reverse operation - set receipt_id and transaction_id to None - robust version
    """
    if schema_editor.connection.vendor != 'mysql':
        return
    
    try:
        with schema_editor.connection.cursor() as cursor:
            # Check if table exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.TABLES 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
            """)
            if cursor.fetchone()[0] == 0:
                return
            
            cursor.execute("""
                UPDATE service_fee_management_servicefeepayment 
                SET receipt_id = NULL, transaction_id = NULL
            """)
    except Exception as e:
        print(f"Error in reverse_populate_receipt_transaction_ids: {e}")
        # Continue migration even if this fails


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0024_rename_table_with_underscore'),
    ]

    operations = [
        # First, populate the fields with data
        migrations.RunPython(
            populate_receipt_transaction_ids,
            reverse_populate_receipt_transaction_ids,
        ),
        # Then make them non-nullable
        migrations.AlterField(
            model_name='servicefeepayment',
            name='receipt_id',
            field=models.CharField(help_text='Unique receipt identifier (e.g., RCP-2024-01-00001)', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='servicefeepayment',
            name='transaction_id',
            field=models.CharField(help_text='Unique transaction identifier', max_length=100, unique=True),
        ),
    ]
