# Generated by Django 5.2.7 on 2025-10-29 14:52

import django.core.validators
from django.db import migrations, models


def safe_remove_constraint(apps, schema_editor):
    """Safely remove constraint only if it exists"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check if the constraint exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.KEY_COLUMN_USAGE 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_payment_details'
                AND CONSTRAINT_NAME = 'unique_billing_per_month'
            """)
            constraint_exists = cursor.fetchone()[0] > 0
            
            if constraint_exists:
                cursor.execute("ALTER TABLE service_fee_payment_details DROP INDEX unique_billing_per_month;")
                print("Removed unique_billing_per_month constraint")
            else:
                print("Constraint unique_billing_per_month does not exist, skipping removal")


def reverse_safe_remove_constraint(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0015_alter_servicefee_service_fee_date'),
        ('service_fee_management', '0025_auto_20251029_1346'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
    ]

    operations = [
        migrations.RunPython(
            safe_remove_constraint,
            reverse_safe_remove_constraint,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Skip database operations for unique_together since it might not exist
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='servicefeepayment',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='servicefeepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='servicefeepayment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Status of this payment transaction', max_length=20),
        ),
        # Removed AlterUniqueTogether for ServiceFeeBilling - fields no longer exist
        # The 'unit', 'service_period_month', 'service_period_year', 'service_fee' fields
        # were removed in later migrations (0036), so this operation is skipped
        # Fields below were already removed in migration 0020, so we only update state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Skip database operations since fields were already removed
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='due_date',
                ),
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='original_amount',
                ),
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='remaining_amount',
                ),
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='service_period_month',
                ),
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='service_period_year',
                ),
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='service_status',
                ),
            ],
        ),
    ]
