# Generated by Django 5.2.3 on 2025-10-29 15:08

from django.db import migrations


def safe_remove_constraint_0028(apps, schema_editor):
    """Safely remove constraint only if it exists, handling foreign key dependencies"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check if the constraint/index exists in service_fee_payment_details table
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.STATISTICS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_payment_details'
                AND INDEX_NAME = 'unique_billing_per_month'
            """)
            index_exists = cursor.fetchone()[0] > 0
            
            if not index_exists:
                print("Index unique_billing_per_month does not exist, skipping removal (migration 0028)")
                return
            
            # Find foreign key constraints that reference this unique constraint
            # These need to be dropped before we can drop the index
            cursor.execute("""
                SELECT DISTINCT rc.CONSTRAINT_NAME
                FROM information_schema.REFERENTIAL_CONSTRAINTS rc
                WHERE rc.CONSTRAINT_SCHEMA = DATABASE()
                AND rc.UNIQUE_CONSTRAINT_NAME = 'unique_billing_per_month'
                UNION
                SELECT kcu.CONSTRAINT_NAME
                FROM information_schema.KEY_COLUMN_USAGE kcu
                INNER JOIN information_schema.REFERENTIAL_CONSTRAINTS rc2 
                    ON kcu.CONSTRAINT_NAME = rc2.CONSTRAINT_NAME 
                    AND kcu.TABLE_SCHEMA = rc2.CONSTRAINT_SCHEMA
                WHERE kcu.TABLE_SCHEMA = DATABASE()
                AND kcu.TABLE_NAME = 'service_fee_payment_details'
                AND EXISTS (
                    SELECT 1 FROM information_schema.STATISTICS s
                    WHERE s.TABLE_SCHEMA = DATABASE()
                    AND s.TABLE_NAME = 'service_fee_payment_details'
                    AND s.INDEX_NAME = 'unique_billing_per_month'
                    AND s.COLUMN_NAME = kcu.COLUMN_NAME
                )
            """)
            
            fk_constraints = cursor.fetchall()
            dropped_fks = []
            
            # Drop foreign keys that depend on this index
            for fk_row in fk_constraints:
                fk_name = fk_row[0]
                try:
                    cursor.execute(f"ALTER TABLE service_fee_payment_details DROP FOREIGN KEY `{fk_name}`")
                    dropped_fks.append(fk_name)
                    print(f"Dropped foreign key: {fk_name}")
                except Exception as e:
                    print(f"Warning: Could not drop FK {fk_name}: {e}")
            
            # Now drop the index
            try:
                cursor.execute("ALTER TABLE service_fee_payment_details DROP INDEX unique_billing_per_month")
                print("Removed unique_billing_per_month index (migration 0028)")
            except Exception as e:
                # If still failing, try with foreign key checks disabled
                print(f"Error dropping index: {e}, trying with FK checks disabled...")
                cursor.execute("SET FOREIGN_KEY_CHECKS = 0")
                try:
                    cursor.execute("ALTER TABLE service_fee_payment_details DROP INDEX unique_billing_per_month")
                    print("Removed unique_billing_per_month index with FK checks disabled (migration 0028)")
                finally:
                    cursor.execute("SET FOREIGN_KEY_CHECKS = 1")
            
            # Note: Foreign keys will be recreated by Django when needed through model definitions


def reverse_safe_remove_constraint_0028(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0027_rename_table_to_payment_details'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    safe_remove_constraint_0028,
                    reverse_safe_remove_constraint_0028,
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='servicefeebilling',
                    name='unique_billing_per_month',
                ),
            ],
        ),
    ]
