# Generated by Django 5.2.3 on 2025-10-29 15:15

from django.db import migrations, models


def safe_add_service_period_year(apps, schema_editor):
    """Safely add service_period_year field only if it doesn't exist"""
    if schema_editor.connection.vendor != 'mysql':
        return
    
    try:
        with schema_editor.connection.cursor() as cursor:
            # Check if the column exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'service_period_year'
            """)
            column_exists = cursor.fetchone()[0] > 0
            
            if not column_exists:
                cursor.execute("""
                    ALTER TABLE service_fee_management_servicefeepayment 
                    ADD COLUMN service_period_year INT NULL 
                    COMMENT 'Year for which service fee is paid'
                """)
                print("Added service_period_year column")
            else:
                print("Column service_period_year already exists, skipping")
    except Exception as e:
        print(f"Error in safe_add_service_period_year: {e}")
        # Continue migration even if this fails


def reverse_safe_add_service_period_year(apps, schema_editor):
    """Reverse operation - do nothing (keep the field)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0028_remove_servicefeebilling_unique_billing_per_month'),
    ]

    operations = [
        migrations.RunPython(
            safe_add_service_period_year,
            reverse_safe_add_service_period_year,
        ),
        # Update state to reflect the field exists
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Already handled by RunPython above
            state_operations=[
                migrations.AddField(
                    model_name='servicefeepayment',
                    name='service_period_year',
                    field=models.IntegerField(blank=True, help_text='Year for which service fee is paid', null=True),
                ),
            ],
        ),
    ]
