# Generated by Django 5.2.7 on 2025-10-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0020_remove_redundant_fields_original'),
        ('service_fee_management', '0020_remove_redundant_fields_safe'),
        ('service_fee_management', '0026_finalize_payment_ids'),
        ('service_fee_management', '0029_add_service_period_year_to_payment'),
    ]

    operations = [
    ]
