# Generated by Django 5.2.3 on 2025-10-30 09:33

from django.db import migrations, models


def check_and_add_field(apps, schema_editor):
    """Add service_period_month field only if it doesn't exist"""
    if schema_editor.connection.vendor != 'mysql':
        return
    
    try:
        from django.db import connection
        
        with connection.cursor() as cursor:
            # Check if column exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment' 
                AND COLUMN_NAME = 'service_period_month'
            """)
            
            exists = cursor.fetchone()[0] > 0
            
            if not exists:
                # Column doesn't exist, add it
                # First check if it should be nullable based on model
                cursor.execute("""
                    ALTER TABLE service_fee_management_servicefeepayment 
                    ADD COLUMN service_period_month INT NULL 
                    COMMENT 'Month for which service fee is paid (1-12)'
                """)
                print("Added service_period_month column")
            else:
                # Column exists, just make it nullable if it's not already
                try:
                    cursor.execute("""
                        ALTER TABLE service_fee_management_servicefeepayment 
                        MODIFY COLUMN service_period_month INT NULL
                    """)
                    print("service_period_month column already exists, made nullable")
                except Exception as e:
                    print(f"Could not modify service_period_month column (may already be nullable): {e}")
    except Exception as e:
        print(f"Error in check_and_add_field: {e}")
        # Continue migration even if this fails


def reverse_check_and_add_field(apps, schema_editor):
    """Reverse operation - do nothing as we can't safely remove"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0031_remove_unique_payment_constraint'),
    ]

    operations = [
        migrations.RunPython(
            check_and_add_field,
            reverse_check_and_add_field,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='servicefeepayment',
                    name='service_period_month',
                    field=models.IntegerField(blank=True, help_text='Month for which service fee is paid (1-12)', null=True),
                ),
            ],
        ),
    ]
