# Generated by Django 5.2.7 on 2025-11-06 15:13

from django.db import migrations, models


def drop_old_unique_constraint(apps, schema_editor):
    """
    Drop the old unique_together constraint on ServiceFeeBilling if it exists
    Safely handles both indexes and foreign keys for both table names
    """
    if schema_editor.connection.vendor != 'mysql':
        return
    
    # Tables that might exist (due to table renames)
    tables_to_check = ['service_fee_payment_details', 'service_fee_billings', 'service_fee_management_servicefeebilling']
    
    with schema_editor.connection.cursor() as cursor:
        for table_name in tables_to_check:
            try:
                # Check if table exists
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                """, [table_name])
                if cursor.fetchone()[0] == 0:
                    continue  # Table doesn't exist, skip
                
                print(f"Checking constraints on table: {table_name}")
                
                # Find all foreign key constraints
                cursor.execute("""
                    SELECT DISTINCT CONSTRAINT_NAME
                    FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                    AND CONSTRAINT_NAME != 'PRIMARY'
                    AND REFERENCED_TABLE_NAME IS NOT NULL
                """, [table_name])
                foreign_keys = cursor.fetchall()
                
                # Drop foreign keys first (they must be dropped before indexes)
                for (fk_name,) in foreign_keys:
                    try:
                        # Double-check it exists
                        cursor.execute("""
                            SELECT COUNT(*) 
                            FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
                            WHERE TABLE_SCHEMA = DATABASE() 
                            AND TABLE_NAME = %s
                            AND CONSTRAINT_NAME = %s
                        """, [table_name, fk_name])
                        if cursor.fetchone()[0] > 0:
                            cursor.execute(f"ALTER TABLE `{table_name}` DROP FOREIGN KEY `{fk_name}`")
                            print(f"Dropped foreign key {fk_name} from {table_name}")
                    except Exception as e:
                        print(f"Could not drop foreign key {fk_name} from {table_name}: {e}")
                
                # Find unique constraints
                cursor.execute("""
                    SELECT DISTINCT CONSTRAINT_NAME
                    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                    AND CONSTRAINT_NAME != 'PRIMARY'
                    AND CONSTRAINT_TYPE = 'UNIQUE'
                """, [table_name])
                unique_constraints = cursor.fetchall()
                
                # Drop unique constraints
                for (constraint_name,) in unique_constraints:
                    try:
                        cursor.execute(f"ALTER TABLE `{table_name}` DROP INDEX `{constraint_name}`")
                        print(f"Dropped unique constraint {constraint_name} from {table_name}")
                    except Exception as e:
                        print(f"Could not drop unique constraint {constraint_name} from {table_name}: {e}")
                
                # Find standalone indexes (not constraints)
                cursor.execute("""
                    SELECT DISTINCT INDEX_NAME
                    FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = DATABASE()
                    AND TABLE_NAME = %s
                    AND INDEX_NAME != 'PRIMARY'
                    AND INDEX_NAME NOT IN (
                        SELECT CONSTRAINT_NAME 
                        FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
                        WHERE TABLE_SCHEMA = DATABASE() 
                        AND TABLE_NAME = %s
                    )
                """, [table_name, table_name])
                indexes = cursor.fetchall()
                
                # Drop standalone indexes
                for (index_name,) in indexes:
                    try:
                        cursor.execute(f"ALTER TABLE `{table_name}` DROP INDEX `{index_name}`")
                        print(f"Dropped index {index_name} from {table_name}")
                    except Exception as e:
                        print(f"Could not drop index {index_name} from {table_name}: {e}")
                        
            except Exception as e:
                print(f"Error processing table {table_name}: {e}")
                # Continue with other tables even if one fails


def safe_add_fields(apps, schema_editor):
    """Safely add fields only if they don't exist"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check and add billing_reference
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'billing_reference'
            """)
            billing_ref_exists = cursor.fetchone()[0] > 0
            
            if not billing_ref_exists:
                cursor.execute("""
                    ALTER TABLE service_fee_management_servicefeepayment 
                    ADD COLUMN billing_reference VARCHAR(100) DEFAULT 'BILL-LEGACY' 
                    COMMENT 'Unique billing identifier (e.g., BILL-2024-01-00001)'
                """)
                print("Added billing_reference column")
            else:
                print("Column billing_reference already exists, skipping")
            
            # Check and add service_status
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'service_status'
            """)
            service_status_exists = cursor.fetchone()[0] > 0
            
            if not service_status_exists:
                cursor.execute("""
                    ALTER TABLE service_fee_management_servicefeepayment 
                    ADD COLUMN service_status VARCHAR(20) DEFAULT 'due' 
                    COMMENT 'Service status at time of payment'
                """)
                print("Added service_status column")
            else:
                print("Column service_status already exists, skipping")


def reverse_safe_add_fields(apps, schema_editor):
    """Reverse operation - do nothing (keep the fields)"""
    pass


def safe_remove_fields(apps, schema_editor):
    """Safely remove fields from ServiceFeeBilling only if they exist"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check and remove billing_id
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_payment_details'
                AND COLUMN_NAME = 'billing_id'
            """)
            billing_id_exists = cursor.fetchone()[0] > 0
            
            if billing_id_exists:
                cursor.execute("ALTER TABLE service_fee_payment_details DROP COLUMN billing_id")
                print("Removed billing_id column")
            else:
                print("Column billing_id does not exist, skipping removal")
            
            # Check and remove service_period_month
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_payment_details'
                AND COLUMN_NAME = 'service_period_month'
            """)
            service_period_month_exists = cursor.fetchone()[0] > 0
            
            if service_period_month_exists:
                cursor.execute("ALTER TABLE service_fee_payment_details DROP COLUMN service_period_month")
                print("Removed service_period_month column")
            else:
                print("Column service_period_month does not exist, skipping removal")
            
            # Check and remove service_period_year
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_payment_details'
                AND COLUMN_NAME = 'service_period_year'
            """)
            service_period_year_exists = cursor.fetchone()[0] > 0
            
            if service_period_year_exists:
                cursor.execute("ALTER TABLE service_fee_payment_details DROP COLUMN service_period_year")
                print("Removed service_period_year column")
            else:
                print("Column service_period_year does not exist, skipping removal")


def reverse_safe_remove_fields(apps, schema_editor):
    """Reverse operation - do nothing (fields are already removed)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0015_alter_servicefee_service_fee_date'),
        ('service_fee_management', '0034_drop_additional_legacy_unique_index'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
    ]

    operations = [
        # Step 1: Drop the old unique constraint using Python function
        migrations.RunPython(drop_old_unique_constraint, reverse_code=migrations.RunPython.noop),
        
        # Step 2: Add new fields to ServiceFeePayment (safely check if they exist)
        migrations.RunPython(safe_add_fields, reverse_safe_add_fields),
        
        # Update state to reflect the fields exist
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Already handled by RunPython above
            state_operations=[
                migrations.AddField(
                    model_name='servicefeepayment',
                    name='billing_reference',
                    field=models.CharField(default='BILL-LEGACY', help_text='Unique billing identifier (e.g., BILL-2024-01-00001)', max_length=100),
                ),
                migrations.AddField(
                    model_name='servicefeepayment',
                    name='service_status',
                    field=models.CharField(choices=[('due', 'Due'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='due', help_text='Service status at time of payment', max_length=20),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='servicefeepayment',
            name='service_period_month',
            field=models.IntegerField(default=1, help_text='Month for which service fee is paid (1-12)'),
        ),
        migrations.AlterField(
            model_name='servicefeepayment',
            name='service_period_year',
            field=models.IntegerField(default=2024, help_text='Year for which service fee is paid'),
        ),
        
        # Step 3: Remove fields from ServiceFeeBilling (safely check if they exist)
        migrations.RunPython(safe_remove_fields, reverse_safe_remove_fields),
        
        # Update state to reflect the fields are removed
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Already handled by RunPython above
            state_operations=[
                migrations.RemoveField(
                    model_name='servicefeebilling',
                    name='billing_id',
                ),
                migrations.RemoveField(
                    model_name='servicefeebilling',
                    name='service_period_month',
                ),
                migrations.RemoveField(
                    model_name='servicefeebilling',
                    name='service_period_year',
                ),
            ],
        ),
        
        # Step 4: Add new unique_together constraint
        # Removed - ServiceFeeBilling model no longer has 'unit' field
        # The model structure has been normalized and unit is accessed via ServiceFeePayment
        # migrations.AlterUniqueTogether(
        #     name='servicefeebilling',
        #     unique_together={('unit', 'service_fee')},
        # ),
        
        # Step 5: Rename the ServiceFeePayment table
        migrations.AlterModelTable(
            name='servicefeepayment',
            table='service_fee_management_servicefeepayment',
        ),
    ]
