# Generated by Django 5.2.7 on 2025-11-06 15:21

from django.db import migrations


def drop_unique_constraint_if_exists(apps, schema_editor):
    """Drop unique constraint if it exists - robust version"""
    if schema_editor.connection.vendor != 'mysql':
        return
    
    try:
        with schema_editor.connection.cursor() as cursor:
            # Determine the actual table name
            table_names = ['service_fee_payment_details', 'service_fee_billings']
            actual_table_name = None
            
            for table_name in table_names:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                """, [table_name])
                if cursor.fetchone()[0] > 0:
                    actual_table_name = table_name
                    break
            
            if not actual_table_name:
                print("Neither service_fee_payment_details nor service_fee_billings table exists, skipping constraint drop")
                return
            
            # Find and drop any unique constraints on unit_id and service_fee_id
            cursor.execute("""
                SELECT DISTINCT CONSTRAINT_NAME 
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME IN ('unit_id', 'service_fee_id')
                AND CONSTRAINT_NAME != 'PRIMARY'
            """, [actual_table_name])
            results = cursor.fetchall()
            
            for result in results:
                if result:
                    constraint_name = result[0]
                    try:
                        cursor.execute(f"ALTER TABLE `{actual_table_name}` DROP INDEX `{constraint_name}`")
                        print(f"Dropped constraint: {constraint_name} from {actual_table_name}")
                    except Exception as e:
                        print(f"Could not drop constraint {constraint_name}: {e}")
    except Exception as e:
        print(f"Error in drop_unique_constraint_if_exists: {e}")
        # Continue migration even if this fails


def safe_remove_fields_from_billing(apps, schema_editor):
    """Safely remove fields from ServiceFeeBilling only if they exist - robust version"""
    if schema_editor.connection.vendor != 'mysql':
        return
    
    try:
        with schema_editor.connection.cursor() as cursor:
            # Determine the actual table name
            table_names = ['service_fee_payment_details', 'service_fee_billings']
            actual_table_name = None
            
            for table_name in table_names:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                """, [table_name])
                if cursor.fetchone()[0] > 0:
                    actual_table_name = table_name
                    break
            
            if not actual_table_name:
                print("Neither service_fee_payment_details nor service_fee_billings table exists, skipping field removal")
                return
            
            print(f"Using table: {actual_table_name}")
            
            # Helper function to safely remove a column
            def remove_column_if_exists(column_name):
                try:
                    cursor.execute("""
                        SELECT COUNT(*) 
                        FROM information_schema.COLUMNS 
                        WHERE TABLE_SCHEMA = DATABASE() 
                        AND TABLE_NAME = %s
                        AND COLUMN_NAME = %s
                    """, [actual_table_name, column_name])
                    column_exists = cursor.fetchone()[0] > 0
                    
                    if column_exists:
                        # Check for foreign key constraints first
                        cursor.execute("""
                            SELECT CONSTRAINT_NAME
                            FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
                            WHERE TABLE_SCHEMA = DATABASE() 
                            AND TABLE_NAME = %s
                            AND COLUMN_NAME = %s
                            AND REFERENCED_TABLE_NAME IS NOT NULL
                        """, [actual_table_name, column_name])
                        fk_results = cursor.fetchall()
                        
                        # Drop foreign keys first
                        for fk_result in fk_results:
                            if fk_result:
                                fk_name = fk_result[0]
                                try:
                                    cursor.execute(f"ALTER TABLE `{actual_table_name}` DROP FOREIGN KEY `{fk_name}`")
                                    print(f"Dropped foreign key {fk_name} for {column_name}")
                                except Exception as e:
                                    print(f"Could not drop foreign key {fk_name}: {e}")
                        
                        # Now drop the column
                        cursor.execute(f"ALTER TABLE `{actual_table_name}` DROP COLUMN `{column_name}`")
                        print(f"Removed {column_name} column")
                    else:
                        print(f"Column {column_name} does not exist, skipping removal")
                except Exception as e:
                    print(f"Error removing column {column_name}: {e}")
            
            # Remove columns
            remove_column_if_exists('resident_id')
            remove_column_if_exists('service_fee_id')
            remove_column_if_exists('service_status')
            remove_column_if_exists('unit_id')
            
    except Exception as e:
        print(f"Error in safe_remove_fields_from_billing: {e}")
        # Continue migration even if this fails


def reverse_safe_remove_fields_from_billing(apps, schema_editor):
    """Reverse operation - do nothing (fields are already removed)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0035_restructure_billing_payment_tables'),
    ]

    operations = [
        # Drop the unique constraint first using Python function
        migrations.RunPython(drop_unique_constraint_if_exists, reverse_code=migrations.RunPython.noop),
        
        # Safely remove fields from ServiceFeeBilling (check if they exist)
        migrations.RunPython(safe_remove_fields_from_billing, reverse_safe_remove_fields_from_billing),
        
        # Update state to reflect the fields are removed
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Already handled by RunPython above
            state_operations=[
                migrations.RemoveField(
                    model_name='servicefeebilling',
                    name='resident',
                ),
                migrations.RemoveField(
                    model_name='servicefeebilling',
                    name='service_fee',
                ),
                migrations.RemoveField(
                    model_name='servicefeebilling',
                    name='service_status',
                ),
                migrations.RemoveField(
                    model_name='servicefeebilling',
                    name='unit',
                ),
            ],
        ),
    ]
