# Generated by Django 5.2.7 on 2025-11-06 15:25

import django.db.models.deletion
from django.db import migrations, models


def safe_add_fields_to_billing(apps, schema_editor):
    """Safely add fields to ServiceFeeBilling only if they don't exist"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Determine the actual table name
            table_names = ['service_fee_payment_details', 'service_fee_billings']
            actual_table_name = None
            
            for table_name in table_names:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                """, [table_name])
                if cursor.fetchone()[0] > 0:
                    actual_table_name = table_name
                    break
            
            if not actual_table_name:
                print("Neither service_fee_payment_details nor service_fee_billings table exists, skipping")
                return
            
            print(f"Using table: {actual_table_name}")
            
            # Check and add billing_id
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'billing_id'
            """, [actual_table_name])
            billing_id_exists = cursor.fetchone()[0] > 0
            
            if not billing_id_exists:
                # First add column without UNIQUE constraint
                cursor.execute(f"""
                    ALTER TABLE `{actual_table_name}` 
                    ADD COLUMN billing_id VARCHAR(100) DEFAULT 'BILL-LEGACY'
                    COMMENT 'Unique billing identifier (e.g., BILL-2024-01-00001)'
                """)
                print("Added billing_id column")
                
                # Update existing rows to have unique values
                cursor.execute(f"""
                    UPDATE `{actual_table_name}` 
                    SET billing_id = CONCAT('BILL-LEGACY-', id)
                    WHERE billing_id = 'BILL-LEGACY' OR billing_id IS NULL
                """)
                print("Updated existing billing_id values to be unique")
                
                # Now add UNIQUE constraint
                try:
                    cursor.execute(f"""
                        ALTER TABLE `{actual_table_name}` 
                        ADD UNIQUE INDEX billing_id_unique (billing_id)
                    """)
                    print("Added UNIQUE constraint to billing_id")
                except Exception as e:
                    print(f"Could not add UNIQUE constraint to billing_id (may already exist): {e}")
            else:
                print("Column billing_id already exists, skipping")
            
            # Check and add notes
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'notes'
            """, [actual_table_name])
            notes_exists = cursor.fetchone()[0] > 0
            
            if not notes_exists:
                cursor.execute(f"""
                    ALTER TABLE `{actual_table_name}` 
                    ADD COLUMN notes TEXT NULL
                    COMMENT 'Additional payment notes'
                """)
                print("Added notes column")
            else:
                print("Column notes already exists, skipping")
            
            # Check and add payment_date
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'payment_date'
            """, [actual_table_name])
            payment_date_exists = cursor.fetchone()[0] > 0
            
            if not payment_date_exists:
                cursor.execute(f"""
                    ALTER TABLE `{actual_table_name}` 
                    ADD COLUMN payment_date DATETIME(6) NULL
                    COMMENT 'When payment was made'
                """)
                print("Added payment_date column")
            else:
                print("Column payment_date already exists, skipping")
            
            # Check and add payment_method_id
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'payment_method_id'
            """, [actual_table_name])
            payment_method_id_exists = cursor.fetchone()[0] > 0
            
            if not payment_method_id_exists:
                cursor.execute(f"""
                    ALTER TABLE `{actual_table_name}` 
                    ADD COLUMN payment_method_id BIGINT NULL
                    COMMENT 'Payment method used'
                """)
                # Add foreign key constraint separately if it doesn't exist
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.TABLE_CONSTRAINTS 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                    AND CONSTRAINT_NAME = 'service_fee_payment_details_payment_method_id_fk'
                """, [actual_table_name])
                fk_exists = cursor.fetchone()[0] > 0
                if not fk_exists:
                    try:
                        cursor.execute(f"""
                            ALTER TABLE `{actual_table_name}` 
                            ADD CONSTRAINT service_fee_payment_details_payment_method_id_fk
                            FOREIGN KEY (payment_method_id) REFERENCES service_fee_payment_methods(id)
                        """)
                        print("Added payment_method_id foreign key constraint")
                    except Exception as e:
                        print(f"Could not add foreign key constraint (may already exist): {e}")
                print("Added payment_method_id column")
            else:
                print("Column payment_method_id already exists, skipping")
            
            # Check and add receipt_id
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'receipt_id'
            """, [actual_table_name])
            receipt_id_exists = cursor.fetchone()[0] > 0
            
            if not receipt_id_exists:
                # First add column without UNIQUE constraint
                cursor.execute(f"""
                    ALTER TABLE `{actual_table_name}` 
                    ADD COLUMN receipt_id VARCHAR(100) DEFAULT 'RCP-LEGACY'
                    COMMENT 'Unique receipt identifier (e.g., RCP-2024-01-00001)'
                """)
                print("Added receipt_id column")
                
                # Update existing rows to have unique values
                cursor.execute(f"""
                    UPDATE `{actual_table_name}` 
                    SET receipt_id = CONCAT('RCP-LEGACY-', id)
                    WHERE receipt_id = 'RCP-LEGACY' OR receipt_id IS NULL
                """)
                print("Updated existing receipt_id values to be unique")
                
                # Now add UNIQUE constraint
                try:
                    cursor.execute(f"""
                        ALTER TABLE `{actual_table_name}` 
                        ADD UNIQUE INDEX receipt_id_unique (receipt_id)
                    """)
                    print("Added UNIQUE constraint to receipt_id")
                except Exception as e:
                    print(f"Could not add UNIQUE constraint to receipt_id (may already exist): {e}")
            else:
                print("Column receipt_id already exists, skipping")
            
            # Check and add reference_number
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'reference_number'
            """, [actual_table_name])
            reference_number_exists = cursor.fetchone()[0] > 0
            
            if not reference_number_exists:
                cursor.execute(f"""
                    ALTER TABLE `{actual_table_name}` 
                    ADD COLUMN reference_number VARCHAR(100) NULL
                    COMMENT 'External reference (e.g., MFS transaction ID)'
                """)
                print("Added reference_number column")
            else:
                print("Column reference_number already exists, skipping")


def reverse_safe_add_fields_to_billing(apps, schema_editor):
    """Reverse operation - do nothing (keep the fields)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0036_alter_servicefeebilling_unique_together_and_more'),
    ]

    operations = [
        # Safely add fields to ServiceFeeBilling (check if they exist)
        migrations.RunPython(safe_add_fields_to_billing, reverse_safe_add_fields_to_billing),
        
        # Update state to reflect the fields exist
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Already handled by RunPython above
            state_operations=[
                migrations.AddField(
                    model_name='servicefeebilling',
                    name='billing_id',
                    field=models.CharField(default='BILL-LEGACY', help_text='Unique billing identifier (e.g., BILL-2024-01-00001)', max_length=100, unique=True),
                ),
                migrations.AddField(
                    model_name='servicefeebilling',
                    name='notes',
                    field=models.TextField(blank=True, help_text='Additional payment notes', null=True),
                ),
                migrations.AddField(
                    model_name='servicefeebilling',
                    name='payment_date',
                    field=models.DateTimeField(blank=True, help_text='When payment was made', null=True),
                ),
                migrations.AddField(
                    model_name='servicefeebilling',
                    name='payment_method',
                    field=models.ForeignKey(blank=True, db_column='payment_method_id', help_text='Payment method used', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billings', to='service_fee_management.paymentmethod'),
                ),
                migrations.AddField(
                    model_name='servicefeebilling',
                    name='receipt_id',
                    field=models.CharField(default='RCP-LEGACY', help_text='Unique receipt identifier (e.g., RCP-2024-01-00001)', max_length=100, unique=True),
                ),
                migrations.AddField(
                    model_name='servicefeebilling',
                    name='reference_number',
                    field=models.CharField(blank=True, help_text='External reference (e.g., MFS transaction ID)', max_length=100, null=True),
                ),
            ],
        ),
    ]
