# Generated by Django 5.2.7 on 2025-11-06 15:29

from django.db import migrations


def safe_remove_fields_from_payment(apps, schema_editor):
    """Safely remove fields from ServiceFeePayment only if they exist"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check and remove billing_reference
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'billing_reference'
            """)
            billing_reference_exists = cursor.fetchone()[0] > 0
            
            if billing_reference_exists:
                cursor.execute("ALTER TABLE service_fee_management_servicefeepayment DROP COLUMN billing_reference")
                print("Removed billing_reference column")
            else:
                print("Column billing_reference does not exist, skipping removal")
            
            # Check and remove notes
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'notes'
            """)
            notes_exists = cursor.fetchone()[0] > 0
            
            if notes_exists:
                cursor.execute("ALTER TABLE service_fee_management_servicefeepayment DROP COLUMN notes")
                print("Removed notes column")
            else:
                print("Column notes does not exist, skipping removal")
            
            # Check and remove payment_date
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'payment_date'
            """)
            payment_date_exists = cursor.fetchone()[0] > 0
            
            if payment_date_exists:
                cursor.execute("ALTER TABLE service_fee_management_servicefeepayment DROP COLUMN payment_date")
                print("Removed payment_date column")
            else:
                print("Column payment_date does not exist, skipping removal")
            
            # Check and remove payment_method_rel_id
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'payment_method_rel_id'
            """)
            payment_method_rel_id_exists = cursor.fetchone()[0] > 0
            
            if payment_method_rel_id_exists:
                cursor.execute("ALTER TABLE service_fee_management_servicefeepayment DROP COLUMN payment_method_rel_id")
                print("Removed payment_method_rel_id column")
            else:
                print("Column payment_method_rel_id does not exist, skipping removal")
            
            # Check and remove receipt_id
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'receipt_id'
            """)
            receipt_id_exists = cursor.fetchone()[0] > 0
            
            if receipt_id_exists:
                cursor.execute("ALTER TABLE service_fee_management_servicefeepayment DROP COLUMN receipt_id")
                print("Removed receipt_id column")
            else:
                print("Column receipt_id does not exist, skipping removal")
            
            # Check and remove reference_number
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'reference_number'
            """)
            reference_number_exists = cursor.fetchone()[0] > 0
            
            if reference_number_exists:
                cursor.execute("ALTER TABLE service_fee_management_servicefeepayment DROP COLUMN reference_number")
                print("Removed reference_number column")
            else:
                print("Column reference_number does not exist, skipping removal")


def reverse_safe_remove_fields_from_payment(apps, schema_editor):
    """Reverse operation - do nothing (fields are already removed)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0037_alter_servicefeebilling_unique_together_and_more'),
    ]

    operations = [
        # Safely remove fields from ServiceFeePayment (check if they exist)
        migrations.RunPython(safe_remove_fields_from_payment, reverse_safe_remove_fields_from_payment),
        
        # Update state to reflect the fields are removed
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Already handled by RunPython above
            state_operations=[
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='billing_reference',
                ),
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='notes',
                ),
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='payment_date',
                ),
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='payment_method_rel',
                ),
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='receipt_id',
                ),
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='reference_number',
                ),
            ],
        ),
    ]
