# Generated by Django 5.2.7 on 2025-11-06 15:36

import django.db.models.deletion
from django.db import migrations, models


def safe_add_servicefeepaymentid(apps, schema_editor):
    """Safely add servicefeepaymentid_id field only if it doesn't exist"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Determine the actual table name
            table_names = ['service_fee_payment_details', 'service_fee_billings']
            actual_table_name = None
            
            for table_name in table_names:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                """, [table_name])
                if cursor.fetchone()[0] > 0:
                    actual_table_name = table_name
                    break
            
            if not actual_table_name:
                print("Neither service_fee_payment_details nor service_fee_billings table exists, skipping")
                return
            
            # If table is still named service_fee_billings, rename it to service_fee_payment_details
            if actual_table_name == 'service_fee_billings':
                try:
                    cursor.execute("ALTER TABLE `service_fee_billings` RENAME TO `service_fee_payment_details`")
                    actual_table_name = 'service_fee_payment_details'
                    print("Renamed service_fee_billings to service_fee_payment_details")
                except Exception as e:
                    print(f"Could not rename table (may already be renamed): {e}")
            
            print(f"Using table: {actual_table_name}")
            
            # Check if the column exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'servicefeepaymentid_id'
            """, [actual_table_name])
            column_exists = cursor.fetchone()[0] > 0
            
            if not column_exists:
                cursor.execute(f"""
                    ALTER TABLE `{actual_table_name}` 
                    ADD COLUMN servicefeepaymentid_id BIGINT NULL
                    COMMENT 'Related payment transaction'
                """)
                # Add foreign key constraint separately if it doesn't exist
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.TABLE_CONSTRAINTS 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                    AND CONSTRAINT_NAME LIKE %s
                """, [actual_table_name, '%servicefeepaymentid%'])
                fk_exists = cursor.fetchone()[0] > 0
                if not fk_exists:
                    try:
                        # Use string formatting for table name (safe since it's validated)
                        cursor.execute(f"""
                            ALTER TABLE `{actual_table_name}` 
                            ADD CONSTRAINT service_fee_payment_details_servicefeepaymentid_id_fk
                            FOREIGN KEY (servicefeepaymentid_id) REFERENCES service_fee_management_servicefeepayment(id)
                            ON DELETE SET NULL
                        """)
                        print("Added servicefeepaymentid_id foreign key constraint")
                    except Exception as e:
                        print(f"Could not add foreign key constraint (may already exist): {e}")
                print("Added servicefeepaymentid_id column")
            else:
                print("Column servicefeepaymentid_id already exists, skipping")


def reverse_safe_add_servicefeepaymentid(apps, schema_editor):
    """Reverse operation - do nothing (keep the field)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0038_alter_servicefeebilling_unique_together_and_more'),
    ]

    operations = [
        # Handle all database operations in Python (including table rename and field addition)
        migrations.RunPython(safe_add_servicefeepaymentid, reverse_safe_add_servicefeepaymentid),
        # Update state only (no database introspection)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # All handled by RunPython above
            state_operations=[
                # Ensure model table name is correct
                migrations.AlterModelTable(
                    name='servicefeebilling',
                    table='service_fee_payment_details',
                ),
                # Update state to reflect field exists
                migrations.AddField(
                    model_name='servicefeebilling',
                    name='servicefeepaymentid',
                    field=models.ForeignKey(blank=True, help_text='Related payment transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_records', to='service_fee_management.servicefeepayment'),
                ),
            ],
        ),
    ]
