# Generated by Django 5.2.7 on 2025-11-06 15:38

import django.db.models.deletion
from django.db import migrations, models


def fix_orphaned_foreign_keys(apps, schema_editor):
    """
    Fix orphaned foreign key references before altering the field
    Set invalid servicefeepaymentid_id to NULL or a valid default
    """
    if schema_editor.connection.vendor != 'mysql':
        return
    
    with schema_editor.connection.cursor() as cursor:
        try:
            # Determine the actual table name
            table_names = ['service_fee_payment_details', 'service_fee_billings']
            actual_table_name = None
            
            for table_name in table_names:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                """, [table_name])
                if cursor.fetchone()[0] > 0:
                    actual_table_name = table_name
                    break
            
            if not actual_table_name:
                print("Neither service_fee_payment_details nor service_fee_billings table exists, skipping orphan fix")
                return
            
            print(f"Using table: {actual_table_name}")
            
            # Check if column exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'servicefeepaymentid_id'
            """, [actual_table_name])
            if cursor.fetchone()[0] == 0:
                print("Column servicefeepaymentid_id does not exist, skipping orphan fix")
                return
            
            # Find a valid default payment ID
            cursor.execute("""
                SELECT id FROM service_fee_management_servicefeepayment 
                ORDER BY id ASC LIMIT 1
            """)
            result = cursor.fetchone()
            default_payment_id = result[0] if result else 29
            
            if not default_payment_id:
                print("No valid payment ID found, cannot fix orphaned references")
                return
            
            # First, update NULL values to default
            cursor.execute(f"""
                UPDATE `{actual_table_name}` 
                SET servicefeepaymentid_id = %s
                WHERE servicefeepaymentid_id IS NULL
            """, [default_payment_id])
            null_fixed = cursor.rowcount
            
            # Then, update orphaned (invalid) records to use the default payment ID
            # Use a subquery to avoid the "You can't specify target table for update in FROM clause" error
            cursor.execute(f"""
                UPDATE `{actual_table_name}` b1
                LEFT JOIN service_fee_management_servicefeepayment p 
                ON b1.servicefeepaymentid_id = p.id
                SET b1.servicefeepaymentid_id = %s
                WHERE b1.servicefeepaymentid_id IS NOT NULL 
                AND p.id IS NULL
            """, [default_payment_id])
            
            orphaned_fixed = cursor.rowcount
            total_fixed = null_fixed + orphaned_fixed
            
            if total_fixed > 0:
                print(f"Fixed {null_fixed} NULL values and {orphaned_fixed} orphaned foreign key references (total: {total_fixed})")
            else:
                print("No orphaned or NULL foreign key references found")
                
        except Exception as e:
            print(f"Error fixing orphaned foreign keys: {e}")
            # Continue migration even if this fails


def reverse_fix_orphaned_foreign_keys(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0039_alter_servicefeebilling_unique_together_and_more'),
    ]

    operations = [
        # Fix orphaned foreign keys before altering the field
        migrations.RunPython(fix_orphaned_foreign_keys, reverse_fix_orphaned_foreign_keys),
        
        migrations.AlterField(
            model_name='servicefeebilling',
            name='servicefeepaymentid',
            field=models.ForeignKey(default=29, help_text='Related payment transaction', on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='service_fee_management.servicefeepayment'),
        ),
    ]
