# Generated by Django 5.2.7 on 2025-11-06 15:45

from django.db import migrations, models


def safe_move_due_date(apps, schema_editor):
    """Safely move due_date from billing to payment"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Determine the actual billing table name
            table_names = ['service_fee_payment_details', 'service_fee_billings']
            actual_table_name = None
            
            for table_name in table_names:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                """, [table_name])
                if cursor.fetchone()[0] > 0:
                    actual_table_name = table_name
                    break
            
            if not actual_table_name:
                print("Neither service_fee_payment_details nor service_fee_billings table exists, skipping")
                return
            
            print(f"Using billing table: {actual_table_name}")
            
            # Check if due_date exists in billing table
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'due_date'
            """, [actual_table_name])
            billing_due_date_exists = cursor.fetchone()[0] > 0
            
            # Check if due_date exists in payment table
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'due_date'
            """)
            payment_due_date_exists = cursor.fetchone()[0] > 0
            
            # Remove from billing if exists
            if billing_due_date_exists:
                cursor.execute(f"ALTER TABLE `{actual_table_name}` DROP COLUMN due_date")
                print("Removed due_date from billing")
            else:
                print("due_date does not exist in billing, skipping removal")
            
            # Add to payment if doesn't exist
            if not payment_due_date_exists:
                cursor.execute("""
                    ALTER TABLE service_fee_management_servicefeepayment 
                    ADD COLUMN due_date DATE DEFAULT '2024-01-01'
                    COMMENT 'Service fee due date'
                """)
                print("Added due_date to payment")
            else:
                print("due_date already exists in payment, skipping")


def reverse_safe_move_due_date(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0040_alter_servicefeebilling_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(safe_move_due_date, reverse_safe_move_due_date),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='servicefeebilling',
                    name='due_date',
                ),
                migrations.AddField(
                    model_name='servicefeepayment',
                    name='due_date',
                    field=models.DateField(default='2024-01-01', help_text='Service fee due date'),
                ),
            ],
        ),
    ]
