# Generated by Django 5.2.7 on 2025-11-06 16:46

from django.db import migrations


def safe_remove_billing_field(apps, schema_editor):
    """Safely remove billing field from payment - drop foreign key first"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check if column exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'billing_id'
            """)
            billing_id_exists = cursor.fetchone()[0] > 0
            
            if billing_id_exists:
                # Find and drop foreign key constraint first
                cursor.execute("""
                    SELECT CONSTRAINT_NAME
                    FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                    AND COLUMN_NAME = 'billing_id'
                    AND REFERENCED_TABLE_NAME IS NOT NULL
                """)
                fk_result = cursor.fetchone()
                
                if fk_result:
                    fk_name = fk_result[0]
                    try:
                        cursor.execute(f"ALTER TABLE `service_fee_management_servicefeepayment` DROP FOREIGN KEY `{fk_name}`")
                        print(f"Dropped foreign key constraint: {fk_name}")
                    except Exception as e:
                        print(f"Could not drop foreign key {fk_name}: {e}")
                
                # Now drop the column
                try:
                    cursor.execute("ALTER TABLE service_fee_management_servicefeepayment DROP COLUMN billing_id")
                    print("Removed billing_id from payment")
                except Exception as e:
                    print(f"Could not drop billing_id column: {e}")
            else:
                print("billing_id does not exist in payment, skipping removal")


def reverse_safe_remove_billing_field(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0041_alter_servicefeebilling_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(safe_remove_billing_field, reverse_safe_remove_billing_field),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='billing',
                ),
            ],
        ),
    ]
