# Generated by Django 5.2.7 on 2025-11-08 17:51

import django.core.validators
from django.db import migrations, models


def safe_add_remaining_amount(apps, schema_editor):
    """Safely add remaining_amount field only if it doesn't exist"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'remaining_amount'
            """)
            column_exists = cursor.fetchone()[0] > 0
            
            if not column_exists:
                cursor.execute("""
                    ALTER TABLE service_fee_management_servicefeepayment 
                    ADD COLUMN remaining_amount DECIMAL(10,2) DEFAULT 0
                    COMMENT 'Remaining amount after this payment'
                """)
                print("Added remaining_amount column")
            else:
                print("Column remaining_amount already exists, skipping")


def reverse_safe_add_remaining_amount(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0042_alter_servicefeebilling_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(safe_add_remaining_amount, reverse_safe_add_remaining_amount),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='servicefeepayment',
                    name='remaining_amount',
                    field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount after this payment', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
                ),
            ],
        ),
    ]
