# Generated by Django 5.2.7 on 2025-11-08 17:59

from django.db import migrations


def safe_remove_remaining_amount(apps, schema_editor):
    """Safely remove remaining_amount from billing"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Determine the actual table name
            table_names = ['service_fee_payment_details', 'service_fee_billings']
            actual_table_name = None
            
            for table_name in table_names:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                """, [table_name])
                if cursor.fetchone()[0] > 0:
                    actual_table_name = table_name
                    break
            
            if not actual_table_name:
                print("Neither service_fee_payment_details nor service_fee_billings table exists, skipping")
                return
            
            print(f"Using table: {actual_table_name}")
            
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = %s
                AND COLUMN_NAME = 'remaining_amount'
            """, [actual_table_name])
            column_exists = cursor.fetchone()[0] > 0
            
            if column_exists:
                cursor.execute(f"ALTER TABLE `{actual_table_name}` DROP COLUMN remaining_amount")
                print("Removed remaining_amount from billing")
            else:
                print("remaining_amount does not exist in billing, skipping removal")


def reverse_safe_remove_remaining_amount(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0043_add_remaining_amount_to_payment'),
    ]

    operations = [
        migrations.RunPython(safe_remove_remaining_amount, reverse_safe_remove_remaining_amount),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='servicefeebilling',
                    name='remaining_amount',
                ),
            ],
        ),
    ]
