# Generated by Django 5.2.7 on 2025-11-09 15:27

from django.db import migrations, models


def safe_move_transaction_id(apps, schema_editor):
    """
    Safely move transaction_id from payment to billing
    First remove from payment, then add to billing with unique values
    """
    if schema_editor.connection.vendor != 'mysql':
        return
    
    with schema_editor.connection.cursor() as cursor:
        try:
            # Step 1: Remove transaction_id from payment table if it exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                AND COLUMN_NAME = 'transaction_id'
            """)
            if cursor.fetchone()[0] > 0:
                # Check for foreign key constraint first
                cursor.execute("""
                    SELECT CONSTRAINT_NAME
                    FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = 'service_fee_management_servicefeepayment'
                    AND COLUMN_NAME = 'transaction_id'
                    AND REFERENCED_TABLE_NAME IS NOT NULL
                """)
                fk_result = cursor.fetchone()
                if fk_result:
                    try:
                        cursor.execute(f"ALTER TABLE `service_fee_management_servicefeepayment` DROP FOREIGN KEY `{fk_result[0]}`")
                        print(f"Dropped foreign key: {fk_result[0]}")
                    except Exception as e:
                        print(f"Could not drop foreign key: {e}")
                
                cursor.execute("ALTER TABLE service_fee_management_servicefeepayment DROP COLUMN transaction_id")
                print("Removed transaction_id from payment table")
            
            # Step 2: Determine billing table name and add transaction_id
            table_names = ['service_fee_payment_details', 'service_fee_billings']
            actual_billing_table = None
            
            for table_name in table_names:
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM INFORMATION_SCHEMA.TABLES 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                """, [table_name])
                if cursor.fetchone()[0] > 0:
                    actual_billing_table = table_name
                    break
            
            if actual_billing_table:
                print(f"Using billing table: {actual_billing_table}")
                cursor.execute("""
                    SELECT COUNT(*) 
                    FROM information_schema.COLUMNS 
                    WHERE TABLE_SCHEMA = DATABASE() 
                    AND TABLE_NAME = %s
                    AND COLUMN_NAME = 'transaction_id'
                """, [actual_billing_table])
                if cursor.fetchone()[0] == 0:
                    # Add column without UNIQUE constraint first
                    cursor.execute(f"""
                        ALTER TABLE `{actual_billing_table}` 
                        ADD COLUMN transaction_id VARCHAR(100) DEFAULT 'TXN-LEGACY'
                        COMMENT 'Unique transaction identifier for each payment'
                    """)
                    print("Added transaction_id column to billing table")
                    
                    # Update existing rows to have unique values
                    cursor.execute(f"""
                        UPDATE `{actual_billing_table}` 
                        SET transaction_id = CONCAT('TXN-LEGACY-', id)
                        WHERE transaction_id = 'TXN-LEGACY' OR transaction_id IS NULL
                    """)
                    print("Updated existing transaction_id values to be unique")
                    
                    # Now add UNIQUE constraint
                    try:
                        cursor.execute(f"""
                            ALTER TABLE `{actual_billing_table}` 
                            ADD UNIQUE INDEX transaction_id_unique (transaction_id)
                        """)
                        print("Added UNIQUE constraint to transaction_id")
                    except Exception as e:
                        print(f"Could not add UNIQUE constraint to transaction_id (may already exist): {e}")
                else:
                    print("Column transaction_id already exists in billing table, skipping")
            else:
                print("Billing table not found, skipping transaction_id addition")
                
        except Exception as e:
            print(f"Error in safe_move_transaction_id: {e}")


def reverse_safe_move_transaction_id(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0044_remove_remaining_amount_from_billing'),
    ]

    operations = [
        # Safely move transaction_id using Python function
        migrations.RunPython(safe_move_transaction_id, reverse_safe_move_transaction_id),
        
        # Update state to reflect the changes
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Already handled by RunPython above
            state_operations=[
                migrations.RemoveField(
                    model_name='servicefeepayment',
                    name='transaction_id',
                ),
                migrations.AddField(
                    model_name='servicefeebilling',
                    name='transaction_id',
                    field=models.CharField(default='TXN-LEGACY', help_text='Unique transaction identifier for each payment', max_length=100, unique=True),
                ),
            ],
        ),
    ]
