# Generated by Django 5.2.7 on 2025-11-13 14:30

import django.db.models.deletion
from django.db import migrations, models


def safe_create_schedule_table(apps, schema_editor):
    """Safely create ServiceFeeGenerationSchedule table only if it doesn't exist"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check if table exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.TABLES 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_generation_schedules'
            """)
            table_exists = cursor.fetchone()[0] > 0
            
            if table_exists:
                print("Table service_fee_generation_schedules already exists, skipping creation")
                return
            
            # Table doesn't exist, create it manually
            print("Creating table service_fee_generation_schedules")
            cursor.execute("""
                CREATE TABLE service_fee_generation_schedules (
                    id BIGINT AUTO_INCREMENT PRIMARY KEY,
                    schedule_name VARCHAR(200) NOT NULL,
                    unit_ids VARCHAR(500) NULL,
                    generation_day INT NOT NULL DEFAULT 1,
                    generation_hour INT NOT NULL DEFAULT 14,
                    generation_minute INT NOT NULL DEFAULT 15,
                    status VARCHAR(20) NOT NULL DEFAULT 'active',
                    last_executed DATETIME(6) NULL,
                    last_execution_result TEXT NULL,
                    created_at DATETIME(6) NOT NULL,
                    updated_at DATETIME(6) NOT NULL,
                    created_by_id BIGINT NULL,
                    service_fee_id BIGINT NULL,
                    tower_id BIGINT NULL,
                    FOREIGN KEY (created_by_id) REFERENCES user_member(id) ON DELETE SET NULL,
                    FOREIGN KEY (service_fee_id) REFERENCES service_fee_servicefee(id) ON DELETE CASCADE,
                    FOREIGN KEY (tower_id) REFERENCES towers_tower(id) ON DELETE CASCADE
                )
            """)
            print("Table service_fee_generation_schedules created successfully")


def reverse_safe_create_schedule_table(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0015_alter_servicefee_service_fee_date'),
        ('service_fee_management', '0045_move_transaction_id_to_billing'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicefeebilling',
            unique_together=set(),
        ),
        # Use SeparateDatabaseAndState to conditionally create table
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_create_schedule_table, reverse_safe_create_schedule_table),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ServiceFeeGenerationSchedule',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('schedule_name', models.CharField(help_text="Name for this schedule (e.g., 'Tower 1 Monthly Generation')", max_length=200)),
                        ('unit_ids', models.CharField(blank=True, help_text="Comma-separated unit IDs (e.g., '12604,12605') or leave empty for all units", max_length=500, null=True)),
                        ('generation_day', models.IntegerField(default=1, help_text='Day of month to generate (1-31, e.g., 1 for 1st, 2 for 2nd)')),
                        ('generation_hour', models.IntegerField(default=14, help_text='Hour to generate (0-23, e.g., 14 for 2 PM)')),
                        ('generation_minute', models.IntegerField(default=15, help_text='Minute to generate (0-59, e.g., 15 for :15)')),
                        ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', help_text='Schedule status', max_length=20)),
                        ('last_executed', models.DateTimeField(blank=True, help_text='Last time this schedule was executed', null=True)),
                        ('last_execution_result', models.TextField(blank=True, help_text='Result of last execution', null=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedules', to='user.member')),
                        ('service_fee', models.ForeignKey(blank=True, help_text='Specific service fee (leave empty for all active service fees)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_schedules', to='service_fee.servicefee')),
                        ('tower', models.ForeignKey(blank=True, help_text='Specific tower for this schedule (leave empty for all towers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_schedules', to='towers.tower')),
                    ],
                    options={
                        'verbose_name': 'Service Fee Generation Schedule',
                        'verbose_name_plural': 'Service Fee Generation Schedules',
                        'db_table': 'service_fee_generation_schedules',
                        'ordering': ['tower_id', 'generation_day', 'generation_hour', 'generation_minute'],
                    },
                ),
            ],
        ),
    ]
