# Generated by Django 5.2.7 on 2025-11-15 14:52

from django.db import migrations, models


def safe_add_recurring_fields(apps, schema_editor):
    """Safely add recurring_frequency and is_recurring fields only if they don't exist"""
    if schema_editor.connection.vendor == 'mysql':
        with schema_editor.connection.cursor() as cursor:
            # Check if is_recurring exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_generation_schedules'
                AND COLUMN_NAME = 'is_recurring'
            """)
            is_recurring_exists = cursor.fetchone()[0] > 0
            
            if not is_recurring_exists:
                cursor.execute("""
                    ALTER TABLE service_fee_generation_schedules 
                    ADD COLUMN is_recurring BOOLEAN DEFAULT TRUE
                    COMMENT 'Whether this schedule is recurring'
                """)
                print("Added is_recurring column")
            else:
                print("Column is_recurring already exists, skipping")
            
            # Check if recurring_frequency exists
            cursor.execute("""
                SELECT COUNT(*) 
                FROM information_schema.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_generation_schedules'
                AND COLUMN_NAME = 'recurring_frequency'
            """)
            recurring_frequency_exists = cursor.fetchone()[0] > 0
            
            if not recurring_frequency_exists:
                cursor.execute("""
                    ALTER TABLE service_fee_generation_schedules 
                    ADD COLUMN recurring_frequency VARCHAR(20) DEFAULT 'monthly'
                    COMMENT 'How often to generate service fees (daily, weekly, monthly)'
                """)
                print("Added recurring_frequency column")
            else:
                print("Column recurring_frequency already exists, skipping")


def reverse_safe_add_recurring_fields(apps, schema_editor):
    """Reverse operation - do nothing"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0046_add_service_fee_generation_schedule'),
    ]

    operations = [
        # Safely add fields using Python function
        migrations.RunPython(safe_add_recurring_fields, reverse_safe_add_recurring_fields),
        # Update state to reflect fields exist
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Already handled by RunPython above
            state_operations=[
                migrations.AddField(
                    model_name='servicefeegenerationschedule',
                    name='is_recurring',
                    field=models.BooleanField(default=True, help_text='Whether this schedule is recurring'),
                ),
                migrations.AddField(
                    model_name='servicefeegenerationschedule',
                    name='recurring_frequency',
                    field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', help_text='How often to generate service fees (daily, weekly, monthly)', max_length=20),
                ),
            ],
        ),
    ]

