# Generated by Django 5.2.8 on 2025-11-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0047_add_recurring_frequency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeebilling',
            name='due_date',
            field=models.DateField(blank=True, help_text='Service fee due date', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='audience',
            field=models.CharField(choices=[('All Towers', 'All Towers'), ('All Residents', 'All Residents'), ('Specific Tower', 'Specific Tower'), ('Specific Units', 'Specific Units'), ('Specific Resident', 'Specific Resident'), ('Due Only', 'Due Only'), ('Overdue Only', 'Overdue Only'), ('Paid Only', 'Paid Only')], default='All Towers', max_length=50),
        ),
    ]
