# Generated by Django 5.2.7 on 2025-11-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0048_alter_reminder_audience'),
        ('service_fee_management', '0048_servicefeebilling_due_date_alter_reminder_audience'),
    ]

    operations = [
    ]
