# Generated by Django 5.2.7 on 2025-11-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0049_merge_20251123_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCommerzTransactionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, help_text='SSLCommerz transaction ID', max_length=100, unique=True)),
                ('payment_ids', models.TextField(help_text='Comma-separated payment IDs')),
                ('unit_id', models.IntegerField(help_text='Unit ID')),
                ('service_fee_id', models.IntegerField(help_text='Service Fee ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this mapping expires (1 hour from creation)')),
            ],
            options={
                'db_table': 'service_fee_sslcommerz_transaction_mapping',
                'ordering': ['-created_at'],
            },
        ),
    ]
