# Generated by Django 5.2.7 on 2025-12-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0050_sslcommerztransactionmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='last_sent_timing',
            field=models.CharField(blank=True, help_text="Last timing rule that was sent (e.g., '1 day before due at 10:00')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='send_when',
            field=models.JSONField(default=list, help_text="List of timing options with specific times. Format: [{'timing': '1 day before due', 'times': ['10:00', '15:00']}]"),
        ),
    ]
