# Generated by assistant - add send_when_type and send_when_day to Reminder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0051_add_reminder_time_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='send_when_type',
            field=models.CharField(blank=True, choices=[('before', 'Before Due'), ('after', 'After Due'), ('due', 'On Due Date'), ('specific', 'Specific Day')], help_text='Quick option type: before/after/due/specific', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='send_when_day',
            field=models.IntegerField(blank=True, help_text='Numeric day value for quick option (e.g., 1)', null=True),
        ),
    ]
