# Generated by Django 5.2.7 on 2025-12-07 13:25

from django.db import migrations, models
import json


def convert_varchar_to_json(apps, schema_editor):
    """Convert existing comma-separated varchar data to JSON arrays"""
    Reminder = apps.get_model('service_fee_management', 'Reminder')
    
    for reminder in Reminder.objects.all():
        if reminder.specific_target:
            # Check if it's already JSON (shouldn't be, but be safe)
            try:
                json.loads(reminder.specific_target)
                # Already valid JSON, skip
                continue
            except (json.JSONDecodeError, TypeError):
                pass
            
            # Convert comma-separated string to list of integers
            if ',' in str(reminder.specific_target):
                # Multiple IDs: "6365,6366,6367" -> [6365, 6366, 6367]
                ids = [int(id_str.strip()) for id_str in str(reminder.specific_target).split(',') if id_str.strip().isdigit()]
                reminder.specific_target = json.dumps(ids)
            elif str(reminder.specific_target).isdigit():
                # Single ID: "6365" -> [6365]
                reminder.specific_target = json.dumps([int(reminder.specific_target)])
            else:
                # Invalid data, set to null
                reminder.specific_target = None
            
            reminder.save(update_fields=['specific_target'])


def reverse_json_to_varchar(apps, schema_editor):
    """Reverse: Convert JSON arrays back to comma-separated strings"""
    Reminder = apps.get_model('service_fee_management', 'Reminder')
    
    for reminder in Reminder.objects.all():
        if reminder.specific_target:
            try:
                data = json.loads(reminder.specific_target)
                if isinstance(data, list):
                    # [6365, 6366, 6367] -> "6365,6366,6367"
                    reminder.specific_target = ','.join(map(str, data))
                    reminder.save(update_fields=['specific_target'])
            except (json.JSONDecodeError, TypeError):
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0053_add_payment_status_send_when_times'),
    ]

    operations = [
        # Step 1: Convert existing varchar data to JSON format (but still stored as varchar)
        migrations.RunPython(convert_varchar_to_json, reverse_json_to_varchar),
        
        # Step 2: Change column type to JSON
        migrations.AlterField(
            model_name='reminder',
            name='specific_target',
            field=models.JSONField(null=True, blank=True, help_text='JSON array of specific target IDs (towers, units, or residents)'),
        ),
    ]
