# Generated by Django 5.2.7 on 2025-12-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0054_change_specific_target_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='tower_id',
            field=models.JSONField(blank=True, help_text='JSON array of tower IDs for filtering reminders', null=True),
        ),
    ]
