# Generated by Django 5.2.7 on 2025-12-07 13:58

from django.db import migrations, models


def convert_sendwhen_to_json(apps, schema_editor):
    """Convert existing varchar/int send_when data to JSON arrays"""
    Reminder = apps.get_model('service_fee_management', 'Reminder')
    
    for reminder in Reminder.objects.all():
        # Convert send_when_type: if it's a string, wrap it in a list
        if reminder.send_when_type and isinstance(reminder.send_when_type, str):
            reminder.send_when_type = [reminder.send_when_type]
        elif not reminder.send_when_type:
            reminder.send_when_type = []
            
        # Convert send_when_day: if it's an int, wrap it in a list
        if reminder.send_when_day is not None and isinstance(reminder.send_when_day, int):
            reminder.send_when_day = [reminder.send_when_day]
        elif reminder.send_when_day is None:
            reminder.send_when_day = []
            
        reminder.save()


def reverse_sendwhen_to_varchar_int(apps, schema_editor):
    """Reverse conversion: take first element from arrays"""
    Reminder = apps.get_model('service_fee_management', 'Reminder')
    
    for reminder in Reminder.objects.all():
        # Convert send_when_type: take first element if list
        if reminder.send_when_type and isinstance(reminder.send_when_type, list):
            reminder.send_when_type = reminder.send_when_type[0] if len(reminder.send_when_type) > 0 else None
            
        # Convert send_when_day: take first element if list
        if reminder.send_when_day and isinstance(reminder.send_when_day, list):
            reminder.send_when_day = reminder.send_when_day[0] if len(reminder.send_when_day) > 0 else None
            
        reminder.save()


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0055_add_tower_id_to_reminder'),
    ]

    operations = [
        # First, run the data conversion while columns are still varchar/int
        migrations.RunPython(convert_sendwhen_to_json, reverse_sendwhen_to_varchar_int),
        # Then alter the field types to JSON
        migrations.AlterField(
            model_name='reminder',
            name='send_when_day',
            field=models.JSONField(blank=True, help_text='JSON array of day values corresponding to send_when_type', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='send_when_type',
            field=models.JSONField(blank=True, help_text="JSON array of quick option types (e.g., ['before_due', 'after_due'])", null=True),
        ),
    ]
