# Generated by Django 5.2.7 on 2025-12-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0056_convert_sendwhen_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='send_when_type',
            field=models.JSONField(blank=True, help_text="JSON array of quick option types (e.g., ['before_due', 'after_due', 'specific'])", null=True),
        ),
    ]
