# Generated by Django 5.2.7 on 2025-12-08 10:26

import django.db.models.deletion
from django.db import migrations, models, connection


def create_tables_if_not_exist(apps, schema_editor):
    """Create tables only if they don't already exist"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_schema = DATABASE()
        """)
        existing_tables = {row[0] for row in cursor.fetchall()}
        
        # Check if parent table exists
        if 'service_fee_reminders' not in existing_tables:
            # Parent table doesn't exist, skip creating child tables
            return
        
        # Create ReminderPaymentStatus table
        if 'service_fee_reminder_payment_statuses' not in existing_tables:
            cursor.execute("""
                CREATE TABLE `service_fee_reminder_payment_statuses` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `status` varchar(20) NOT NULL,
                    `created_at` datetime(6) NOT NULL,
                    `reminder_id` bigint NOT NULL,
                    PRIMARY KEY (`id`),
                    UNIQUE KEY `service_fee_reminder_reminder_id_status_1c8a8a8a_uniq` (`reminder_id`,`status`),
                    CONSTRAINT `service_fee_reminde_reminder_id_1c8a8a8a_fk_service_f` FOREIGN KEY (`reminder_id`) REFERENCES `service_fee_reminders` (`id`)
                ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
            """)
        
        # Create ReminderTower table
        if 'service_fee_reminder_towers' not in existing_tables:
            cursor.execute("""
                CREATE TABLE `service_fee_reminder_towers` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `created_at` datetime(6) NOT NULL,
                    `reminder_id` bigint NOT NULL,
                    `tower_id` bigint NOT NULL,
                    PRIMARY KEY (`id`),
                    UNIQUE KEY `service_fee_reminder_t_reminder_id_tower_id_a1b2c3d4_uniq` (`reminder_id`,`tower_id`),
                    KEY `service_fee_reminde_tower_id_a1b2c3d4_fk_towers_to` (`tower_id`),
                    CONSTRAINT `service_fee_reminde_reminder_id_a1b2c3d4_fk_service_f` FOREIGN KEY (`reminder_id`) REFERENCES `service_fee_reminders` (`id`),
                    CONSTRAINT `service_fee_reminde_tower_id_a1b2c3d4_fk_towers_to` FOREIGN KEY (`tower_id`) REFERENCES `towers_tower` (`id`)
                ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
            """)
        
        # Create ReminderSpecificTarget table
        if 'service_fee_reminder_specific_targets' not in existing_tables:
            cursor.execute("""
                CREATE TABLE `service_fee_reminder_specific_targets` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `target_type` varchar(20) NOT NULL,
                    `target_id` int NOT NULL,
                    `created_at` datetime(6) NOT NULL,
                    `reminder_id` bigint NOT NULL,
                    PRIMARY KEY (`id`),
                    UNIQUE KEY `service_fee_reminder_s_reminder_id_target_type_b3c4d5e6_uniq` (`reminder_id`,`target_type`,`target_id`),
                    KEY `service_fee_reminde_1449a2_idx` (`reminder_id`,`target_type`),
                    KEY `service_fee_target__3828bc_idx` (`target_type`,`target_id`),
                    CONSTRAINT `service_fee_reminde_reminder_id_b3c4d5e6_fk_service_f` FOREIGN KEY (`reminder_id`) REFERENCES `service_fee_reminders` (`id`)
                ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
            """)
        
        # Create ReminderTiming table
        if 'service_fee_reminder_timings' not in existing_tables:
            cursor.execute("""
                CREATE TABLE `service_fee_reminder_timings` (
                    `id` bigint NOT NULL AUTO_INCREMENT,
                    `timing_type` varchar(20) NOT NULL,
                    `day_offset` int NOT NULL,
                    `timing_label` varchar(255) NOT NULL,
                    `send_time` time(6) NOT NULL,
                    `created_at` datetime(6) NOT NULL,
                    `updated_at` datetime(6) NOT NULL,
                    `reminder_id` bigint NOT NULL,
                    PRIMARY KEY (`id`),
                    KEY `service_fee_reminde_76a960_idx` (`reminder_id`,`timing_type`),
                    KEY `service_fee_reminde_1a889c_idx` (`reminder_id`,`day_offset`),
                    CONSTRAINT `service_fee_reminde_reminder_id_c5d6e7f8_fk_service_f` FOREIGN KEY (`reminder_id`) REFERENCES `service_fee_reminders` (`id`)
                ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0057_update_sendwhen_choices'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ReminderPaymentStatus',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('status', models.CharField(choices=[('All', 'All'), ('Paid', 'Paid'), ('Due', 'Due'), ('Overdue', 'Overdue'), ('Partial', 'Partial')], help_text='Payment status to filter', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('reminder', models.ForeignKey(help_text='Parent reminder', on_delete=django.db.models.deletion.CASCADE, related_name='payment_statuses', to='service_fee_management.reminder')),
                    ],
                    options={
                        'db_table': 'service_fee_reminder_payment_statuses',
                        'ordering': ['status'],
                        'unique_together': {('reminder', 'status')},
                    },
                ),
                migrations.CreateModel(
                    name='ReminderSpecificTarget',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('target_type', models.CharField(choices=[('tower', 'Tower'), ('unit', 'Unit'), ('resident', 'Resident')], help_text='Type of target', max_length=20)),
                        ('target_id', models.IntegerField(help_text='ID of the target (tower_id, unit_id, or resident_id)')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('reminder', models.ForeignKey(help_text='Parent reminder', on_delete=django.db.models.deletion.CASCADE, related_name='specific_targets', to='service_fee_management.reminder')),
                    ],
                    options={
                        'db_table': 'service_fee_reminder_specific_targets',
                        'ordering': ['target_type', 'target_id'],
                        'indexes': [models.Index(fields=['reminder', 'target_type'], name='service_fee_reminde_1449a2_idx'), models.Index(fields=['target_type', 'target_id'], name='service_fee_target__3828bc_idx')],
                        'unique_together': {('reminder', 'target_type', 'target_id')},
                    },
                ),
                migrations.CreateModel(
                    name='ReminderTiming',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('timing_type', models.CharField(choices=[('before_due', 'Before Due'), ('after_due', 'After Due'), ('on_due', 'On Due Date'), ('specific', 'Specific Day')], help_text='Type of timing rule', max_length=20)),
                        ('day_offset', models.IntegerField(default=0, help_text="Number of days (0 for 'on_due', N for before/after)")),
                        ('timing_label', models.CharField(help_text="Human-readable timing description (e.g., '3 days before due')", max_length=255)),
                        ('send_time', models.TimeField(help_text='Time to send reminder (HH:MM)')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('reminder', models.ForeignKey(help_text='Parent reminder', on_delete=django.db.models.deletion.CASCADE, related_name='timing_rules', to='service_fee_management.reminder')),
                    ],
                    options={
                        'db_table': 'service_fee_reminder_timings',
                        'ordering': ['timing_type', 'day_offset', 'send_time'],
                        'indexes': [models.Index(fields=['reminder', 'timing_type'], name='service_fee_reminde_76a960_idx'), models.Index(fields=['reminder', 'day_offset'], name='service_fee_reminde_1a889c_idx')],
                    },
                ),
                migrations.CreateModel(
                    name='ReminderTower',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('reminder', models.ForeignKey(help_text='Parent reminder', on_delete=django.db.models.deletion.CASCADE, related_name='reminder_towers', to='service_fee_management.reminder')),
                        ('tower', models.ForeignKey(help_text='Associated tower', on_delete=django.db.models.deletion.CASCADE, to='towers.tower')),
                    ],
                    options={
                        'db_table': 'service_fee_reminder_towers',
                        'ordering': ['tower__tower_name'],
                        'unique_together': {('reminder', 'tower')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    code=create_tables_if_not_exist,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
    ]
