# Generated by Django 5.2.7 on 2025-12-08 10:26

from django.db import migrations
from datetime import time


def migrate_json_data_to_tables(apps, schema_editor):
    """
    Migrate data from JSON columns to normalized tables:
    - send_when, send_when_type, send_when_day, send_when_times -> ReminderTiming
    - payment_status -> ReminderPaymentStatus
    - tower_id -> ReminderTower
    - specific_target -> ReminderSpecificTarget
    """
    Reminder = apps.get_model('service_fee_management', 'Reminder')
    ReminderTiming = apps.get_model('service_fee_management', 'ReminderTiming')
    ReminderPaymentStatus = apps.get_model('service_fee_management', 'ReminderPaymentStatus')
    ReminderTower = apps.get_model('service_fee_management', 'ReminderTower')
    ReminderSpecificTarget = apps.get_model('service_fee_management', 'ReminderSpecificTarget')
    Tower = apps.get_model('towers', 'Tower')
    
    for reminder in Reminder.objects.all():
        # Migrate timing data
        send_when_types = reminder.send_when_type or []
        send_when_days = reminder.send_when_day or []
        send_when_times = reminder.send_when_times or []
        
        # If no times specified, use default time of 10:00
        if not send_when_times:
            send_when_times = ['10:00']
        
        # Create timing rules for each type/day combination
        for i, timing_type in enumerate(send_when_types):
            day_offset = send_when_days[i] if i < len(send_when_days) else 0
            
            # Generate timing label
            if timing_type == 'on_due':
                timing_label = 'On due date'
            elif timing_type == 'before_due':
                timing_label = f"{day_offset} day{'s' if day_offset > 1 else ''} before due"
            elif timing_type == 'after_due':
                timing_label = f"{day_offset} day{'s' if day_offset > 1 else ''} after due"
            elif timing_type == 'specific':
                timing_label = f"Specific day: {day_offset}"
            else:
                timing_label = str(timing_type)
            
            # Create timing rule for each send time
            for send_time_str in send_when_times:
                try:
                    # Parse time string (HH:MM)
                    hour, minute = send_time_str.split(':')
                    send_time_obj = time(int(hour), int(minute))
                    
                    ReminderTiming.objects.create(
                        reminder=reminder,
                        timing_type=timing_type,
                        day_offset=day_offset,
                        timing_label=timing_label,
                        send_time=send_time_obj
                    )
                except (ValueError, AttributeError) as e:
                    print(f"Error parsing time '{send_time_str}' for reminder {reminder.id}: {e}")
                    # Use default time if parsing fails
                    ReminderTiming.objects.create(
                        reminder=reminder,
                        timing_type=timing_type,
                        day_offset=day_offset,
                        timing_label=timing_label,
                        send_time=time(10, 0)
                    )
        
        # Migrate payment status data
        payment_statuses = reminder.payment_status or []
        for status in payment_statuses:
            if status:  # Skip empty strings
                ReminderPaymentStatus.objects.create(
                    reminder=reminder,
                    status=status
                )
        
        # Migrate tower_id data
        tower_ids = reminder.tower_id or []
        for tower_id in tower_ids:
            try:
                tower = Tower.objects.get(id=tower_id)
                ReminderTower.objects.create(
                    reminder=reminder,
                    tower=tower
                )
            except Tower.DoesNotExist:
                print(f"Tower {tower_id} not found for reminder {reminder.id}")
        
        # Migrate specific_target data
        specific_targets = reminder.specific_target or []
        if specific_targets and reminder.audience:
            # Determine target type based on audience
            if 'Tower' in reminder.audience:
                target_type = 'tower'
            elif 'Unit' in reminder.audience:
                target_type = 'unit'
            elif 'Resident' in reminder.audience:
                target_type = 'resident'
            else:
                target_type = 'unit'  # Default fallback
            
            for target_id in specific_targets:
                ReminderSpecificTarget.objects.create(
                    reminder=reminder,
                    target_type=target_type,
                    target_id=target_id
                )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - clear the new tables
    (JSON data will remain intact in original columns)
    """
    ReminderTiming = apps.get_model('service_fee_management', 'ReminderTiming')
    ReminderPaymentStatus = apps.get_model('service_fee_management', 'ReminderPaymentStatus')
    ReminderTower = apps.get_model('service_fee_management', 'ReminderTower')
    ReminderSpecificTarget = apps.get_model('service_fee_management', 'ReminderSpecificTarget')
    
    ReminderTiming.objects.all().delete()
    ReminderPaymentStatus.objects.all().delete()
    ReminderTower.objects.all().delete()
    ReminderSpecificTarget.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0058_add_normalized_reminder_tables'),
    ]

    operations = [
        migrations.RunPython(migrate_json_data_to_tables, reverse_migration),
    ]
