# Generated by Django 5.2.7 on 2025-12-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0062_remove_send_when_times'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remindertiming',
            options={'ordering': ['timing_type', 'day_offset', 'id']},
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='send_when',
        ),
    ]
