# Generated by Django 5.2.7 on 2025-12-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0066_add_timing_tracking_to_reminderlog'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reminderlog',
            new_name='service_fee_reminde_b4b5eb_idx',
            old_name='service_fee_reminder_timing_idx',
        ),
        migrations.AlterField(
            model_name='reminderpaymentstatus',
            name='status',
            field=models.CharField(choices=[('all', 'All'), ('paid', 'Paid'), ('due', 'Due'), ('overdue', 'Overdue'), ('partial', 'Partial')], help_text='Payment status to filter', max_length=20),
        ),
        migrations.AddIndex(
            model_name='reminderlog',
            index=models.Index(fields=['reminder', 'unit', 'sent_at'], name='service_fee_reminde_b34e1a_idx'),
        ),
    ]
