# Generated by Django 5.2.7 on 2025-12-10 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0067_rename_service_fee_reminder_timing_idx_service_fee_reminde_b4b5eb_idx_and_more'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderlog',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reminders', to='user.member'),
        ),
    ]
