# Generated by Django 5.2.7 on 2025-12-13 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def safe_create_tables(apps, schema_editor):
    """Safely create bill upload tables if they don't exist."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check if bill_uploads table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
        """)
        table_exists = cursor.fetchone()[0] > 0
        
        if table_exists:
            # Tables already exist, skip creation
            return
        
        # Create BillUpload table
        cursor.execute("""
            CREATE TABLE `bill_uploads` (
                `id` bigint NOT NULL AUTO_INCREMENT,
                `upload_id` varchar(100) NOT NULL UNIQUE,
                `category` varchar(50) NOT NULL,
                `upload_month` int NOT NULL,
                `upload_year` int NOT NULL,
                `upload_method` varchar(20) NOT NULL DEFAULT 'manual',
                `is_active` tinyint(1) NOT NULL DEFAULT 1,
                `created_at` datetime(6) NOT NULL,
                `updated_at` datetime(6) NOT NULL,
                `created_by_id` bigint DEFAULT NULL,
                `service_fee_id` bigint NOT NULL,
                `tower_id` bigint NOT NULL,
                `updated_by_id` bigint DEFAULT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `service_fee_management_service_fee_id_tower_i_e1b8c8e5_uniq` (`service_fee_id`,`tower_id`,`upload_month`,`upload_year`),
                KEY `bill_uploads_created_by_id_idx` (`created_by_id`),
                KEY `bill_uploads_service_fee_id_idx` (`service_fee_id`),
                KEY `bill_uploads_tower_id_idx` (`tower_id`),
                KEY `bill_uploads_updated_by_id_idx` (`updated_by_id`),
                CONSTRAINT `bill_uploads_created_by_id_fk` FOREIGN KEY (`created_by_id`) REFERENCES `user_member` (`id`) ON DELETE SET NULL,
                CONSTRAINT `bill_uploads_service_fee_id_fk` FOREIGN KEY (`service_fee_id`) REFERENCES `service_fee_servicefee` (`id`) ON DELETE RESTRICT,
                CONSTRAINT `bill_uploads_tower_id_fk` FOREIGN KEY (`tower_id`) REFERENCES `towers_tower` (`id`) ON DELETE RESTRICT,
                CONSTRAINT `bill_uploads_updated_by_id_fk` FOREIGN KEY (`updated_by_id`) REFERENCES `user_member` (`id`) ON DELETE SET NULL
            ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
        """)
        
        # Create BillUploadDetail table
        cursor.execute("""
            CREATE TABLE `bill_upload_details` (
                `id` bigint NOT NULL AUTO_INCREMENT,
                `unit_of_measurement` varchar(20) DEFAULT NULL,
                `price_per_unit` decimal(10,2) NOT NULL DEFAULT 0.00,
                `previous_reading` decimal(10,2) NOT NULL DEFAULT 0.00,
                `current_reading` decimal(10,2) NOT NULL DEFAULT 0.00,
                `consumption` decimal(10,2) NOT NULL DEFAULT 0.00,
                `amount` decimal(10,2) NOT NULL,
                `created_at` datetime(6) NOT NULL,
                `updated_at` datetime(6) NOT NULL,
                `bill_upload_id` bigint NOT NULL,
                `unit_id` bigint NOT NULL,
                PRIMARY KEY (`id`),
                UNIQUE KEY `service_fee_management_bill_upload_id_unit_id_8a9b7c6d_uniq` (`bill_upload_id`,`unit_id`),
                KEY `bill_upload_details_bill_upload_id_idx` (`bill_upload_id`),
                KEY `bill_upload_details_unit_id_idx` (`unit_id`),
                CONSTRAINT `bill_upload_details_bill_upload_id_fk` FOREIGN KEY (`bill_upload_id`) REFERENCES `bill_uploads` (`id`) ON DELETE CASCADE,
                CONSTRAINT `bill_upload_details_unit_id_fk` FOREIGN KEY (`unit_id`) REFERENCES `towers_unit` (`id`) ON DELETE RESTRICT
            ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0019_delete_servicefeetower'),
        ('service_fee_management', '0068_alter_reminderlog_recipient'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_create_tables, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='BillUpload',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('upload_id', models.CharField(help_text='Unique upload identifier (e.g., BILL-ELEC-2024-01-00001)', max_length=100, unique=True)),
                        ('category', models.CharField(choices=[('Electricity', 'Electricity'), ('Gas', 'Gas'), ('Water', 'Water'), ('Service Fee', 'Service Fee')], help_text='Bill category', max_length=50)),
                        ('upload_month', models.IntegerField(help_text='Month for which bills are uploaded (1-12)', validators=[django.core.validators.MinValueValidator(1)])),
                        ('upload_year', models.IntegerField(help_text='Year for which bills are uploaded', validators=[django.core.validators.MinValueValidator(2020)])),
                        ('upload_method', models.CharField(choices=[('manual', 'Manual Entry'), ('csv', 'CSV Upload')], default='manual', max_length=20)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bill_uploads', to='user.member')),
                        ('service_fee', models.ForeignKey(help_text='Associated service fee', on_delete=django.db.models.deletion.PROTECT, related_name='bill_uploads', to='service_fee.servicefee')),
                        ('tower', models.ForeignKey(help_text='Tower for which bills are uploaded', on_delete=django.db.models.deletion.PROTECT, related_name='bill_uploads', to='towers.tower')),
                        ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_bill_uploads', to='user.member')),
                    ],
                    options={
                        'db_table': 'bill_uploads',
                        'ordering': ['-created_at'],
                        'unique_together': {('service_fee', 'tower', 'upload_month', 'upload_year')},
                    },
                ),
                migrations.CreateModel(
                    name='BillUploadDetail',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('unit_of_measurement', models.CharField(blank=True, help_text='e.g., kWh, cubic meters', max_length=20, null=True)),
                        ('price_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('previous_reading', models.DecimalField(decimal_places=2, default=0, help_text='Previous meter reading', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('current_reading', models.DecimalField(decimal_places=2, default=0, help_text='Current meter reading', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('consumption', models.DecimalField(decimal_places=2, default=0, help_text='Consumption amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('amount', models.DecimalField(decimal_places=2, help_text='Total bill amount in BDT', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('bill_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='service_fee_management.billupload')),
                        ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_upload_details', to='towers.unit')),
                    ],
                    options={
                        'db_table': 'bill_upload_details',
                        'ordering': ['unit__unit_name'],
                        'unique_together': {('bill_upload', 'unit')},
                    },
                ),
            ],
        ),
    ]
