# Generated by Django 5.2.7 on 2025-12-14 15:11

import django.db.models.deletion
from django.db import migrations, models


def safe_add_bill_category(apps, schema_editor):
    """Safely add bill_category column if it doesn't exist."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check if bill_category table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_category'
        """)
        table_exists = cursor.fetchone()[0] > 0
        
        if not table_exists:
            # Parent table doesn't exist, skip adding foreign key
            return
        # Check if bill_category_id column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND COLUMN_NAME = 'bill_category_id'
        """)
        column_exists = cursor.fetchone()[0] > 0
        
        if not column_exists:
            # Add bill_category_id column
            cursor.execute("""
                ALTER TABLE `bill_uploads` 
                ADD COLUMN `bill_category_id` bigint DEFAULT NULL,
                ADD CONSTRAINT `bill_uploads_bill_category_id_fk` 
                FOREIGN KEY (`bill_category_id`) REFERENCES `bill_category` (`id`) ON DELETE RESTRICT
            """)
            
            # Add index
            cursor.execute("""
                CREATE INDEX `bill_uploads_bill_category_id_idx` ON `bill_uploads` (`bill_category_id`)
            """)
        
        # Check if category column needs to be altered
        cursor.execute("""
            SELECT IS_NULLABLE 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND COLUMN_NAME = 'category'
        """)
        result = cursor.fetchone()
        if result and result[0] == 'NO':
            # Make category nullable
            cursor.execute("""
                ALTER TABLE `bill_uploads` 
                MODIFY COLUMN `category` varchar(50) DEFAULT NULL COMMENT 'Bill category name (legacy field)'
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('bill_categories', '0001_initial'),
        ('service_fee_management', '0069_billupload_billuploaddetail'),
    ]

    operations = [
        migrations.RunPython(safe_add_bill_category, migrations.RunPython.noop),
    ]
