# Generated by Django 5.2.7 on 2025-12-15 10:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def safe_restructure_bill_upload(apps, schema_editor):
    """Safely restructure bill upload tables."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check if service_fee_id column exists in bill_upload_details
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_upload_details'
            AND COLUMN_NAME = 'service_fee_id'
        """)
        service_fee_exists = cursor.fetchone()[0] > 0
        
        if service_fee_exists:
            # Fields already moved, skip
            return
        
        # Add new fields to bill_upload_details
        cursor.execute("""
            ALTER TABLE `bill_upload_details`
            ADD COLUMN `service_fee_id` bigint DEFAULT NULL,
            ADD COLUMN `tower_id` bigint DEFAULT NULL,
            ADD COLUMN `upload_month` int DEFAULT NULL,
            ADD COLUMN `upload_year` int DEFAULT NULL
        """)
        
        # Add foreign key constraints
        cursor.execute("""
            ALTER TABLE `bill_upload_details`
            ADD CONSTRAINT `bill_upload_details_service_fee_id_fk` 
            FOREIGN KEY (`service_fee_id`) REFERENCES `service_fee_servicefee` (`id`) ON DELETE RESTRICT,
            ADD CONSTRAINT `bill_upload_details_tower_id_fk` 
            FOREIGN KEY (`tower_id`) REFERENCES `towers_tower` (`id`) ON DELETE RESTRICT
        """)
        
        # Copy data from bill_uploads to bill_upload_details
        cursor.execute("""
            UPDATE `bill_upload_details` bd
            INNER JOIN `bill_uploads` bu ON bd.bill_upload_id = bu.id
            SET 
                bd.service_fee_id = bu.service_fee_id,
                bd.tower_id = bu.tower_id,
                bd.upload_month = bu.upload_month,
                bd.upload_year = bu.upload_year
        """)
        
        # Drop old unique constraint from bill_uploads
        cursor.execute("""
            SELECT CONSTRAINT_NAME 
            FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND CONSTRAINT_TYPE = 'UNIQUE'
            AND CONSTRAINT_NAME LIKE '%service_fee_id%'
        """)
        constraint = cursor.fetchone()
        if constraint:
            cursor.execute(f"ALTER TABLE `bill_uploads` DROP INDEX `{constraint[0]}`")
        
        # Drop foreign key constraints before dropping columns
        # Find and drop service_fee_id foreign key
        cursor.execute("""
            SELECT CONSTRAINT_NAME 
            FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND CONSTRAINT_TYPE = 'FOREIGN KEY'
            AND CONSTRAINT_NAME LIKE '%service_fee_id%'
        """)
        fk_constraint = cursor.fetchone()
        if fk_constraint:
            cursor.execute(f"ALTER TABLE `bill_uploads` DROP FOREIGN KEY `{fk_constraint[0]}`")
        
        # Find and drop tower_id foreign key
        cursor.execute("""
            SELECT CONSTRAINT_NAME 
            FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND CONSTRAINT_TYPE = 'FOREIGN KEY'
            AND CONSTRAINT_NAME LIKE '%tower_id%'
        """)
        tower_fk_constraint = cursor.fetchone()
        if tower_fk_constraint:
            cursor.execute(f"ALTER TABLE `bill_uploads` DROP FOREIGN KEY `{tower_fk_constraint[0]}`")
        
        # Remove fields from bill_uploads (now safe to drop after FK constraints are removed)
        # Check if columns exist before dropping
        cursor.execute("""
            SELECT COLUMN_NAME 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND COLUMN_NAME IN ('service_fee_id', 'tower_id', 'upload_month', 'upload_year')
        """)
        columns_to_drop = [row[0] for row in cursor.fetchall()]
        
        for column in columns_to_drop:
            cursor.execute(f"ALTER TABLE `bill_uploads` DROP COLUMN `{column}`")


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0019_delete_servicefeetower'),
        ('service_fee_management', '0070_billupload_bill_category_alter_billupload_category'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
    ]

    operations = [
        migrations.RunPython(safe_restructure_bill_upload, migrations.RunPython.noop),
    ]
