# Generated by Django 5.2.7 on 2025-12-17 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def safe_create_service_fee_bill_category(apps, schema_editor):
    """Safely create service_fee_bill_categories table if it doesn't exist."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_bill_categories'
        """)
        table_exists = cursor.fetchone()[0] > 0
        
        if table_exists:
            # Table already exists, skip creation
            return
        
        # Check if parent tables exist
        cursor.execute("""
            SELECT TABLE_NAME 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME IN ('bill_category', 'service_fee_servicefee', 'service_fee_management_servicefeepayment', 'towers_tower', 'towers_unit')
        """)
        parent_tables = {row[0] for row in cursor.fetchall()}
        
        # Build foreign key constraints only for tables that exist
        fk_constraints = []
        
        if 'bill_category' in parent_tables:
            fk_constraints.append("CONSTRAINT `service_fee_bill_categories_bill_category_id_fk` FOREIGN KEY (`bill_category_id`) REFERENCES `bill_category` (`id`) ON DELETE RESTRICT")
        
        if 'service_fee_servicefee' in parent_tables:
            fk_constraints.append("CONSTRAINT `service_fee_bill_categories_service_fee_id_fk` FOREIGN KEY (`service_fee_id`) REFERENCES `service_fee_servicefee` (`id`) ON DELETE RESTRICT")
        
        if 'service_fee_management_servicefeepayment' in parent_tables:
            fk_constraints.append("CONSTRAINT `service_fee_bill_categories_servicefeepaymentid_id_fk` FOREIGN KEY (`servicefeepaymentid_id`) REFERENCES `service_fee_management_servicefeepayment` (`id`) ON DELETE RESTRICT")
        
        if 'towers_tower' in parent_tables:
            fk_constraints.append("CONSTRAINT `service_fee_bill_categories_tower_id_fk` FOREIGN KEY (`tower_id`) REFERENCES `towers_tower` (`id`) ON DELETE RESTRICT")
        
        if 'towers_unit' in parent_tables:
            fk_constraints.append("CONSTRAINT `service_fee_bill_categories_unit_id_fk` FOREIGN KEY (`unit_id`) REFERENCES `towers_unit` (`id`) ON DELETE RESTRICT")
        
        # Build CREATE TABLE statement
        fk_clause = ",\n                ".join(fk_constraints) if fk_constraints else ""
        create_table_sql = f"""
            CREATE TABLE `service_fee_bill_categories` (
                `id` bigint NOT NULL AUTO_INCREMENT,
                `upload_month` int DEFAULT NULL,
                `upload_year` int DEFAULT NULL,
                `unit_of_measurement` varchar(20) DEFAULT NULL,
                `price_per_unit` decimal(10,2) NOT NULL DEFAULT 0.00,
                `previous_reading` decimal(10,2) NOT NULL DEFAULT 0.00,
                `current_reading` decimal(10,2) NOT NULL DEFAULT 0.00,
                `consumption` decimal(10,2) NOT NULL DEFAULT 0.00,
                `amount` decimal(10,2) NOT NULL,
                `created_at` datetime(6) NOT NULL,
                `updated_at` datetime(6) NOT NULL,
                `bill_category_id` bigint DEFAULT NULL,
                `service_fee_id` bigint DEFAULT NULL,
                `servicefeepaymentid_id` bigint NOT NULL,
                `tower_id` bigint DEFAULT NULL,
                `unit_id` bigint NOT NULL,
                PRIMARY KEY (`id`),
                KEY `service_fee_bill_categories_bill_category_id_idx` (`bill_category_id`),
                KEY `service_fee_bill_categories_service_fee_id_idx` (`service_fee_id`),
                KEY `service_fee_bill_categories_servicefeepaymentid_id_idx` (`servicefeepaymentid_id`),
                KEY `service_fee_bill_categories_tower_id_idx` (`tower_id`),
                KEY `service_fee_bill_categories_unit_id_idx` (`unit_id`)"""
        
        if fk_clause:
            create_table_sql += f",\n                {fk_clause}"
        
        create_table_sql += "\n            ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
        
        cursor.execute(create_table_sql)


class Migration(migrations.Migration):

    dependencies = [
        ('bill_categories', '0001_initial'),
        ('service_fee', '0019_delete_servicefeetower'),
        ('service_fee_management', '0071_alter_billupload_unique_together_and_more'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_create_service_fee_bill_category, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='ServiceFeeBillCategory',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('upload_month', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                        ('upload_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2020)])),
                        ('unit_of_measurement', models.CharField(blank=True, max_length=20, null=True)),
                        ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('current_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('bill_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_bill_categories', to='bill_categories.billcategory')),
                        ('service_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_bill_categories', to='service_fee.servicefee')),
                        ('servicefeepaymentid', models.ForeignKey(help_text='Linked service fee payment', on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_bill_categories', to='service_fee_management.servicefeepayment')),
                        ('tower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_bill_categories', to='towers.tower')),
                        ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_bill_categories', to='towers.unit')),
                    ],
                    options={
                        'verbose_name_plural': 'Service Fee Bill Categories',
                        'db_table': 'service_fee_bill_categories',
                        'ordering': ['unit__unit_name'],
                    },
                ),
            ],
        ),
    ]
