# Generated by Django 5.2.7 on 2025-12-17 12:27

from django.db import migrations


def safe_remove_columns(apps, schema_editor):
    """Safely remove upload_month and upload_year columns if they exist."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check and remove upload_month
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_bill_categories'
            AND COLUMN_NAME = 'upload_month'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE `service_fee_bill_categories` DROP COLUMN `upload_month`")
        
        # Check and remove upload_year
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_bill_categories'
            AND COLUMN_NAME = 'upload_year'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE `service_fee_bill_categories` DROP COLUMN `upload_year`")


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0072_servicefeebillcategory'),
    ]

    operations = [
        migrations.RunPython(safe_remove_columns, migrations.RunPython.noop),
    ]
