# Generated by Django 5.2.7 on 2025-12-20 12:05

import django.core.validators
from django.db import migrations, models


def safe_add_penalty_fields(apps, schema_editor):
    """Safely add penalty fields if they don't exist."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check and add penalty_after_waiver
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_payment_details'
            AND COLUMN_NAME = 'penalty_after_waiver'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE `service_fee_payment_details` 
                ADD COLUMN `penalty_after_waiver` decimal(10,2) NOT NULL DEFAULT 0.00 
                COMMENT 'Penalty remaining after waiver'
            """)
        
        # Check and add penalty_amount
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_payment_details'
            AND COLUMN_NAME = 'penalty_amount'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE `service_fee_payment_details` 
                ADD COLUMN `penalty_amount` decimal(10,2) NOT NULL DEFAULT 0.00 
                COMMENT 'Original penalty amount'
            """)
        
        # Check and add waived_amount
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_payment_details'
            AND COLUMN_NAME = 'waived_amount'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE `service_fee_payment_details` 
                ADD COLUMN `waived_amount` decimal(10,2) NOT NULL DEFAULT 0.00 
                COMMENT 'Amount waived from penalty'
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0073_remove_servicefeebillcategory_upload_month_and_more'),
    ]

    operations = [
        migrations.RunPython(safe_add_penalty_fields, migrations.RunPython.noop),
    ]
