# Generated by Django 5.2.7 on 2025-12-20 12:11

import django.db.models.deletion
from django.db import migrations, models


def safe_create_penalty_waiver(apps, schema_editor):
    """Safely create penalty waiver table if it doesn't exist."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_penalty_waivers'
        """)
        table_exists = cursor.fetchone()[0] > 0
        
        if table_exists:
            # Table already exists, skip creation
            return
        
        # Create table
        cursor.execute("""
            CREATE TABLE `service_fee_penalty_waivers` (
                `id` bigint NOT NULL AUTO_INCREMENT,
                `waiver_type` varchar(20) NOT NULL,
                `percentage` decimal(5,2) DEFAULT NULL,
                `waived_amount` decimal(10,2) NOT NULL,
                `reason` varchar(255) DEFAULT NULL,
                `notes` text DEFAULT NULL,
                `applied_at` datetime(6) NOT NULL,
                `applied_by_id` bigint DEFAULT NULL,
                `billing_id` bigint NOT NULL,
                PRIMARY KEY (`id`),
                KEY `service_fee_penalty_waivers_applied_by_id_idx` (`applied_by_id`),
                KEY `service_fee_penalty_waivers_billing_id_idx` (`billing_id`),
                CONSTRAINT `service_fee_penalty_waivers_applied_by_id_fk` FOREIGN KEY (`applied_by_id`) REFERENCES `user_member` (`id`) ON DELETE SET NULL,
                CONSTRAINT `service_fee_penalty_waivers_billing_id_fk` FOREIGN KEY (`billing_id`) REFERENCES `service_fee_payment_details` (`id`) ON DELETE CASCADE
            ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0074_servicefeebilling_penalty_after_waiver_and_more'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_create_penalty_waiver, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='PenaltyWaiver',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('waiver_type', models.CharField(choices=[('full', 'Full Waiver'), ('partial_percentage', 'Partial (Percentage)'), ('partial_fixed', 'Partial (Fixed Amount)')], max_length=20)),
                        ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage waived if applicable', max_digits=5, null=True)),
                        ('waived_amount', models.DecimalField(decimal_places=2, help_text='Amount waived in this instance', max_digits=10)),
                        ('reason', models.CharField(blank=True, max_length=255, null=True)),
                        ('notes', models.TextField(blank=True, null=True)),
                        ('applied_at', models.DateTimeField(auto_now_add=True)),
                        ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_waivers', to='user.member')),
                        ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='service_fee_management.servicefeebilling')),
                    ],
                    options={
                        'db_table': 'service_fee_penalty_waivers',
                        'ordering': ['-applied_at'],
                    },
                ),
            ],
        ),
    ]
