# Generated by Django 5.2.7 on 2025-12-20 12:20

import django.core.validators
from django.db import migrations, models


def safe_move_penalty_fields(apps, schema_editor):
    """Safely move penalty fields from billing to waiver table."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        # Remove fields from service_fee_payment_details if they exist
        for column in ['penalty_after_waiver', 'penalty_amount', 'waived_amount']:
            cursor.execute(f"""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_payment_details'
                AND COLUMN_NAME = '{column}'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute(f"ALTER TABLE `service_fee_payment_details` DROP COLUMN `{column}`")
        
        # Add fields to service_fee_penalty_waivers if they don't exist
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_penalty_waivers'
            AND COLUMN_NAME = 'penalty_after_waiver'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE `service_fee_penalty_waivers` 
                ADD COLUMN `penalty_after_waiver` decimal(10,2) NOT NULL DEFAULT 0.00 
                COMMENT 'Penalty remaining after this waiver'
            """)
        
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_penalty_waivers'
            AND COLUMN_NAME = 'penalty_amount'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE `service_fee_penalty_waivers` 
                ADD COLUMN `penalty_amount` decimal(10,2) NOT NULL DEFAULT 0.00 
                COMMENT 'Penalty amount before this waiver'
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0075_penaltywaiver'),
    ]

    operations = [
        migrations.RunPython(safe_move_penalty_fields, migrations.RunPython.noop),
    ]
