# Generated by Django 5.2.7 on 2025-12-21 15:59

import django.db.models.deletion
from django.db import migrations, models


def safe_add_payment_fields(apps, schema_editor):
    """Safely add payment-related fields if they don't exist."""
    connection = schema_editor.connection
    
    with connection.cursor() as cursor:
        fields_to_add = [
            ('from_account_number', "varchar(100) DEFAULT NULL COMMENT \"Sender's account number\""),
            ('other_method_name', "varchar(100) DEFAULT NULL COMMENT \"Display name for 'Other' methods like bKash, Nagad\""),
            ('received_by_id', "bigint DEFAULT NULL COMMENT 'User who received the cash payment'"),
            ('received_by_name', "varchar(255) DEFAULT NULL COMMENT 'Name of person who received payment (fallback)'"),
            ('to_account_name', "varchar(255) DEFAULT NULL COMMENT \"Receiver's account name\""),
            ('to_account_number', "varchar(100) DEFAULT NULL COMMENT \"Receiver's account number\""),
        ]
        
        for column_name, column_def in fields_to_add:
            cursor.execute(f"""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.COLUMNS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_payment_details'
                AND COLUMN_NAME = '{column_name}'
            """)
            if cursor.fetchone()[0] == 0:
                cursor.execute(f"ALTER TABLE `service_fee_payment_details` ADD COLUMN `{column_name}` {column_def}")
        
        # Add foreign key constraint for received_by_id if it doesn't exist
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_payment_details'
            AND COLUMN_NAME = 'received_by_id'
            AND REFERENCED_TABLE_NAME IS NOT NULL
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE `service_fee_payment_details` 
                ADD CONSTRAINT `service_fee_payment_details_received_by_id_fk` 
                FOREIGN KEY (`received_by_id`) REFERENCES `user_member` (`id`) ON DELETE SET NULL
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0076_remove_servicefeebilling_penalty_after_waiver_and_more'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.RunPython(safe_add_payment_fields, migrations.RunPython.noop),
    ]
