# Generated by Django 5.2.7 on 2025-12-22 17:45
# This migration is a duplicate of changes already applied in 0071
# Keeping it as a no-op to maintain migration history

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill_categories', '0002_alter_billcategory_description'),
        ('service_fee', '0020_add_late_penalty_configuration'),
        ('service_fee_management', '0077_servicefeebilling_from_account_number_and_more'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
    ]

    operations = [
        # All operations in this migration were already handled by previous migrations
        # Keeping as no-op to maintain migration history
    ]
