# Generated by Django 5.2.7 on 2025-12-23 10:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models, connection


def safe_alter_unique_together(apps, schema_editor):
    """Safely alter unique_together constraint, handling cases where old columns don't exist."""
    with connection.cursor() as cursor:
        # Check if old unique constraint exists (on columns that may have been dropped)
        cursor.execute("""
            SELECT CONSTRAINT_NAME 
            FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND CONSTRAINT_TYPE = 'UNIQUE'
            AND CONSTRAINT_NAME LIKE '%service_fee_id%'
        """)
        old_constraint = cursor.fetchone()
        
        if old_constraint:
            # Drop old constraint
            cursor.execute(f"ALTER TABLE `bill_uploads` DROP INDEX `{old_constraint[0]}`")
        
        # Check if new unique constraint already exists
        cursor.execute("""
            SELECT CONSTRAINT_NAME 
            FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND CONSTRAINT_TYPE = 'UNIQUE'
            AND CONSTRAINT_NAME LIKE '%upload_id%'
        """)
        new_constraint = cursor.fetchone()
        
        # Check if upload_id column exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND COLUMN_NAME = 'upload_id'
        """)
        upload_id_exists = cursor.fetchone()[0] > 0
        
        if upload_id_exists and not new_constraint:
            # Create new unique constraint on upload_id
            cursor.execute("""
                ALTER TABLE `bill_uploads` 
                ADD UNIQUE KEY `bill_uploads_upload_id_unique` (`upload_id`)
            """)


def safe_remove_fields(apps, schema_editor):
    """Safely remove fields that may not exist."""
    with connection.cursor() as cursor:
        # Remove send_time from reminder_timings if it exists
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_reminder_timings'
            AND COLUMN_NAME = 'send_time'
        """)
        if cursor.fetchone()[0] > 0:
            cursor.execute("ALTER TABLE `service_fee_reminder_timings` DROP COLUMN `send_time`")
        
        # Remove upload_month and upload_year from service_fee_bill_categories if they exist
        cursor.execute("""
            SELECT COLUMN_NAME 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_bill_categories'
            AND COLUMN_NAME IN ('upload_month', 'upload_year')
        """)
        columns_to_drop = [row[0] for row in cursor.fetchall()]
        for column in columns_to_drop:
            cursor.execute(f"ALTER TABLE `service_fee_bill_categories` DROP COLUMN `{column}`")
        
        # Remove service_fee, tower, upload_month, upload_year from bill_uploads if they exist
        cursor.execute("""
            SELECT COLUMN_NAME 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND COLUMN_NAME IN ('service_fee_id', 'tower_id', 'upload_month', 'upload_year')
        """)
        bill_upload_columns = [row[0] for row in cursor.fetchall()]
        for column in bill_upload_columns:
            # Drop foreign key constraints first if they exist
            cursor.execute("""
                SELECT CONSTRAINT_NAME 
                FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'bill_uploads'
                AND CONSTRAINT_TYPE = 'FOREIGN KEY'
                AND CONSTRAINT_NAME LIKE %s
            """, [f'%{column}%'])
            fk_constraint = cursor.fetchone()
            if fk_constraint:
                cursor.execute(f"ALTER TABLE `bill_uploads` DROP FOREIGN KEY `{fk_constraint[0]}`")
            cursor.execute(f"ALTER TABLE `bill_uploads` DROP COLUMN `{column}`")


def reverse_remove_fields(apps, schema_editor):
    """Reverse field removals - this is a no-op as we can't safely restore dropped fields."""
    pass


def safe_add_fields(apps, schema_editor):
    """Safely add fields only if they don't already exist."""
    with connection.cursor() as cursor:
        # Check if bill_category_id already exists in bill_uploads (added in migration 0070)
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND COLUMN_NAME = 'bill_category_id'
        """)
        bill_category_exists = cursor.fetchone()[0] > 0
        
        if not bill_category_exists:
            # Add bill_category_id column if it doesn't exist
            cursor.execute("""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.TABLES 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'bill_category'
            """)
            table_exists = cursor.fetchone()[0] > 0
            
            if table_exists:
                cursor.execute("""
                    ALTER TABLE `bill_uploads` 
                    ADD COLUMN `bill_category_id` bigint DEFAULT NULL,
                    ADD CONSTRAINT `bill_uploads_bill_category_id_fk` 
                    FOREIGN KEY (`bill_category_id`) REFERENCES `bill_category` (`id`) ON DELETE RESTRICT
                """)
                cursor.execute("""
                    CREATE INDEX `bill_uploads_bill_category_id_idx` ON `bill_uploads` (`bill_category_id`)
                """)
        
        # Check if fields already exist in bill_upload_details (added in migration 0071)
        cursor.execute("""
            SELECT COLUMN_NAME 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_upload_details'
            AND COLUMN_NAME IN ('service_fee_id', 'tower_id', 'upload_month', 'upload_year')
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}
        
        # Add service_fee_id if it doesn't exist
        if 'service_fee_id' not in existing_columns:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.TABLES 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'service_fee_servicefee'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("""
                    ALTER TABLE `bill_upload_details` 
                    ADD COLUMN `service_fee_id` bigint DEFAULT NULL
                """)
                cursor.execute("""
                    ALTER TABLE `bill_upload_details`
                    ADD CONSTRAINT `bill_upload_details_service_fee_id_fk` 
                    FOREIGN KEY (`service_fee_id`) REFERENCES `service_fee_servicefee` (`id`) ON DELETE RESTRICT
                """)
                cursor.execute("""
                    CREATE INDEX `bill_upload_details_service_fee_id_idx` ON `bill_upload_details` (`service_fee_id`)
                """)
        
        # Add tower_id if it doesn't exist
        if 'tower_id' not in existing_columns:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.TABLES 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'towers_tower'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("""
                    ALTER TABLE `bill_upload_details` 
                    ADD COLUMN `tower_id` bigint DEFAULT NULL
                """)
                cursor.execute("""
                    ALTER TABLE `bill_upload_details`
                    ADD CONSTRAINT `bill_upload_details_tower_id_fk` 
                    FOREIGN KEY (`tower_id`) REFERENCES `towers_tower` (`id`) ON DELETE RESTRICT
                """)
                cursor.execute("""
                    CREATE INDEX `bill_upload_details_tower_id_idx` ON `bill_upload_details` (`tower_id`)
                """)
        
        # Add upload_month if it doesn't exist
        if 'upload_month' not in existing_columns:
            cursor.execute("""
                ALTER TABLE `bill_upload_details` 
                ADD COLUMN `upload_month` int DEFAULT NULL
            """)
        
        # Add upload_year if it doesn't exist
        if 'upload_year' not in existing_columns:
            cursor.execute("""
                ALTER TABLE `bill_upload_details` 
                ADD COLUMN `upload_year` int DEFAULT NULL
            """)
        
        # Check and add fields for penaltywaiver table (db_table: service_fee_penalty_waivers)
        cursor.execute("""
            SELECT COLUMN_NAME 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_penalty_waivers'
            AND COLUMN_NAME IN ('penalty_after_waiver', 'penalty_amount')
        """)
        penalty_columns = {row[0] for row in cursor.fetchall()}
        
        if 'penalty_after_waiver' not in penalty_columns:
            cursor.execute("""
                ALTER TABLE `service_fee_penalty_waivers` 
                ADD COLUMN `penalty_after_waiver` decimal(10,2) NOT NULL DEFAULT 0.00
            """)
        
        if 'penalty_amount' not in penalty_columns:
            cursor.execute("""
                ALTER TABLE `service_fee_penalty_waivers` 
                ADD COLUMN `penalty_amount` decimal(10,2) NOT NULL DEFAULT 0.00
            """)
        
        # Check and add send_times field for reminder table (db_table: service_fee_reminders)
        cursor.execute("""
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_reminders'
            AND COLUMN_NAME = 'send_times'
        """)
        if cursor.fetchone()[0] == 0:
            cursor.execute("""
                ALTER TABLE `service_fee_reminders` 
                ADD COLUMN `send_times` json DEFAULT NULL
            """)
        
        # Check and add fields for servicefeebilling table (db_table: service_fee_payment_details)
        cursor.execute("""
            SELECT COLUMN_NAME 
            FROM INFORMATION_SCHEMA.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'service_fee_payment_details'
            AND COLUMN_NAME IN ('from_account_number', 'other_method_name', 'received_by_id', 'received_by_name', 'to_account_name', 'to_account_number')
        """)
        billing_columns = {row[0] for row in cursor.fetchall()}
        
        if 'from_account_number' not in billing_columns:
            cursor.execute("""
                ALTER TABLE `service_fee_payment_details` 
                ADD COLUMN `from_account_number` varchar(100) DEFAULT NULL
            """)
        
        if 'other_method_name' not in billing_columns:
            cursor.execute("""
                ALTER TABLE `service_fee_payment_details` 
                ADD COLUMN `other_method_name` varchar(100) DEFAULT NULL
            """)
        
        if 'received_by_id' not in billing_columns:
            cursor.execute("""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.TABLES 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'user_member'
            """)
            if cursor.fetchone()[0] > 0:
                cursor.execute("""
                    ALTER TABLE `service_fee_payment_details` 
                    ADD COLUMN `received_by_id` bigint DEFAULT NULL
                """)
                cursor.execute("""
                    ALTER TABLE `service_fee_payment_details`
                    ADD CONSTRAINT `service_fee_payment_received_by_id_fk` 
                    FOREIGN KEY (`received_by_id`) REFERENCES `user_member` (`id`) ON DELETE SET NULL
                """)
                cursor.execute("""
                    CREATE INDEX `service_fee_payment_received_by_id_idx` ON `service_fee_payment_details` (`received_by_id`)
                """)
        
        if 'received_by_name' not in billing_columns:
            cursor.execute("""
                ALTER TABLE `service_fee_payment_details` 
                ADD COLUMN `received_by_name` varchar(255) DEFAULT NULL
            """)
        
        if 'to_account_name' not in billing_columns:
            cursor.execute("""
                ALTER TABLE `service_fee_payment_details` 
                ADD COLUMN `to_account_name` varchar(255) DEFAULT NULL
            """)
        
        if 'to_account_number' not in billing_columns:
            cursor.execute("""
                ALTER TABLE `service_fee_payment_details` 
                ADD COLUMN `to_account_number` varchar(100) DEFAULT NULL
            """)


def reverse_alter_unique_together(apps, schema_editor):
    """Reverse the unique_together alteration."""
    with connection.cursor() as cursor:
        # Drop new constraint
        cursor.execute("""
            SELECT CONSTRAINT_NAME 
            FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'bill_uploads'
            AND CONSTRAINT_TYPE = 'UNIQUE'
            AND CONSTRAINT_NAME LIKE '%upload_id%'
        """)
        constraint = cursor.fetchone()
        if constraint:
            cursor.execute(f"ALTER TABLE `bill_uploads` DROP INDEX `{constraint[0]}`")


class Migration(migrations.Migration):

    dependencies = [
        ("bill_categories", "0002_alter_billcategory_description"),
        ("service_fee", "0020_add_late_penalty_configuration"),
        ("service_fee_management", "0078_alter_billupload_unique_together_and_more"),
        ("towers", "0011_alter_owner_unique_together_delete_vehicle"),
        ("user", "0002_delete_mymodel"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_alter_unique_together, reverse_alter_unique_together),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="billupload",
                    unique_together={("upload_id",)},
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_remove_fields, reverse_remove_fields),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="remindertiming",
                    name="send_time",
                ),
                migrations.RemoveField(
                    model_name="servicefeebillcategory",
                    name="upload_month",
                ),
                migrations.RemoveField(
                    model_name="servicefeebillcategory",
                    name="upload_year",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_add_fields, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="billupload",
                    name="bill_category",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Bill category",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_uploads",
                        to="bill_categories.billcategory",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_add_fields, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="billuploaddetail",
                    name="service_fee",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Associated service fee",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_upload_details",
                        to="service_fee.servicefee",
                    ),
                ),
                migrations.AddField(
                    model_name="billuploaddetail",
                    name="tower",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="Tower for this detail",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bill_upload_details",
                        to="towers.tower",
                    ),
                ),
                migrations.AddField(
                    model_name="billuploaddetail",
                    name="upload_month",
                    field=models.IntegerField(
                        blank=True,
                        help_text="Month for which this detail applies (1-12)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                migrations.AddField(
                    model_name="billuploaddetail",
                    name="upload_year",
                    field=models.IntegerField(
                        blank=True,
                        help_text="Year for which this detail applies",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(2020)],
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(safe_add_fields, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="penaltywaiver",
                    name="penalty_after_waiver",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Penalty remaining after this waiver",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                migrations.AddField(
                    model_name="penaltywaiver",
                    name="penalty_amount",
                    field=models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Penalty amount before this waiver",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                migrations.AddField(
                    model_name="reminder",
                    name="send_times",
                    field=models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of times to send reminder (e.g., ['10:00:00', '14:00:00'])",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="servicefeebilling",
                    name="from_account_number",
                    field=models.CharField(
                        blank=True,
                        help_text="Sender's account number",
                        max_length=100,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="servicefeebilling",
                    name="other_method_name",
                    field=models.CharField(
                        blank=True,
                        help_text="Display name for 'Other' methods like bKash, Nagad",
                        max_length=100,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="servicefeebilling",
                    name="received_by",
                    field=models.ForeignKey(
                        blank=True,
                        help_text="User who received the cash payment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to="user.member",
                    ),
                ),
                migrations.AddField(
                    model_name="servicefeebilling",
                    name="received_by_name",
                    field=models.CharField(
                        blank=True,
                        help_text="Name of person who received payment (fallback)",
                        max_length=255,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="servicefeebilling",
                    name="to_account_name",
                    field=models.CharField(
                        blank=True,
                        help_text="Receiver's account name",
                        max_length=255,
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="servicefeebilling",
                    name="to_account_number",
                    field=models.CharField(
                        blank=True,
                        help_text="Receiver's account number",
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="billupload",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Bill category name (legacy field)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Database operations already handled by safe_remove_fields above
                migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
            ],
            state_operations=[
                # These fields are already handled by safe_remove_fields above
                # Keeping them in state_operations for Django's migration state tracking
                migrations.RemoveField(
                    model_name="billupload",
                    name="service_fee",
                ),
                migrations.RemoveField(
                    model_name="billupload",
                    name="tower",
                ),
                migrations.RemoveField(
                    model_name="billupload",
                    name="upload_month",
                ),
                migrations.RemoveField(
                    model_name="billupload",
                    name="upload_year",
                ),
            ],
        ),
    ]
