# Generated by Django 5.2.7 on 2025-12-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0079_alter_billupload_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltywaiver',
            name='waiver_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete waiver data as JSON (auto-populated)', null=True),
        ),
    ]
