# Generated by Django 5.2.7 on 2025-12-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0080_penaltywaiver_waiver_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penaltywaiver',
            name='waiver_data',
        ),
    ]
