# Generated by Django 5.2.7 on 2025-12-28 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0081_remove_penaltywaiver_waiver_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeepayment',
            name='additional_bill_charges',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of all additional bill categories', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='servicefeepayment',
            name='base_service_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base service fee amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='servicefeepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount (base + additional) in this transaction', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
