# Generated by Django 5.2.7 on 2025-12-30 18:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0087_add_voucher_payment_account_fields'),
        ('towers', '0024_alter_unitresidenthistory_entry_type'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_type', models.CharField(choices=[('auto_excess', 'Auto-generated from excess payment'), ('service_fee_advance', 'Service Fee Advance'), ('other_advance', 'Other Advance')], default='auto_excess', help_text='How advance payment was created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total advance amount held', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('applied_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount already applied to payments', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, help_text='Available advance balance', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('source_payment_id', models.IntegerField(blank=True, help_text='Payment ID that generated this advance (if auto_excess)', null=True)),
                ('status', models.CharField(choices=[('available', 'Available for use'), ('partial', 'Partially applied'), ('applied', 'Fully applied'), ('cancelled', 'Cancelled')], default='available', help_text='Current status of advance payment', max_length=20)),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When advance was fully applied', null=True)),
                ('expired_at', models.DateTimeField(blank=True, help_text='When advance expires if not used (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about this advance payment', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advance_payments', to='user.member')),
                ('resident', models.ForeignKey(blank=True, help_text='Resident associated with advance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments', to='user.member')),
                ('unit', models.ForeignKey(help_text='Unit for which advance is held', on_delete=django.db.models.deletion.CASCADE, related_name='advance_payments', to='towers.unit')),
            ],
            options={
                'db_table': 'service_fee_advance_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['unit', 'status'], name='service_fee_unit_id_ffb81c_idx'), models.Index(fields=['status', '-created_at'], name='service_fee_status_c8313d_idx')],
            },
        ),
    ]
