# Generated by Django 5.2.7 on 2026-01-01 12:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_categories', '0002_alter_billcategory_description'),
        ('service_fee_management', '0088_advancepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('base_fee', 'Base Service Fee'), ('penalty', 'Penalty/Late Fee'), ('bill_category', 'Bill Category/Utility Item'), ('unit_specific', 'Unit-Specific Item')], help_text='Type of item: base fee, penalty, bill category, or unit-specific', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this item', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Details about this item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_category', models.ForeignKey(blank=True, help_text='Bill category if item_type is bill_category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_items', to='bill_categories.billcategory')),
                ('penalty_waiver', models.ForeignKey(blank=True, help_text='Penalty waiver record if item_type is penalty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_items', to='service_fee_management.penaltywaiver')),
                ('service_fee_payment', models.ForeignKey(help_text='Parent service fee payment for this unit+period', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='service_fee_management.servicefeepayment')),
            ],
            options={
                'db_table': 'service_fee_management_servicefeeitem',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['service_fee_payment', 'item_type'], name='service_fee_service_894e88_idx'), models.Index(fields=['bill_category'], name='service_fee_bill_ca_f95d54_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeePaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('penalty', 'Penalty Payment'), ('base_fee', 'Base Service Fee'), ('bill_category', 'Bill Category Charge')], help_text='What component was paid', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid for this component', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Details about this payment component', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_category', models.ForeignKey(blank=True, help_text="Bill category if payment_type is 'bill_category'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_details', to='bill_categories.billcategory')),
                ('penalty_waiver', models.ForeignKey(blank=True, help_text="Penalty waiver record if payment_type is 'penalty'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_details', to='service_fee_management.penaltywaiver')),
                ('service_fee_billing', models.ForeignKey(help_text='Related billing record', on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='service_fee_management.servicefeebilling')),
                ('service_fee_payment', models.ForeignKey(help_text='Parent payment transaction', on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='service_fee_management.servicefeepayment')),
            ],
            options={
                'db_table': 'service_fee_management_servicefeepaymentdetail',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['service_fee_payment', 'payment_type'], name='service_fee_service_dae36c_idx'), models.Index(fields=['service_fee_billing'], name='service_fee_service_f88810_idx')],
            },
        ),
    ]
