# Generated by Django 5.2.7 on 2026-01-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0089_servicefeeitem_servicefeepaymentdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeeitem',
            name='item_type',
            field=models.CharField(help_text='Type of item: base fee, penalty, bill category, or unit-specific', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicefeepaymentdetail',
            name='payment_type',
            field=models.CharField(help_text='What component was paid', max_length=50),
        ),
    ]
