# Generated by Django 5.2.7 on 2026-01-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0090_alter_servicefeeitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeeitem',
            name='item_name',
            field=models.CharField(blank=True, help_text='Readable name of the item (e.g. Service Fee, Electricity)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicefeepaymentdetail',
            name='item_name',
            field=models.CharField(blank=True, help_text='Readable name of the item (e.g. Service Fee, Late Fee)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeeitem',
            name='item_type',
            field=models.CharField(help_text='Type of item: Service Fee, Late Fee, or dynamic bill category name', max_length=50),
        ),
    ]
