# Generated by Django 5.2.7 on 2026-01-01 18:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0091_servicefeeitem_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Amount allocated to this item', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, help_text='Details about this allocation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_fee_billing', models.ForeignKey(help_text='Related billing record (source of funds)', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='service_fee_management.servicefeebilling')),
                ('service_fee_item', models.ForeignKey(help_text='Specific item being paid (destination of funds)', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='service_fee_management.servicefeeitem')),
                ('service_fee_payment', models.ForeignKey(help_text='Parent payment transaction context', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='service_fee_management.servicefeepayment')),
            ],
            options={
                'db_table': 'service_fee_payment_allocations',
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ServiceFeePaymentDetail',
        ),
        migrations.AddIndex(
            model_name='servicefeepaymentallocation',
            index=models.Index(fields=['service_fee_billing'], name='service_fee_service_2ee7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeepaymentallocation',
            index=models.Index(fields=['service_fee_item'], name='service_fee_service_61f90c_idx'),
        ),
    ]
