# Generated by Django 5.2.7 on 2026-01-01 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0092_servicefeepaymentallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeepaymentallocation',
            name='allocation_type',
            field=models.CharField(choices=[('cash', 'Cash Payment'), ('waiver', 'Penalty Waiver')], default='cash', help_text='Whether this allocation comes from a cash payment or a waiver', max_length=20),
        ),
        migrations.AddField(
            model_name='servicefeepaymentallocation',
            name='penalty_waiver',
            field=models.ForeignKey(blank=True, help_text="Related waiver record if allocation_type is 'waiver'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='service_fee_management.penaltywaiver'),
        ),
        migrations.AddIndex(
            model_name='servicefeepaymentallocation',
            index=models.Index(fields=['allocation_type'], name='service_fee_allocat_18a816_idx'),
        ),
    ]
