# Generated by Django 5.2.7 on 2026-01-03 11:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0093_servicefeepaymentallocation_allocation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeepayment',
            name='late_penalty_enabled',
            field=models.BooleanField(default=False, help_text='Whether late payment penalties were enabled at time of generation'),
        ),
        migrations.CreateModel(
            name='ServiceFeePaymentLatePenaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_overdue', models.IntegerField(help_text='Number of days overdue for this penalty tier (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('penalty_percentage', models.DecimalField(decimal_places=2, help_text='Penalty percentage (>1 and <=100)', max_digits=5, validators=[django.core.validators.MinValueValidator(1.01), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=0, help_text='Order of this tier (lower numbers = earlier tiers)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(help_text='Parent payment record', on_delete=django.db.models.deletion.CASCADE, related_name='penalty_tiers', to='service_fee_management.servicefeepayment')),
            ],
            options={
                'verbose_name': 'Service Fee Payment Late Penalty Tier',
                'verbose_name_plural': 'Service Fee Payment Late Penalty Tiers',
                'db_table': 'service_fee_management_servicefeepaymentlatepenaltytier',
                'ordering': ['order', 'days_overdue'],
                'unique_together': {('payment', 'days_overdue')},
            },
        ),
    ]
