# Generated by Django 5.2.7 on 2026-01-03 12:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0094_servicefeepayment_late_penalty_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFeePaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('frequency', models.CharField(default='Monthly', max_length=20)),
                ('billing_cycle', models.CharField(default='Monthly', max_length=20)),
                ('due_day', models.IntegerField(help_text='Due day of the month (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('accepts_cash', models.BooleanField(default=False)),
                ('accepts_mfs', models.BooleanField(default=False)),
                ('accepts_bank', models.BooleanField(default=False)),
                ('reminder_before_days', models.IntegerField(default=0)),
                ('reminder_after_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.OneToOneField(help_text='Parent payment record', on_delete=django.db.models.deletion.CASCADE, related_name='config_snapshot', to='service_fee_management.servicefeepayment')),
            ],
            options={
                'verbose_name': 'Service Fee Payment Configuration Snapshot',
                'verbose_name_plural': 'Service Fee Payment Configuration Snapshots',
                'db_table': 'service_fee_management_servicefeepaymentconfig',
            },
        ),
    ]
