# Generated by Django 5.2.7 on 2026-01-03 12:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

def noop(apps, schema_editor):
    pass

def add_field_safe(apps, schema_editor):
    table = 'service_fee_management_servicefeepayment'
    col = 'generation_config_id'
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SHOW COLUMNS FROM {table} LIKE '{col}'")
        if not cursor.fetchone():
             # Add column (MyISAM, no FK constraint for robustness)
             cursor.execute(f"ALTER TABLE {table} ADD COLUMN {col} bigint NULL")

class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0021_alter_latepenaltytier_days_overdue_and_more'),
        ('service_fee_management', '0095_servicefeepaymentconfig'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ServiceFeeGenerationConfig',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('year', models.IntegerField(help_text='Billing period year')),
                        ('month', models.IntegerField(help_text='Billing period month')),
                        ('fee_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                        ('currency', models.CharField(default='BDT', max_length=3)),
                        ('frequency', models.CharField(default='Monthly', max_length=20)),
                        ('billing_cycle', models.CharField(default='Monthly', max_length=20)),
                        ('due_day', models.IntegerField(help_text='Due day of the month (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                        ('accepts_cash', models.BooleanField(default=False)),
                        ('accepts_mfs', models.BooleanField(default=False)),
                        ('accepts_bank', models.BooleanField(default=False)),
                        ('reminder_before_days', models.IntegerField(default=0)),
                        ('reminder_after_days', models.IntegerField(default=0)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('service_fee', models.ForeignKey(help_text='The service fee this config belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='generation_configs', to='service_fee.servicefee')),
                    ],
                    options={
                        'verbose_name': 'Service Fee Generation Configuration',
                        'verbose_name_plural': 'Service Fee Generation Configurations',
                        'db_table': 'service_fee_management_servicefeegenerationconfig',
                        'unique_together': {('service_fee', 'year', 'month')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    """
                    CREATE TABLE IF NOT EXISTS `service_fee_management_servicefeegenerationconfig` (
                        `id` bigint AUTO_INCREMENT NOT NULL PRIMARY KEY,
                        `year` integer NOT NULL,
                        `month` integer NOT NULL,
                        `fee_amount` decimal(15, 2) NOT NULL,
                        `currency` varchar(3) NOT NULL,
                        `frequency` varchar(20) NOT NULL,
                        `billing_cycle` varchar(20) NOT NULL,
                        `due_day` integer NOT NULL,
                        `accepts_cash` tinyint(1) NOT NULL,
                        `accepts_mfs` tinyint(1) NOT NULL,
                        `accepts_bank` tinyint(1) NOT NULL,
                        `reminder_before_days` integer NOT NULL,
                        `reminder_after_days` integer NOT NULL,
                        `created_at` datetime(6) NOT NULL,
                        `service_fee_id` bigint NOT NULL,
                        UNIQUE KEY `unique_gen_config` (`service_fee_id`, `year`, `month`),
                        CONSTRAINT `fk_sfgc_service_fee` FOREIGN KEY (`service_fee_id`) REFERENCES `service_fee_servicefee` (`id`) ON DELETE CASCADE
                    ) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;
                    """,
                    reverse_sql=migrations.RunSQL.noop
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='servicefeepayment',
                    name='generation_config',
                    field=models.ForeignKey(blank=True, help_text='Reference to the snapshot config at time of generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='service_fee_management.servicefeegenerationconfig'),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_field_safe, reverse_code=noop),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='ServiceFeePaymentConfig',
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS service_fee_management_servicefeepaymentconfig",
                    reverse_sql=migrations.RunSQL.noop
                ),
            ]
        ),
    ]
