# Generated by Django 5.2.7 on 2026-01-07 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_categories', '0002_alter_billcategory_description'),
        ('service_fee', '0021_alter_latepenaltytier_days_overdue_and_more'),
        ('service_fee_management', '0100_update_allocation_type_to_debit_credit'),
        ('towers', '0024_alter_unitresidenthistory_entry_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancepayment',
            name='source_payment_id',
        ),
        migrations.RemoveField(
            model_name='servicefeeitem',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='servicefeeitem',
            name='current_reading',
        ),
        migrations.RemoveField(
            model_name='servicefeeitem',
            name='previous_reading',
        ),
        migrations.RemoveField(
            model_name='servicefeeitem',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='servicefeeitem',
            name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='source_billing',
            field=models.ForeignKey(blank=True, help_text='Billing record (payment detail) that generated this advance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_advances', to='service_fee_management.servicefeebilling'),
        ),
        migrations.AlterField(
            model_name='servicefeepaymentallocation',
            name='allocation_type',
            field=models.CharField(choices=[('debit', 'Debit (Cash Payment)'), ('credit', 'Credit (Penalty Waiver)')], default='debit', help_text='Debit = cash payment received, Credit = waiver reduces liability', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicefeepaymentallocation',
            name='penalty_waiver',
            field=models.ForeignKey(blank=True, help_text="Related waiver record if allocation_type is 'credit'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='service_fee_management.penaltywaiver'),
        ),
        migrations.CreateModel(
            name='ServiceFeeBillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=20, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('previous_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_reading', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_bill_categories', to='bill_categories.billcategory')),
                ('service_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_bill_categories', to='service_fee.servicefee')),
                ('servicefeepaymentid', models.ForeignKey(help_text='Linked service fee payment', on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_bill_categories', to='service_fee_management.servicefeepayment')),
                ('tower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_bill_categories', to='towers.tower')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_bill_categories', to='towers.unit')),
            ],
            options={
                'verbose_name_plural': 'Service Fee Bill Categories',
                'db_table': 'service_fee_bill_categories',
                'ordering': ['unit__unit_name'],
            },
        ),
    ]
