# Generated by Django 5.2.7 on 2026-01-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0101_update_advancepayment_source_to_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeepaymentlatepenaltytier',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='Current status of this tier (only one tier should be active per payment)', max_length=20),
        ),
        migrations.AddField(
            model_name='servicefeepaymentlatepenaltytier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
