# Generated by Django 5.2.7 on 2026-01-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0102_servicefeepaymentlatepenaltytier_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billupload',
            name='file_name',
            field=models.CharField(blank=True, help_text='Original filename of the uploaded file', max_length=255, null=True),
        ),
    ]
