# Generated by Django 5.2.7 on 2026-01-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0103_billupload_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeepayment',
            name='account_holder_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='ID of the resident or owner record', null=True),
        ),
        migrations.AddField(
            model_name='servicefeepayment',
            name='account_holder_type',
            field=models.CharField(blank=True, choices=[('resident', 'Resident'), ('owner', 'Owner')], help_text='Type of account holder responsible for this fee', max_length=20, null=True),
        ),
    ]
