# Generated by Django 5.2.7 on 2026-01-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0104_servicefeepayment_account_holder_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='account_holder_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='ID of the resident or owner record', null=True),
        ),
        migrations.AddField(
            model_name='advancepayment',
            name='account_holder_type',
            field=models.CharField(blank=True, choices=[('resident', 'Resident'), ('owner', 'Owner')], help_text='Type of account holder who owns this advance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeepaymentallocation',
            name='allocation_type',
            field=models.CharField(choices=[('debit', 'Debit (Cash Payment)'), ('credit', 'Credit (Penalty Waiver)'), ('advance', 'Advance (Advance Adjustment)')], default='debit', help_text='Debit = cash payment received, Credit = waiver reduces liability', max_length=20),
        ),
    ]
