# Generated by Django 5.2.7 on 2026-01-15 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0021_alter_latepenaltytier_days_overdue_and_more'),
        ('service_fee_management', '0105_advancepayment_account_holder_id_and_more'),
        ('towers', '0024_alter_unitresidenthistory_entry_type'),
        ('user', '0003_member_terms_accepted_member_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeepayment',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', help_text='Primary contract owner (billing contact) - THE account holder', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_payments_as_owner', to='user.member'),
        ),
        migrations.AddField(
            model_name='servicefeepayment',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='Owner email snapshot at generation time', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicefeepayment',
            name='owner_name',
            field=models.CharField(blank=True, help_text='Owner name snapshot at generation time', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicefeepayment',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Owner phone snapshot at generation time', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeepayment',
            name='account_holder_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='DEPRECATED: Always equals owner_id for new bills. Use owner field instead.', null=True),
        ),
        migrations.AlterField(
            model_name='servicefeepayment',
            name='account_holder_type',
            field=models.CharField(blank=True, choices=[('resident', 'Resident'), ('owner', 'Owner')], help_text="DEPRECATED: Always 'owner' for new bills. Use owner field instead.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeepayment',
            name='resident',
            field=models.ForeignKey(blank=True, help_text='DEPRECATED: Legacy field, no longer populated during bill generation. Use owner field instead.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_fee_management_payments', to='user.member'),
        ),
        migrations.AddIndex(
            model_name='servicefeepayment',
            index=models.Index(fields=['owner', 'service_period_year', 'service_period_month'], name='idx_payment_owner_period'),
        ),
        migrations.AddIndex(
            model_name='servicefeepayment',
            index=models.Index(fields=['unit', 'service_period_year', 'service_period_month'], name='idx_payment_unit_period'),
        ),
        migrations.AddIndex(
            model_name='servicefeepayment',
            index=models.Index(fields=['service_status', 'payment_status'], name='idx_payment_status_combo'),
        ),
    ]
