# Generated by Django 5.2.7 on 2026-01-15 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_categories', '0002_alter_billcategory_description'),
        ('service_fee_management', '0106_servicefeepayment_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeeitem',
            name='penalty_tier',
            field=models.ForeignKey(blank=True, help_text='Penalty tier snapshot if item_type is penalty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_items', to='service_fee_management.servicefeepaymentlatepenaltytier'),
        ),
        migrations.AddIndex(
            model_name='servicefeeitem',
            index=models.Index(fields=['penalty_tier'], name='service_fee_penalty_d80218_idx'),
        ),
    ]
