# Generated by Django 5.2.7 on 2026-01-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0107_add_penalty_tier_to_servicefeeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeepaymentlatepenaltytier',
            name='penalty_calculation_basis',
            field=models.CharField(blank=True, help_text="Basis for penalty calculation (e.g., 'base_amount', 'total_amount')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicefeepaymentlatepenaltytier',
            name='tier_name',
            field=models.CharField(blank=True, help_text="Name of the penalty tier (e.g., 'Standard Penalty', 'Late Payment Fee')", max_length=100, null=True),
        ),
    ]
