# Generated by Django 5.2.7 on 2026-01-17 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_categories', '0002_alter_billcategory_description'),
        ('service_fee_management', '0108_servicefeepaymentlatepenaltytier_penalty_calculation_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeebilling',
            name='payment_type',
            field=models.CharField(choices=[('service_fee_bill_payment', 'Service Fee Bill Payment'), ('advance_payment', 'Advance Payment')], default='service_fee_bill_payment', help_text='Type of payment: regular bill payment or advance payment application', max_length=30),
        ),
        migrations.AddField(
            model_name='servicefeeitem',
            name='bill_upload_detail',
            field=models.ForeignKey(blank=True, help_text='Source bill upload detail that created this item (for bill_category items) - contains consumption and reading data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_items', to='service_fee_management.billuploaddetail'),
        ),
        migrations.AddIndex(
            model_name='servicefeeitem',
            index=models.Index(fields=['bill_upload_detail'], name='service_fee_bill_up_c12770_idx'),
        ),
    ]
