# Generated by Django 5.2.7 on 2026-01-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0109_add_bill_upload_detail_and_payment_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicefeepayment',
            table='service_fee_management_servicefeegenerate',
        ),
    ]
