# Generated by Django 5.2.7 on 2026-01-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0111_add_payment_penalty_tracking_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='account_holder_type',
            field=models.CharField(blank=True, choices=[('resident', 'Resident'), ('owner', 'Owner')], db_collation='utf8mb4_general_ci', help_text='Type of account holder who owns this advance', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicefeebilling',
            name='receipt_id',
            field=models.CharField(default='RCP-LEGACY', help_text='Unique receipt identifier (e.g., RCP-2024-01-00001)', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicefeebilling',
            name='transaction_id',
            field=models.CharField(default='TXN-LEGACY', help_text='Unique transaction identifier for each payment', max_length=100),
        ),
    ]
