# Generated by Django 5.2.7 on 2026-01-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0112_alter_advancepayment_account_holder_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='account_holder_type',
            field=models.CharField(blank=True, choices=[('resident', 'Resident'), ('owner', 'Owner')], db_collation='utf8mb4_0900_ai_ci', help_text='Type of account holder who owns this advance', max_length=20, null=True),
        ),
    ]
