# Generated by Django 5.2.7 on 2026-01-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0113_alter_advancepayment_account_holder_type'),
        ('towers', '0024_alter_unitresidenthistory_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicefeepayment',
            name='owner',
            field=models.ForeignKey(blank=True, db_column='owner_id', help_text='Primary contract owner (billing contact) - THE account holder', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_fee_payments', to='towers.owner'),
        ),
    ]
