# Generated by Django 5.2.7 on 2026-01-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0114_alter_servicefeepayment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeebilling',
            name='advance_payment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Related advance payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_receipts', to='service_fee_management.advancepayment'),
        ),
        migrations.AlterField(
            model_name='servicefeebilling',
            name='servicefeepaymentid',
            field=models.ForeignKey(blank=True, db_constraint=False, default=29, help_text='Related payment transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='service_fee_management.servicefeepayment'),
        ),
    ]
