# Generated by Django 5.2.7 on 2026-01-25 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account_openingcredit_account_openingdebit'),
        ('service_fee_management', '0115_servicefeebilling_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='penaltywaiver',
            name='default_account_head',
            field=models.ForeignKey(blank=True, help_text='Accounting head for this waiver adjustement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_waivers', to='accounts.defaultaccounthead'),
        ),
    ]
