# Generated by Django 5.2.7 on 2026-01-25 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_account_openingcredit_account_openingdebit'),
        ('service_fee_management', '0116_penaltywaiver_default_account_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='default_account',
            field=models.ForeignKey(blank=True, help_text='Accounting head for this payment method', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='accounts.account'),
        ),
    ]
