# Generated by Django 5.2.7 on 2026-01-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0022_servicefee_service_fee_is_acti_19558f_idx_and_more'),
        ('service_fee_management', '0117_paymentmethod_default_account'),
        ('towers', '0024_alter_unitresidenthistory_entry_type'),
        ('user', '0003_member_terms_accepted_member_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advancepayment',
            index=models.Index(fields=['account_holder_type', 'account_holder_id'], name='service_fee_account_1be1e7_idx'),
        ),
        migrations.AddIndex(
            model_name='billuploaddetail',
            index=models.Index(fields=['unit', 'service_fee', 'upload_year', 'upload_month'], name='bill_upload_unit_id_54da05_idx'),
        ),
        migrations.AddIndex(
            model_name='billuploaddetail',
            index=models.Index(fields=['service_fee', 'upload_year', 'upload_month'], name='bill_upload_service_ee0914_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeebilling',
            index=models.Index(fields=['transaction_id'], name='service_fee_transac_e26513_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeebilling',
            index=models.Index(fields=['receipt_id'], name='service_fee_receipt_00cd85_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeebilling',
            index=models.Index(fields=['payment_date'], name='service_fee_payment_e1ba29_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeebilling',
            index=models.Index(fields=['servicefeepaymentid', '-payment_date'], name='service_fee_service_3a79de_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeebilling',
            index=models.Index(fields=['reference_number'], name='service_fee_referen_17c9f3_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeebilling',
            index=models.Index(fields=['payment_type'], name='service_fee_payment_99d8d9_idx'),
        ),
        migrations.AddIndex(
            model_name='servicefeepayment',
            index=models.Index(fields=['service_fee', 'service_period_year', 'service_period_month'], name='idx_payment_fee_period'),
        ),
        migrations.AddIndex(
            model_name='servicefeepayment',
            index=models.Index(fields=['unit', 'service_fee', 'service_period_year', 'service_period_month'], name='idx_payment_unique_bill'),
        ),
    ]
