# Generated by Django 5.2.7 on 2026-01-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0118_advancepayment_service_fee_account_1be1e7_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='servicefeepaymentallocation',
            index=models.Index(fields=['service_fee_billing', 'service_fee_item'], name='service_fee_service_95a3b2_idx'),
        ),
    ]
