# Generated by Django 5.2.8 on 2026-01-29 11:45

import django.db.models.deletion
from django.db import migrations, models


def safe_drop_constraints(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
        
    db_name = schema_editor.connection.settings_dict['NAME']
    columns = ['advance_payment_id', 'servicefeepaymentid_id']
    
    with schema_editor.connection.cursor() as cursor:
        for col in columns:
            # Find constraints on these columns
            cursor.execute("""
                SELECT CONSTRAINT_NAME 
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
                WHERE TABLE_NAME = 'service_fee_payment_details' 
                AND TABLE_SCHEMA = %s 
                AND COLUMN_NAME = %s
                AND REFERENCED_TABLE_NAME IS NOT NULL
            """, [db_name, col])
            
            for (fk_name,) in cursor.fetchall():
                try:
                    cursor.execute(f"ALTER TABLE service_fee_payment_details DROP FOREIGN KEY {fk_name}")
                except Exception:
                    pass

class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0119_servicefeepaymentallocation_service_fee_service_95a3b2_idx'),
    ]

    operations = [
        migrations.RunPython(safe_drop_constraints, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='servicefeebilling',
            name='advance_payment',
            field=models.ForeignKey(blank=True, help_text='Related advance payment record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_receipts', to='service_fee_management.advancepayment'),
        ),
        migrations.AlterField(
            model_name='servicefeebilling',
            name='servicefeepaymentid',
            field=models.ForeignKey(blank=True, default=29, help_text='Related payment transaction', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='service_fee_management.servicefeepayment'),
        ),
    ]
