# Generated by Django 5.2.8 on 2026-02-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0120_alter_servicefeebilling_advance_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayStationTransactionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text='PayStation invoice number', max_length=100, unique=True)),
                ('payment_ids', models.TextField(help_text='Comma-separated payment IDs')),
                ('unit_id', models.IntegerField(help_text='Unit ID')),
                ('service_fee_id', models.IntegerField(help_text='Service Fee ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total transaction amount', max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Additional reference information', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this mapping expires (24 hours from creation)')),
            ],
            options={
                'db_table': 'service_fee_paystation_transaction_mapping',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SSLCommerzTransactionMapping',
        ),
    ]
