# Generated by Django 5.2.8 on 2026-02-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0121_paystationtransactionmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystationtransactionmapping',
            name='is_advance_payment',
            field=models.BooleanField(default=False, help_text='Whether this is an advance payment'),
        ),
    ]
