# Generated by Django 5.2.8 on 2026-02-05 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0118_add_payment_gateway_field'),
        ('service_fee_management', '0123_add_payment_result_status_to_billing'),
    ]

    operations = [
    ]
