# Generated by Django 5.2.8 on 2026-02-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0124_merge_20260205_1237'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicefeebilling',
            name='service_fee_payment_gateway_idx',
        ),
    ]
