# Generated by Django 5.2.8 on 2026-02-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0125_remove_servicefeebilling_service_fee_payment_gateway_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='advance_type',
            field=models.CharField(choices=[('auto_excess', 'Auto-generated from excess payment'), ('service_fee_advance', 'Service Fee Advance'), ('advance_payment', 'Advance Payment'), ('other_advance', 'Other Advance')], default='auto_excess', help_text='How advance payment was created', max_length=20),
        ),
    ]
