# Generated by Django 5.2.8 on 2026-02-05 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0126_alter_advancepayment_advance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancepayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Payment method used to create this advance payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments', to='service_fee_management.paymentmethod'),
        ),
    ]
