# Generated by Django 5.2.8 on 2026-02-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0127_add_payment_method_to_advance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('mfs', 'Mobile Financial Services (MFS)')], default='cash', help_text='Categorization of the payment method', max_length=20),
        ),
    ]
