# Generated by Django 5.2.8 on 2026-02-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee_management', '0128_paymentmethod_method_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account_name',
            field=models.CharField(blank=True, help_text='Name of the account holder (e.g. Company Name)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account number/Phone number for receiving payments', max_length=100, null=True),
        ),
    ]
