# Generated by Django 5.2.8 on 2026-02-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_fee', '0022_servicefee_service_fee_is_acti_19558f_idx_and_more'),
        ('service_fee_management', '0129_paymentmethod_account_name_and_more'),
        ('towers', '0025_floor_towers_floo_tower_i_35871b_idx_and_more'),
        ('user', '0004_create_django_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefeepayment',
            name='bill_number',
            field=models.CharField(blank=True, help_text='Unique bill number (e.g., BILL-2024-01-00001)', max_length=100, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='servicefeepayment',
            index=models.Index(fields=['bill_number'], name='idx_payment_bill_number'),
        ),
    ]
