# Generated by Django 5.2.5 on 2025-08-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_remove_notice_description_remove_notice_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='title',
        ),
    ]
