# Generated by Django 5.2.5 on 2025-08-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0006_remove_notice_description_remove_notice_title'),
    ]

    operations = [
        # This migration does nothing - the fields were already removed in previous migrations
        # This is a no-op migration to maintain migration history consistency
    ]
