# Generated by Django 5.2.3 on 2025-11-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_role', '0005_add_additional_permissions'),
        ('noticeboard', '0007_remove_notice_description_remove_notice_title'),
        ('towers', '0011_alter_owner_unique_together_delete_vehicle'),
        ('user', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['-is_pinned', '-created_at'], name='noticeboard_is_pinn_b79bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['status', '-created_at'], name='noticeboard_status_eff45f_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['priority'], name='noticeboard_priorit_df1805_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['start_date', 'end_date'], name='noticeboard_start_d_fc64f3_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['creator'], name='noticeboard_creator_121cd3_idx'),
        ),
    ]
