# Generated by Django 5.2.3 on 2025-11-18 14:32

import company_settings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=company_settings.models.upload_to_company_logo, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])])),
                ('login_page_image', models.ImageField(blank=True, null=True, upload_to=company_settings.models.upload_to_login_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])])),
                ('company_name', models.CharField(default='Estate Link', max_length=255)),
                ('company_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
