# Generated by Django 5.2.3 on 2025-11-18 14:54

import company_settings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_type', models.CharField(choices=[('logo', 'Logo'), ('login_image', 'Login Page Image')], max_length=20)),
                ('image', models.ImageField(upload_to=company_settings.models.upload_to_company_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Image',
                'verbose_name_plural': 'Company Images',
                'ordering': ['-created_at'],
            },
        ),
    ]

