# Generated by Django 5.2.3 on 2025-11-18 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0002_data_migrate_existing_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='login_page_image',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='active_login_image',
            field=models.ForeignKey(blank=True, limit_choices_to={'image_type': 'login_image'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_login_image_settings', to='company_settings.companyimage'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='active_logo',
            field=models.ForeignKey(blank=True, limit_choices_to={'image_type': 'logo'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_logo_settings', to='company_settings.companyimage'),
        ),
    ]

