# Generated by Django 5.2.3 on 2025-11-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0004_set_initial_active_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
