# Generated by Django 5.1.4 on 2025-05-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_role', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersrole',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membersrole',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
